docs(cn): translate learn/choosing-the-state-structure into Chinese
reactjs/zh-hans.react.dev pull request #1094
Opened 2023-03-23 13:04 UTC by Davont

翻译 [choosing-the-state-structure](https://react.dev/learn/choosing-the-state-structure)
之前的翻译 PR #638 已经过时，现已更新 

感谢检视！ @QC-L  @awxiaoxian2020

2023-03-23 14:45 UTC, awxiaoxian2020 requested changes

2023-03-23 14:45 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +* 何时使用单个 state 变量和多个 state 变量
```suggestion
* 使用单个 state 变量还是多个 state 变量
```

2023-03-23 14:45 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +  // 这个 `color` state 变量用于保存 `initialColor` 的 *初始值* 值。
```suggestion
  // 这个 `color` state 变量用于保存 `initialColor` 的 *初始值*。
```

2023-03-23 14:45 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +为什么这是个问题？ 让我们使每个项目都可以编辑：
```suggestion
为什么这是个问题？让我们使每个项目都可以编辑：
```
在渲染没有问题的情况下，请删除中文之间的空格。

2023-03-24 05:22 UTC, Davont commented
我好像删除了两位审稿人 @daochouwangu  和 @Yucohny 请求

麻烦您重新加上，再次感谢审核！

2023-04-05 10:26 UTC, awxiaoxian2020 requested changes
请根据最新的 wiki 调整加粗和空格的相关问题

2023-04-09 13:55 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +这些原则背后的目标是*使 state 易于更新而不引入错误*。从 state 中删除冗余和重复数据有助于确保所有部分保持同步。这类似于数据库工程师想要 [“规范化”数据库结构](https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description)，以减少出现错误的机会。用爱因
```suggestion
这些原则背后的目标是 **使 state 易于更新而不引入错误**。从 state 中删除冗余和重复数据有助于确保所有部分保持同步。这类似于数据库工程师想要 [“规范化”数据库结构](https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description)，以减少出现错误的机会。用爱因斯坦的话说，**“让你的状态尽可能简单，但不要过于简单。”**
```

2023-04-09 13:55 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +这里，`fullName` *不是* 一个 state 变量。相反，它是在渲染期间中计算出的：
```suggestion
这里的 `fullName` **不是** 一个 state 变量。相反，它是在渲染期间中计算出的：
```

2023-04-09 13:55 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +因此，更改处理程序不需要做任何特殊操作来更新它。 当你调用 `setFirstName` 或 `setLastName` 时，你会触发一次重新渲染，然后下一个 `fullName` 将从新数据中计算出来。。
```suggestion
因此，更改处理程序不需要做任何特殊操作来更新它。 当你调用 `setFirstName` 或 `setLastName` 时，你会触发一次重新渲染，然后下一个 `fullName` 将从新数据中计算出来。
```

2023-04-09 13:55 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +这就是为什么在 state 变量中，"镜像"一些 prop 属性会导致混淆的原因。相反，你要在代码中直接使用 `messageColor` 属性。如果你想给它起一个更短的名称，请使用常量：
```suggestion
这就是为什么在 state 变量中，“镜像”一些 prop 属性会导致混淆的原因。相反，你要在代码中直接使用 `messageColor` 属性。如果你想给它起一个更短的名称，请使用常量：
```

2023-04-09 13:56 UTC, Yucohny commented
请再检查一下标点以及空格问题。除此之外，[翻译指南](https://github.com/reactjs/zh-hans.react.dev/wiki/React-Translation-Guide) 更新了一点说明，中文斜体统一修改为加粗。烦请检查一下~

2023-04-10 13:30 UTC, Davont commented
> 请再检查一下标点以及空格问题。除此之外，[翻译指南](https://github.com/reactjs/zh-hans.react.dev/wiki/React-Translation-Guide) 更新了一点说明，中文斜体统一修改为加粗。烦请检查一下~

感谢检视，已经修改完成！

2023-04-10 13:47 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +**如果 state 嵌套太深，难以轻松更新，可以考虑将其“扁平化”。** 这里有一个方法可以重构上面这个数据。不同于树状结构，它每个`节点`都有 **其子节点** 数组，你可以让每个`节点`保存一个 **其子节点ID** 的数组。然后存储一个节点 ID 与相应节点的映射关系。
```suggestion
**如果 state 嵌套太深，难以轻松更新，可以考虑将其“扁平化”。** 这里有一个方法可以重构上面这个数据。不同于树状结构，它每个`节点`都有 **其子节点** 数组，你可以让每个`节点`保存一个 **其子节点 ID** 的数组。然后存储一个节点 ID 与相应节点的映射关系。
```

2023-04-10 13:47 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +- 其 **父级** 地点的更新版本应该从其 `childIds` 数组中排除已删除的ID。
```suggestion
- 其 **父级** 地点的更新版本应该从其 `childIds` 数组中排除已删除的 ID。
```

2023-04-10 13:47 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +理想情况下，您还应该从“表”对象中删除已删除的项目（以及它们的子项！）以改善内存使用。还可以 [使用Immer](/learn/updating-objects-in-state#write-concise-update-logic-with-immer) 使更新逻辑更加简洁。
```suggestion
理想情况下，您还应该从“表”对象中删除已删除的项目（以及它们的子项！）以改善内存使用。还可以 [使用 Immer](/learn/updating-objects-in-state#write-concise-update-logic-with-immer) 使更新逻辑更加简洁。
```

2023-04-10 13:47 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +这个问题点在于此组件的 `color` state 是使用`color` prop 的初始值进行初始化的。但是当 `color` prop 值发生更改时，这不会影响 state 变量！因此它们会失去同步。为了解决这个问题，完全删除 state 变量，并直接使用 `color` prop 即可。
```suggestion
这个问题点在于此组件的 `color` state 是使用 `color` prop 的初始值进行初始化的。但是当 `color` prop 值发生更改时，这不会影响 state 变量！因此它们会失去同步。为了解决这个问题，完全删除 state 变量，并直接使用 `color` prop 即可。
```

2023-04-10 13:47 UTC, Yucohny commented
仍然存在许多空格问题，烦请再检查一下~

2023-04-11 03:07 UTC, Davont commented on src/content/learn/choosing-the-state-structure.md
> +- 其 **父级** 地点的更新版本应该从其 `childIds` 数组中排除已删除的ID。
已解决

2023-04-11 03:08 UTC, Davont commented on src/content/learn/choosing-the-state-structure.md
> +理想情况下，您还应该从“表”对象中删除已删除的项目（以及它们的子项！）以改善内存使用。还可以 [使用Immer](/learn/updating-objects-in-state#write-concise-update-logic-with-immer) 使更新逻辑更加简洁。
已解决

2023-04-11 03:08 UTC, Davont commented on src/content/learn/choosing-the-state-structure.md
> +这个问题点在于此组件的 `color` state 是使用`color` prop 的初始值进行初始化的。但是当 `color` prop 值发生更改时，这不会影响 state 变量！因此它们会失去同步。为了解决这个问题，完全删除 state 变量，并直接使用 `color` prop 即可。
已解决

2023-04-11 03:34 UTC, Davont commented
> 仍然存在许多空格问题，烦请再检查一下~

再次感谢指出问题，自查一遍后，现已更改。

2023-04-11 11:57 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +
```suggestion
```

2023-04-11 20:58 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +为了解决这个问题，请从 state 中删除重复项。不要在两个地方存储 `字母对象本身`，而是存储 `highlightedId`。然后，您可以使用 `letter.id === highlightedId` 检查每个带有 `isHighlighted` 属性的字母，即使 `letter` 对象在上次渲染后发生了变化，这也是可行的。
```suggestion
为了解决这个问题，请从 state 中删除重复项。不要在两个地方存储 **字母对象本身**，而是存储 `highlightedId`。然后，您可以使用 `letter.id === highlightedId` 检查每个带有 `isHighlighted` 属性的字母，即使 `letter` 对象在上次渲染后发生了变化，这也是可行的。
```

2023-04-11 20:58 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +**如果 state 嵌套太深，难以轻松更新，可以考虑将其“扁平化”。** 这里有一个方法可以重构上面这个数据。不同于树状结构，它每个`节点`都有 **其子节点** 数组，你可以让每个`节点`保存一个 **其子节点 ID** 的数组。然后存储一个节点 ID 与相应节点的映射关系。
```suggestion
**如果 state 嵌套太深，难以轻松更新，可以考虑将其“扁平化”。** 这里有一个方法可以重构上面这个数据。不同于树状结构，每个节点的 `place` 都是一个包含 **其子节点** 的数组，你可以让每个节点的 `place` 作为数组保存 **其子节点的 ID**。然后存储一个节点 ID 与相应节点的映射关系。
```

2023-04-11 20:58 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +当前，它将所选菜作为对象存储在 `selectedItem` state 变量中。然而，这并不好：**`selectedItem` 的内容与 `items` 列表中的某个项是同一个对象。** 这意味着关于该项本身的信息在两个地方产生了重复。
```suggestion
当前，它将所选元素作为对象存储在 `selectedItem` state 变量中。然而，这并不好：**`selectedItem` 的内容与 `items` 列表中的某个项是同一个对象。** 这意味着关于该项本身的信息在两个地方产生了重复。
```

2023-04-11 20:58 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +  // 这个 `color` state 变量用于保存 `initialColor` 的 *初始值*。
```suggestion
  // 这个 `color` state 变量用于保存 `initialColor` 的 **初始值**。
```

2023-04-11 20:58 UTC, Yucohny commented on src/content/learn/choosing-the-state-structure.md
> +**因为 `isSending` 和 `isSent` 不应同时为 `true`，所以最好用一个 `status` 变量来代替它们，这个 state 变量可以采取 *三种* 有效状态其中之一**：`'typing'` (初始), `'sending'`, 和 `'sent'`:
```suggestion
**因为 `isSending` 和 `isSent` 不应同时为 `true`，所以最好用一个 `status` 变量来代替它们，这个 state 变量可以采取三种有效状态其中之一**：`'typing'` (初始), `'sending'`, 和 `'sent'`:
```

2023-04-12 01:37 UTC, Davont commented on src/content/learn/choosing-the-state-structure.md
> +请注意，如果你首先单击菜单上的“Choose” **然后** 编辑它，**输入会更新，但底部的标签不会反映编辑内容。** 这是因为你有重复的 state，并且你忘记更新了 `selectedItem`。
您好，此处修改没有发生变化

2023-04-12 01:38 UTC, Davont commented
已更新~

2023-04-15 14:27 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +
```suggestion
```

2023-04-15 14:30 UTC, awxiaoxian2020 requested changes

2023-04-15 14:30 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +
```suggestion
```
从这里开始，似乎有多余的空行，请检查调整

2023-04-20 07:11 UTC, awxiaoxian2020 requested changes

2023-04-20 07:11 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +这里，一个 `color` state 变量被初始化为 `messageColor` 的 props 值。这段代码的问题在于，**如果父组件稍后传递不同的 `messageColor` 值（例如，将其从 `'blue'` 更改为 `'red'`），则 `color`** state 变量**将不会更新！** state 仅在第一次渲染期间初始化。
```suggestion
这里，一个 `color` state 变量被初始化为 `messageColor` 的 prop 值。这段代码的问题在于，**如果父组件稍后传递不同的 `messageColor` 值（例如，将其从 `'blue'` 更改为 `'red'`），则 `color`** state 变量**将不会更新！** state 仅在第一次渲染期间初始化。
```

2023-04-20 07:11 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +现在，如果你编辑 **selected** 项目，下面的消息将立即更新。这是因为 `setItems` 会触发重新渲染，而 `items.find(...)` 会找到带有更新文本的项目。你不需要在 state 中保存 **选定的项目**，因为只有 **选定的 ID** 是必要的。其余的可以在渲染期间计算。
不应翻译为“项目”

2023-04-22 07:22 UTC, Davont commented on src/content/learn/choosing-the-state-structure.md
> +现在，如果你编辑 **selected** 项目，下面的消息将立即更新。这是因为 `setItems` 会触发重新渲染，而 `items.find(...)` 会找到带有更新文本的项目。你不需要在 state 中保存 **选定的项目**，因为只有 **选定的 ID** 是必要的。其余的可以在渲染期间计算。
参考 [Yucohny](https://github.com/Yucohny) ，翻译成 ”元素“

2023-04-22 07:22 UTC, Davont commented
已经更新解决，辛苦检视～

2023-04-27 06:24 UTC, Davont commented
@awxiaoxian2020  打扰下，我看 pr 的最下文显示 :
`Merging can be performed automatically once the requested changes are addressed.`

但是我已经更改好了，没看到哪里没有修改的，请问这个怎么解决呢？

2023-04-27 06:43 UTC, awxiaoxian2020 commented
> @awxiaoxian2020 打扰下，我看 pr 的最下文显示 : `Merging can be performed automatically once the requested changes are addressed.`
> 
> 但是我已经更改好了，没看到哪里没有修改的，请问这个怎么解决呢？

这只是因为我使用了 request changes 且我并没有更新我的 review 状态，所以只要我没有 approve，那么就会一直是这个状态，并不会因为你的提交而改变~不用管它

2023-05-05 05:24 UTC, awxiaoxian2020 approved these changes

2023-05-12 03:28 UTC, merged