docs(cn): translate content/reference/react/useContext.md into Chinese
reactjs/zh-hans.react.dev pull request #1097
Opened 2023-03-24 06:51 UTC by BetterZxx

翻译 useContext.md

@awxiaoxian2020 @QC-L 
辛苦检阅了

2023-03-25 22:56 UTC, awxiaoxian2020 requested changes

2023-03-25 22:56 UTC, awxiaoxian2020 commented on src/content/reference/react/useContext.md
> +         Use dark mode
```suggestion
        Use dark mode
```

2023-04-10 11:06 UTC, awxiaoxian2020 commented
请根据 wiki 调整格式~

2023-04-10 13:53 UTC, Yucohny commented on src/content/reference/react/useContext.md
> +在组件的顶层调用 `useContext` 来读取和订阅 [context。](/learn/passing-data-deeply-with-context)
```suggestion
在组件的顶层调用 `useContext` 来读取和订阅 [context](/learn/passing-data-deeply-with-context)。
```

2023-04-10 13:53 UTC, Yucohny commented on src/content/reference/react/useContext.md
> +`useContext()` 总是在调用它的组件 *上面* 寻找最近的 provider。它向上搜索， **不考虑** 调用 `useContext()` 的组件中的 provider。
```suggestion
`useContext()` 总是在调用它的组件 **上面** 寻找最近的 provider。它向上搜索， **不考虑** 调用 `useContext()` 的组件中的 provider。
```

2023-04-10 13:53 UTC, Yucohny commented on src/content/reference/react/useContext.md
> +这里，与 `Footer` 外的值为（`"dark"`）的按钮相比， *里面* 的按钮接收到一个不一样的 context 值（`"light"`）。
```suggestion
这里，与 `Footer` 外的值为（`"dark"`）的按钮相比，**里面** 的按钮接收到一个不一样的 context 值（`"light"`）。
```

2023-04-10 13:53 UTC, Yucohny commented on src/content/reference/react/useContext.md
> +此处，<CodeStep step={2}>context value</CodeStep> 是一个具有两个属性的 JavaScript 对象，其中一个是函数。每当 `MyApp` 出现重新渲染（例如，路由更新）时，这里将会是一个 *不同的* 对象指向 *不同的* 函数，因此 React 还必须重新渲染树中调用 `useContext(AuthContext)` 的所有组件。
```suggestion
此处，<CodeStep step={2}>context value</CodeStep> 是一个具有两个属性的 JavaScript 对象，其中一个是函数。每当 `MyApp` 出现重新渲染（例如，路由更新）时，这里将会是一个 **不同的** 对象指向 **不同的** 函数，因此 React 还必须重新渲染树中调用 `useContext(AuthContext)` 的所有组件。
```

2023-04-10 13:53 UTC, Yucohny commented on src/content/reference/react/useContext.md
> +### 我总从 context 中得到 `undefined` 尽管设置了不一样的默认值 {/*i-am-always-getting-undefined-from-my-context-although-the-default-value-is-different*/}
```suggestion
### 尽管设置了不一样的默认值，但是我总是从 context 中得到 `undefined` {/*i-am-always-getting-undefined-from-my-context-although-the-default-value-is-different*/}
```

2023-04-10 13:53 UTC, Yucohny commented on src/content/reference/react/useContext.md
> +注意，只有在 **上层根本没有匹配的 provider** 时才使用 [`createContext(defaultValue)`调用的默认值](#specifying-a-fallback-default-value)。如果存在 `<SomeContext.Provider value={undefined}>` 组件在父树的某个位置，调用 `useContext(SomeContext)`
```suggestion
注意，只有在 **上层根本没有匹配的 provider** 时才使用 [`createContext(defaultValue)`调用的默认值](#specifying-a-fallback-default-value)。如果存在 `<SomeContext.Provider value={undefined}>` 组件在父树的某个位置，调用 `useContext(SomeContext)` 的组件 **将会** 接收到 `undefined` 作为 context 的值。
```

2023-04-15 10:51 UTC, Yucohny commented on src/content/reference/react/useContext.md
> +1. 你在调用 `useContext()` 的同一组件（或下层）渲染 `<SomeContext.Provider>`。把 `<SomeContext.Provider>` 向调用 `useContext()` 组件 *之上和之外* 移动。
```suggestion
1. 你在调用 `useContext()` 的同一组件（或下层）渲染 `<SomeContext.Provider>`。把 `<SomeContext.Provider>` 向调用 `useContext()` 组件 **之上和之外** 移动。
```

2023-04-20 07:35 UTC, awxiaoxian2020 approved these changes

2023-04-23 13:35 UTC, Yucohny approved these changes

2023-04-23 13:35 UTC, merged