docs(cn): translate content/reference/react/index.md into Chinese
reactjs/zh-hans.react.dev pull request #1098
Opened 2023-03-24 07:18 UTC by thehelium

Translate content/reference/react/index.md into Chinese.

翻译 content/reference/react/index.md 至中文。

2023-03-24 09:46 UTC, awxiaoxian2020 requested changes
还有几处标题没有翻译，请翻译

2023-03-24 09:46 UTC, awxiaoxian2020 commented on src/content/reference/react/index.md
> +title: "内置 React Hooks"
```suggestion
title: "内置 React Hook"
```
请一并调整单数

2023-03-24 10:09 UTC, thehelium commented on src/content/reference/react/index.md
> +title: "内置 React Hooks"
已整改完毕，请查阅

2023-03-25 22:52 UTC, awxiaoxian2020 requested changes

2023-03-25 22:52 UTC, awxiaoxian2020 commented on src/content/reference/react/index.md
> +*Hook* 让你从你的组件中使用不同的 React 功能。你可以使用内置的 Hook 或者结合它们来建立你自己的。本页列出了 React 中所有的内置 Hook。
```suggestion
*Hook* 让你可以在组件中使用不同的 React 功能。你可以使用内置的 Hook 或者把它们组合起来建立你自己的。本页列出了 React 中所有的内置 Hook。
```

2023-03-25 22:52 UTC, awxiaoxian2020 commented on src/content/reference/react/index.md
> +*State* 让一个组件 ["记住" 像用户输入的信息](/learn/state-a-components-memory)，比如，要给一个组件添加状态，使用这些 Hook 中的一个：
这里似乎漏翻了。

2023-03-26 01:27 UTC, thehelium commented on src/content/reference/react/index.md
> +*State* 让一个组件 ["记住" 像用户输入的信息](/learn/state-a-components-memory)，比如，要给一个组件添加状态，使用这些 Hook 中的一个：
> 

已整改完毕，请查阅。

2023-03-27 23:27 UTC, awxiaoxian2020 requested changes

2023-03-27 23:27 UTC, awxiaoxian2020 commented on src/content/reference/react/index.md
> +*State* 让一个组件 ["记住" 像用户输入的信息](/learn/state-a-components-memory)，比如，一个表单组件可以使用状态来存储输入值，而一个图片库组件可以使用状态来存储选定的图片索引。
```suggestion
*state* 让一个组件 [“记住”像用户输入的信息](/learn/state-a-components-memory)，比如，一个表单组件可以使用 state 来存储输入值，而一个图片库组件可以使用 state 来存储选定的图片索引。
```
请视情况翻译为 state，下文一并修改。

2023-03-29 08:13 UTC, fwqaaq requested changes

2023-03-29 08:13 UTC, fwqaaq commented on src/content/reference/react/index.md
> +你也可以在 JavaScript 函数中[定义你自己的 Hook。](/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component)
```suggestion
你也可以在 JavaScript 函数中 [定义你自己的 Hook](/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component)。
```

2023-03-29 08:13 UTC, fwqaaq commented on src/content/reference/react/index.md
> +要确定渲染的优先级，可以使用这些 Hook 的一个：
```suggestion
要确定渲染的优先级，可以使用以下 Hook 其中之一：
```

2023-03-29 08:13 UTC, fwqaaq commented on src/content/reference/react/index.md
> +你也可以在 JavaScript 函数中[定义你自己的 Hook。](/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component)
[这里是 React 中文排版](https://github.com/reactjs/zh-hans.react.dev/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97)

2023-04-09 09:22 UTC, Yucohny commented on src/content/reference/react/index.md
> +*Context* 让一个组件[从远处的父组件接收信息，而不需要将其作为 props 传递](/learn/passing-props-to-a-component)。比如，app 的顶层组件可以将当前的 UI 主题传递给下面的所有组件，无论它们层级多深。
```suggestion
*Context* 让一个组件 [从远处的父组件接收信息，而不需要将其作为 props 传递](/learn/passing-props-to-a-component)。比如，app 的顶层组件可以将当前的 UI 主题传递给下面的所有组件，无论它们层级多深。
```

2023-04-09 09:22 UTC, Yucohny commented on src/content/reference/react/index.md
> +*Ref* 让一个组件[持有一些不用于渲染的信息](/learn/referencing-values-with-refs)，如 DOM 节点或一个 timeout ID。与 state 不同的是，更新 Ref 并不会重新渲染你的组件。Ref 是 React 范式的一个 "逃生舱门"。当你需要与非 React 系统一起工作时，它们很有用，比如内置的浏览器 API。
```suggestion
*Ref* 让一个组件 [持有一些不用于渲染的信息](/learn/referencing-values-with-refs)，如 DOM 节点或一个 timeout ID。与 state 不同的是，更新 Ref 并不会重新渲染你的组件。Ref 是 React 范式的一个 "逃生舱门"。当你需要与非 React 系统一起工作时，它们很有用，比如内置的浏览器 API。
```

2023-04-09 09:22 UTC, Yucohny commented on src/content/reference/react/index.md
> +Effect 是 React 范式的 "逃生舱门"。不要用 Effect 来协调你的应用程序的数据流。如果你不与外部系统交互，[你可能不需要 Effect](/learn/you-might-not-need-an-effect)。
```suggestion
Effect 是 React 范式的“逃生舱门”。不要用 Effect 来协调你的应用程序的数据流。如果你不与外部系统交互，[你可能不需要 Effect](/learn/you-might-not-need-an-effect)。
```

2023-04-10 04:07 UTC, Yucohny commented on src/content/reference/react/index.md
> +* [`useImperativeHandle`](/reference/react/useImperativeHandle) 可以让你自定义你的组件所暴露的 Ref。这一点很少使用。
```suggestion
* [`useImperativeHandle`](/reference/react/useImperativeHandle) 可以让你自定义你的组件所暴露的 ref。这一点很少使用。
```

2023-04-11 20:59 UTC, Yucohny submitted a review, later dismissed

2023-04-12 02:43 UTC, fwqaaq commented on src/content/reference/react/index.md
> +* [`useReducer`](/reference/react/useReducer) 声明了一个带有更新逻辑的 state 变量在一个 [reducer 函数](/learn/extracting-state-logic-into-a-reducer)中。
```suggestion
* [`useReducer`](/reference/react/useReducer) 声明了一个带有更新逻辑的 state 变量在一个 [reducer 函数](/learn/extracting-state-logic-into-a-reducer) 中。
```

2023-04-12 02:43 UTC, fwqaaq commented on src/content/reference/react/index.md
> +*Effect* 让一个组件[连接到外部系统并与之同步](/learn/synchronizing-with-effects)。这包括处理网络、浏览器、DOM、动画、使用不同 UI 库编写的 widgets 以及其他非 React 代码。
```suggestion
*Effect* 让一个组件 [连接到外部系统并与之同步](/learn/synchronizing-with-effects)。这包括处理网络、浏览器、DOM、动画、使用不同 UI 库编写的 widgets 以及其他非 React 代码。
```

2023-04-12 02:46 UTC, fwqaaq commented on src/content/reference/react/index.md
> +*Effect* 让一个组件[连接到外部系统并与之同步](/learn/synchronizing-with-effects)。这包括处理网络、浏览器、DOM、动画、使用不同 UI 库编写的 widgets 以及其他非 React 代码。
这里的 wigest 应该可以翻译吧？我不太清楚

2023-04-12 02:48 UTC, fwqaaq commented on src/content/reference/react/index.md
> +* [`useInsertionEffect`](/reference/react/useInsertionEffect) 在 React 对 DOM 进行修改之前触发。Libraries 可以在这里插入动态 CSS。
这里也怪怪地？

2023-04-12 07:31 UTC, thehelium commented on src/content/reference/react/index.md
> +*Effect* 让一个组件[连接到外部系统并与之同步](/learn/synchronizing-with-effects)。这包括处理网络、浏览器、DOM、动画、使用不同 UI 库编写的 widgets 以及其他非 React 代码。
> 这里的 wigest 应该可以翻译吧？我不太清楚

也可以翻译成组件或部件。组件对应的英文应该为 component，但又脱离了原文对应的单词，所以保留了原文单词未翻译。此项可在审核讨论后更改。

2023-04-20 07:17 UTC, awxiaoxian2020 requested changes

2023-04-20 07:17 UTC, awxiaoxian2020 commented on src/content/reference/react/index.md
> +要给一个组件添加状态，使用这些 Hook 中的一个：
```suggestion
要给一个组件添加状态，可以使用这些 Hook 中的一个：
```

2023-04-20 07:17 UTC, awxiaoxian2020 commented on src/content/reference/react/index.md
> +*Context* 让一个组件 [从远处的父组件接收信息，而不需要将其作为 props 传递](/learn/passing-props-to-a-component)。比如，app 的顶层组件可以将当前的 UI 主题传递给下面的所有组件，无论它们层级多深。
```suggestion
*context* 让一个组件 [从远处的父组件接收信息，而不需要将其作为 props 传递](/learn/passing-props-to-a-component)。比如，app 的顶层组件可以将当前的 UI 主题传递给下面的所有组件，无论它们层级多深。
```

2023-04-20 07:17 UTC, awxiaoxian2020 commented on src/content/reference/react/index.md
> +* [`useContext`](/reference/react/useContext) 读取并订阅了一个上下文。
```suggestion
* [`useContext`](/reference/react/useContext) 读取并订阅了一个 context。
```

2023-05-18 15:06 UTC, loveloki commented on src/content/reference/react/index.md
> +要跳过计算和不必要的重新渲染，请使用这些 Hook 的一个：
```suggestion
要跳过计算和不必要的重新渲染，请使用这些 Hook：
```

2023-05-18 15:06 UTC, loveloki commented on src/content/reference/react/index.md
> +* [`useMemo`](/reference/react/useMemo) 让你缓存一个非常高的计算结果。
```suggestion
* [`useMemo`](/reference/react/useMemo) 让你缓存一个代价非常高的计算结果。
```

2023-05-18 15:06 UTC, loveloki commented on src/content/reference/react/index.md
> +有时，你不能跳过重新渲染，因为屏幕确实需要更新。在这种情况下，你可以通过将必须同步的阻塞更新（比如向输入法输入）与不需要阻塞用户界面的非阻塞更新（比如更新图表）分开以提高性能。
```suggestion
有时，你不能跳过重新渲染，因为屏幕确实需要更新。在这种情况下，你可以通过将必须同步的阻塞更新（比如使用输入法输入内容）与不需要阻塞用户界面的非阻塞更新（比如更新图表）分开以提高性能。
```

2023-05-18 15:06 UTC, loveloki commented on src/content/reference/react/index.md
> +要确定渲染的优先级，可以从以下 Hook 选择其中之一：
```suggestion
要确定渲染的优先级，可以使用以下 Hook：
```

2023-05-18 15:06 UTC, loveloki commented on src/content/reference/react/index.md
> +* [`useDebugValue`](/reference/react/useDebugValue) 让你在 React 开发者工具中为自定义 Hook 添加一个 label。
```suggestion
* [`useDebugValue`](/reference/react/useDebugValue) 让你在 React 开发者工具中为自定义 Hook 添加一个标签。
```

2023-05-18 15:06 UTC, loveloki commented on src/content/reference/react/index.md
> +* [`useId`](/reference/react/useId) 让组件将一个独特的 ID 与自己联系起来。通常与可访问性 API 一起使用。
```suggestion
* [`useId`](/reference/react/useId) 让组件绑定一个唯一 ID。通常与可访问性 API 一起使用。
```

2023-05-18 15:06 UTC, loveloki commented on src/content/reference/react/index.md
> +## 自己的 Hook {/*your-own-hooks*/}
```suggestion
## 自定义 Hook {/*your-own-hooks*/}
```

2023-06-19 10:28 UTC, Yucohny commented on src/content/reference/react/index.md
> +要跳过计算和不必要的重新渲染，请使用这些 Hook：
```suggestion
你可以使用这些 Hook 跳过计算和不必要的重新渲染：
```

2023-06-19 10:28 UTC, Yucohny commented on src/content/reference/react/index.md
> +* [`useDebugValue`](/reference/react/useDebugValue) 让你在 React 开发者工具中为自定义 Hook 添加一个标签。
```suggestion
* [`useDebugValue`](/reference/react/useDebugValue) 允许你在 React 开发者工具中为自定义 Hook 添加一个标签。
```

2023-06-19 10:28 UTC, Yucohny commented on src/content/reference/react/index.md
> +* [`useId`](/reference/react/useId) 让组件绑定一个唯一 ID。通常与可访问性 API 一起使用。
```suggestion
* [`useId`](/reference/react/useId) 允许组件绑定一个唯一 ID。通常与可访问性 API 一起使用。
```

2023-06-19 10:28 UTC, Yucohny commented on src/content/reference/react/index.md
> +* [`useSyncExternalStore`](/reference/react/useSyncExternalStore) 让一个组件订阅一个外部 store。
```suggestion
* [`useSyncExternalStore`](/reference/react/useSyncExternalStore) 允许一个组件订阅一个外部 store。
```

2023-06-21 12:26 UTC, merged