docs(cn): translate content/reference/react/useLayoutEffect.md into C…
reactjs/zh-hans.react.dev pull request #1106
Opened 2023-03-28 13:43 UTC by BetterZxx

翻译reference/react/useLayoutEffect.md
@QC-L @awxiaoxian2020 @daochouwangu 
感谢review！

2023-03-28 14:01 UTC, awxiaoxian2020 submitted a review, later dismissed
建议将标点符号放外面。

2023-03-29 07:55 UTC, fwqaaq requested changes

2023-03-29 07:55 UTC, fwqaaq commented on src/content/reference/react/useLayoutEffect.md
> +[请看下面的更多例子](#usage)。
```suggestion
[请看下面的更多例子](#用法)。
```

这里应该是中文对应的标题

2023-03-29 07:55 UTC, fwqaaq commented on src/content/reference/react/useLayoutEffect.md
> +* `setup`：处理副作用的函数。setup 函数选择性返回一个 *cleanup（清理）* 函数。在将组件首次添加到 DOM 之前，React 将运行 setup 函数。在每次依赖项变更重新渲染后，React 将首先使用旧值运行 cleanup 函数（如果你提供了该函数），然后使用新值运行 setup 函数。在组件从 DOM 中移除之前，React 将最后一次运行 cleanup 函数。
```suggestion
* `setup`：处理副作用的函数。setup 函数选择性返回一个*清理*（cleanup）函数。在将组件首次添加到 DOM 之前，React 将运行 setup 函数。在每次依赖项变更重新渲染后，React 将首先使用旧值运行 cleanup 函数（如果你提供了该函数），然后使用新值运行 setup 函数。在组件从 DOM 中移除之前，React 将最后一次运行 cleanup 函数。
```

2023-03-29 08:00 UTC, awxiaoxian2020 commented on src/content/reference/react/useLayoutEffect.md
> +[请看下面的更多例子](#usage)。
这里应该保留英文，因为每个标题的后面带有锚点，渲染时可以转换为对应的 id。

2023-03-29 08:02 UTC, awxiaoxian2020 commented on src/content/reference/react/useLayoutEffect.md
> +* `useLayoutEffect` 是一个 Hook，因此只能在 **组件的顶层** 或自己的 Hook 中调用它。不能在循环或者条件内部调用它。如果你需要的话，抽离出一个组件并将副作用处理移动到那里。
这里从字体层面考虑，可以加空格~我正在译文规范要怎么样表述。因为不加空格有时可能相关效果不明显，阅读体验不佳。

2023-03-29 08:07 UTC, fwqaaq commented on src/content/reference/react/useLayoutEffect.md
> +* `useLayoutEffect` 是一个 Hook，因此只能在 **组件的顶层** 或自己的 Hook 中调用它。不能在循环或者条件内部调用它。如果你需要的话，抽离出一个组件并将副作用处理移动到那里。
![image](https://user-images.githubusercontent.com/82551626/228468298-9cf542dc-f3f8-4a5c-a1a0-469b3012331a.png)

我看了它的粗体以及斜体渲染，幅度还是挺大的

2023-03-29 15:44 UTC, BetterZxx commented on src/content/reference/react/useLayoutEffect.md
> +* **可选** `dependencies`：`setup` 代码中引用的所有动态值的列表。动态值包括 props，state 以及所有直接在组件内部声明的变量和函数。如果你的代码检查工具 [配置了 React](/learn/editor-setup#linting)，那么它将验证每个动态值都被正确地指定为一个依赖项。依赖项列表必须具有固定数量的项，并且必须像 `[dep1, dep2, d
已修改

2023-04-10 03:17 UTC, Yucohny commented on src/content/reference/react/useLayoutEffect.md
> +大多数组件不需要知道它们在屏幕上的位置和大小来决定渲染什么。他们只返回一些 JSX，然后浏览器计算他们的 *布局* （位置和大小）并重新绘制屏幕。
```suggestion
大多数组件不需要知道它们在屏幕上的位置和大小来决定渲染什么。他们只返回一些 JSX，然后浏览器计算他们的 **布局**（位置和大小）并重新绘制屏幕。
```

2023-04-10 03:17 UTC, Yucohny commented on src/content/reference/react/useLayoutEffect.md
> +下面是同样的例子，但是使用 [`useEffect`](/reference/react/useEffect) 代替 `useLayoutEffect`。如果你使用的是速度较慢的设备，你可能会注意到有时 tooltip“闪烁”，并且在更正的位置之前你可以简单地看到它的初始位置。
```suggestion
下面是同样的例子，但是使用 [`useEffect`](/reference/react/useEffect) 代替 `useLayoutEffect`。如果你使用的是速度较慢的设备，你可能会注意到有时 tooltip 会“闪烁”，并且在更正的位置之前你可以简单地看到它的初始位置。
```

2023-04-10 03:17 UTC, Yucohny commented on src/content/reference/react/useLayoutEffect.md
> +- 用 [`useEffect`](/reference/react/useEffect) 替换 `useLayoutEffect`。 React 可以在不阻塞绘制的情况下显示初始的渲染结果（因为初始的 HTML 将在 Effect 运行之前显示出来）。
```suggestion
- 用 [`useEffect`](/reference/react/useEffect) 替换 `useLayoutEffect`。React 可以在不阻塞绘制的情况下显示初始的渲染结果（因为初始的 HTML 将在 Effect 运行之前显示出来）。
```

2023-04-10 03:17 UTC, Yucohny commented on src/content/reference/react/useLayoutEffect.md
> +- 或者，[将组件标记为仅客户端](/reference/react/Suspense#providing-a-fallback-for-server-errors-and-server-only-content)。 这告诉 React 在服务端渲染时用一个 loading 降级（例如，一个 spinner 或者 glimmer）替换其内容到上方最近的 [`<Suspense>`](/refer
```suggestion
- 或者，[将组件标记为仅客户端](/reference/react/Suspense#providing-a-fallback-for-server-errors-and-server-only-content)。这告诉 React 在服务端渲染时用一个 loading 降级（例如，一个 spinner 或者 glimmer）替换其内容到上方最近的 [`<Suspense>`](/reference/react/Suspense) 边界。
```

2023-04-10 03:17 UTC, Yucohny commented on src/content/reference/react/useLayoutEffect.md
> +- 或者，只有在水合之后，使用 `useLayoutEffect` 渲染组件。保留一个初始化为 false 的 isMounted 布尔状态，并在 useEffect 调用中将其设置为 true。然后你的渲染逻辑就会像 `return isMounted ? <RealContent /> : <FallbackContent />` 这样。在服务端和水合过程中，用户将看到 `FallbackC
```suggestion
- 或者，只有在水合之后，使用 `useLayoutEffect` 渲染组件。保留一个初始化为 `false` 的 `isMounted` 布尔状态，并在 `useEffect` 调用中将其设置为 `true`。然后你的渲染逻辑就会像 `return isMounted ? <RealContent /> : <FallbackContent />` 这样。在服务端和水合过程中，用户将看到 `FallbackContent`，它不应该调用 `useLayoutEffect`。然后 React 将用 `RealContent` 替换它，`RealContent` 仅在客户端上运行并且可以包含 `useLayoutEffect` 调用。
```

2023-04-10 03:17 UTC, Yucohny commented on src/content/reference/react/useLayoutEffect.md
> +- 如果你将组件与外部数据存储同步，并且依赖 useLayouteffect 的原因不同于测量布局，可以考虑使用 [支持服务端渲染](/reference/react/useSyncExternalStore#adding-support-for-server-rendering) 的 [`useSyncExternalStore`](/reference/react/useSyncExtern
```suggestion
- 如果你将组件与外部数据存储同步，并且依赖 `useLayouteffect` 的原因不同于测量布局，可以考虑使用 [支持服务端渲染](/reference/react/useSyncExternalStore#adding-support-for-server-rendering) 的 [`useSyncExternalStore`](/reference/react/useSyncExternalStore)。
```

2023-04-10 03:19 UTC, Yucohny approved these changes

2023-05-19 14:54 UTC, awxiaoxian2020 commented
please fix the conflict

2023-06-19 15:20 UTC, loveloki submitted a review, later dismissed

2023-06-19 15:20 UTC, loveloki commented on src/content/reference/react/useLayoutEffect.md
> +* `setup`：处理副作用的函数。setup 函数选择性返回一个*清理*（cleanup）函数。在将组件首次添加到 DOM 之前，React 将运行 setup 函数。在每次依赖项变更重新渲染后，React 将首先使用旧值运行 cleanup 函数（如果你提供了该函数），然后使用新值运行 setup 函数。在组件从 DOM 中移除之前，React 将最后一次运行 cleanup 函数。
```suggestion
* `setup`：处理副作用的函数。setup 函数选择性返回一个*清理*（cleanup）函数。在将组件首次添加到 DOM 之前，React 将运行 setup 函数。在每次因为依赖项变更而重新渲染后，React 将首先使用旧值运行 cleanup 函数（如果你提供了该函数），然后使用新值运行 setup 函数。在组件从 DOM 中移除之前，React 将最后一次运行 cleanup 函数。
```

2023-06-19 15:20 UTC, loveloki commented on src/content/reference/react/useLayoutEffect.md
> +* 当 StrictMode 启动时，React 将在真正的 setup 函数首次运行前，**运行一个额外的开发专有的 setup + cleanup 周期**。这是一个压力测试，确保 cleanup 逻辑“映照”到 setup 逻辑，并停止或撤消 setup 函数正在做的任何事情。如果这导致一个问题，[请实现清理函数](/learn/synchronizing-with-effects#how
```suggestion
* 当 StrictMode 启用时，React 将在真正的 setup 函数首次运行前，**运行一个额外的开发专有的 setup + cleanup 周期**。这是一个压力测试，确保 cleanup 逻辑“映照”到 setup 逻辑，并停止或撤消 setup 函数正在做的任何事情。如果这导致一个问题，[请实现清理函数](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)。
```

2023-06-19 15:20 UTC, loveloki commented on src/content/reference/react/useLayoutEffect.md
> +大多数组件不需要知道它们在屏幕上的位置和大小来决定渲染什么。他们只返回一些 JSX，然后浏览器计算他们的 **布局**（位置和大小）并重新绘制屏幕。
```suggestion
大多数组件不需要依靠它们在屏幕上的位置和大小来决定渲染什么。他们只返回一些 JSX，然后浏览器计算他们的 **布局**（位置和大小）并重新绘制屏幕。
```

2023-06-19 15:20 UTC, loveloki commented on src/content/reference/react/useLayoutEffect.md
> +3. `useLayoutEffect` [测量](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) 了 tooltip 内容的高度，并触发立即的重新渲染。
```suggestion
3. `useLayoutEffect` [测量](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) 了 tooltip 内容的高度，并立即触发重新渲染。
```

2023-06-19 15:20 UTC, loveloki commented on src/content/reference/react/useLayoutEffect.md
> +下面是同样的例子，但是使用 [`useEffect`](/reference/react/useEffect) 代替 `useLayoutEffect`。如果你使用的是速度较慢的设备，你可能会注意到有时 tooltip 会“闪烁”，并且在更正的位置之前你可以简单地看到它的初始位置。
```suggestion
下面是同样的例子，但是使用 [`useEffect`](/reference/react/useEffect) 代替 `useLayoutEffect`。如果你使用的是速度较慢的设备，你可能注意到有时 tooltip 会“闪烁”，并且会在更正位置之前短暂地看到初始位置。
```

2023-06-19 16:26 UTC, Yucohny submitted a review, later dismissed

2023-06-20 00:32 UTC, loveloki submitted a review, later dismissed

2023-06-20 00:45 UTC, Yucohny commented
请自行解决合并冲突。

2023-06-20 01:34 UTC, loveloki approved these changes

2023-06-20 02:51 UTC, Yucohny approved these changes

2023-06-20 02:52 UTC, merged