docs(cn): translate [ /content/reference/react/useId.md ] into Chinese
reactjs/zh-hans.react.dev pull request #1108
Opened 2023-03-29 05:20 UTC by Java-S12138

docs(cn): translate [ src/content/reference/react/useId.md ] into Chinese

2023-03-29 05:26 UTC, awxiaoxian2020 commented
请于 #602 补上任务认领，以免撞车~

2023-03-29 05:36 UTC, awxiaoxian2020 requested changes
文章有多处格式问题，请参照译文规范进行修改。也存在机翻化严重的问题，请加以润色~

2023-03-29 05:36 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +在React内部，`useId` 是从调用组件的 “ 父路径 ” 生成的。这就是为什么，如果客户端和服务器树相同，则 “ 父路径 ” 将匹配，而不管渲染顺序如何的原因。
```suggestion
在React内部，`useId` 是从调用组件的“父路径”生成的。这就是为什么，如果客户端和服务器树相同，则 “父路径” 将匹配，而不管渲染顺序如何的原因。
```

2023-03-29 07:42 UTC, fwqaaq requested changes
Some Suggestions

2023-03-29 07:42 UTC, fwqaaq commented on src/content/reference/react/useId.md
> +这使你避免为每个需要唯一 ID 的元素调用`useId`。
```suggestion
这使你避免为每个需要唯一 ID 的元素调用 `useId`。
```

2023-03-29 07:42 UTC, fwqaaq commented on src/content/reference/react/useId.md
> +在React内部，`useId` 是从调用组件的 “ 父路径 ” 生成的。这就是为什么，如果客户端和服务器树相同，则 “ 父路径 ” 将匹配，而不管渲染顺序如何的原因。
```suggestion
在 React 内部，`useId` 是从调用组件的 “ 父路径 ” 生成的。这就是为什么，如果客户端和服务器树相同，则 “ 父路径 ” 将匹配，而不管渲染顺序如何的原因。
```

2023-03-29 07:42 UTC, fwqaaq commented on src/content/reference/react/useId.md
> +        密码应该包含至少18个字符
```suggestion
        密码应该包含至少 18 个字符
```

2023-03-29 07:42 UTC, fwqaaq commented on src/content/reference/react/useId.md
> +[请看这个视频，](https://www.youtube.com/watch?v=0dNzNcuEuOo) 了解辅助技术所提供的用户体验的差异。
```suggestion
[请看这个视频](https://www.youtube.com/watch?v=0dNzNcuEuOo)，以了解辅助技术所提供的用户体验的差异。
```

2023-03-29 07:42 UTC, fwqaaq commented on src/content/reference/react/useId.md
> +[在服务器渲染中，](/reference/react-dom/server) **`useId` 需要在服务器和客户端上有相同的组件树。** 如果你在服务器和客户端上渲染的树不完全匹配，生成的 ID 将不匹配。
```suggestion
[使用服务器渲染时](/reference/react-dom/server)，**`useId` 需要在服务器和客户端上有相同的组件树**。如果你在服务器和客户端上渲染的树不完全匹配，生成的 ID 将不匹配。
```

2023-03-30 09:19 UTC, Java-S12138 commented on src/content/reference/react/useId.md
> +[在服务器渲染中，](/reference/react-dom/server) **`useId` 需要在服务器和客户端上有相同的组件树。** 如果你在服务器和客户端上渲染的树不完全匹配，生成的 ID 将不匹配。
Thank you very much.

2023-03-30 12:34 UTC, awxiaoxian2020 requested changes

2023-03-30 12:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +[请看下方更多示例。](#usage)
```suggestion
[请看下方更多示例](#usage)。
```

2023-03-30 12:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +* `useId` 是一个 Hook，因此你只能**在组件的顶层**或自己的 Hooks 中调用它。 你不能在内部循环或条件判断中调用它。如果需要，可以提取一个新组件并将 State 移到该组件中。
```suggestion
* `useId` 是一个 Hook，因此你只能 **在组件的顶层** 或自己的 Hooks 中调用它。 你不能在内部循环或条件判断中调用它。如果需要，可以提取一个新组件并将 State 移到该组件中。
```

2023-03-30 12:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +在组件的顶层调用 `useId` 来生成唯一ID：
```suggestion
在组件的顶层调用 `useId` 来生成唯一 ID：
```

2023-03-30 12:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +[HTML 可访问性属性](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) 例如 [`aria-describedby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) 允许你
```suggestion
[HTML 无障碍属性](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) 例如 [`aria-describedby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) 允许你指定两个标签之间的关系。例如，你可以指定一个元素（比如输入框）由另一个元素（比如段落）描述。
```

2023-03-30 12:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +然而，在 React 中直接编写 ID 并不是一个好的习惯。 一个组件可能会在页面上渲染多次，但是 ID 必须是唯一的！不要使用自己编写的 ID，而是使用 `useId` 生成唯一的 ID。
```suggestion
然而，在 React 中直接编写 ID 并不是一个好的习惯。一个组件可能会在页面上渲染多次，但是 ID 必须是唯一的！不要使用自己编写的 ID，而是使用 `useId` 生成唯一的 ID。
```

2023-03-30 12:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +[使用服务器渲染时](/reference/react-dom/server)， **`useId` 需要在服务器和客户端上有相同的组件树** 。如果你在服务器和客户端上渲染的树不完全匹配，生成的 ID 将不匹配。
```suggestion
[使用服务器渲染时](/reference/react-dom/server)， **`useId` 需要在服务器和客户端上有相同的组件树**。如果你在服务器和客户端上渲染的树不完全匹配，生成的 ID 将不匹配。
```

2023-03-30 12:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +`useId` 的主要好处是 React 确保它能够与[服务器渲染](/reference/react-dom/server)一起工作。 在服务器渲染期间，你的组件生成输出 HTML。随后，在客户端，[Hydration](/reference/react-dom/client/hydrateRoot) 会将你的事件处理程序附加到生成的 HTML 上。由于 Hydration, 客户端必须匹配服
```suggestion
`useId` 的主要好处是 React 确保它能够与[服务器渲染](/reference/react-dom/server)一起工作。 在服务器渲染期间，你的组件生成输出 HTML。随后，在客户端，[Hydration](/reference/react-dom/client/hydrateRoot) 会将你的事件处理程序附加到生成的 HTML 上。由于 hydration, 客户端必须匹配服务器输出的 HTML。
```

2023-03-30 12:38 UTC, awxiaoxian2020 commented
请仔细阅读 wiki 中的规范，git pull 以后再次检查译文是否规范，并作相应修改~

2023-04-09 06:51 UTC, Yucohny commented on src/content/reference/react/useId.md
> +  **不要使用 `useId` 来生成列表中的 key**。[key 应该由你的数据生成](/learn/rendering-lists#where-to-get-your-key)。
```suggestion
**不要使用 `useId` 来生成列表中的 key**。[key 应该由你的数据生成](/learn/rendering-lists#where-to-get-your-key)。
```

2023-04-09 06:51 UTC, Yucohny commented on src/content/reference/react/useId.md
> +[HTML 无障碍属性](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA) 例如 [`aria-describedby`](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) 允许你指
```suggestion
如 [`aria-describedby`](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) 这样的 [HTML 无障碍属性](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA) 允许你指定两个标签之间的关系。例如，你可以指定一个元素（比如输入框）由另一个元素（比如段落）描述。
```

2023-04-09 06:51 UTC, Yucohny commented on src/content/reference/react/useId.md
> +你可能想知道为什么使用 `useId` 比增加全局变量（如 nextId ++）更好。
```suggestion
你可能想知道为什么使用 `useId` 比增加全局变量（如 `nextId++`）更好。
```

2023-04-23 14:27 UTC, Yucohny commented on src/content/reference/react/useId.md
> +**让我们通过一个例子，看看这个什么时候有用。**
```suggestion
**让我们通过一个例子，看看这个什么时候有用**。
```

2023-04-23 14:27 UTC, Yucohny commented on src/content/reference/react/useId.md
> +在 React 内部，调用组件的“父路径”生成 `useId`。这就是为什么，如果客户端和服务器的树相同，不管渲染顺序如何，“父路径”将匹配。
```suggestion
在 React 内部，调用组件的“父路径”生成 `useId`。这就是为什么如果客户端和服务器的树相同，不管渲染顺序如何，“父路径”始终都匹配。
```

2023-04-23 14:28 UTC, Yucohny approved these changes

2023-04-24 02:33 UTC, awxiaoxian2020 approved these changes
LGTM! Welcome aboard!

2023-04-24 02:34 UTC, merged