docs(cn): translate content/learn/start-a-new-react-project.md into Chinese
reactjs/zh-hans.react.dev pull request #1111
Opened 2023-03-31 07:24 UTC by ZZZCNY

translate start-a-new-react-project.md

2023-03-31 07:49 UTC, awxiaoxian2020 requested changes

2023-03-31 07:49 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**本页面上的 React 框架默认解决了这些问题，不需要你做额外的工作。** 它们让你在开始时非常精简，然后根据你的需求扩展你的应用程序。每个 React 框架都有一个社区，所以寻找问题的答案和升级工具都比较容易。框架还为你的代码提供了结构，帮助你和其他人在不同的项目之间保留背景和技能。相反，如果是自定义设置，则更容易卡在不支持的依赖版本上，而且你最终会创建自己的框架——尽管是一个没有社区或升
```suggestion
**本页面上的 React 框架默认解决了这些问题，不需要你做额外的工作**。它们让你在开始时非常精简，然后根据你的需求扩展你的应用程序。每个 React 框架都有一个社区，所以寻找问题的答案和升级工具都比较容易。框架还为你的代码提供了结构，帮助你和其他人在不同的项目之间保留背景和技能。相反，如果是自定义设置，则更容易卡在不支持的依赖版本上，而且你最终会创建自己的框架——尽管是一个没有社区或升级路径的框架（如果它像我们过去做的那些框架一样，则设计得更加草率）。
```

2023-04-02 09:34 UTC, awxiaoxian2020 requested changes

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**你需要安装 [Node.js](https://nodejs.org/zh-cn) 用于本地开发**。你也可以选择在生产中使用 Node.js，但你不一定要这样。许多 React 框架支持导出到静态 HTML/CSS/JS 文件夹。
```suggestion
**你需要安装 [Node.js](https://nodejs.org/zh-cn) 用于本地开发**。你也可以选择在生产中使用 Node.js，但你不一定要这样。许多 React 框架支持导出 HTML/CSS/JS 等静态文件。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js](https://nextjs.org/) 是一个全栈式的 React 框架**。它用途广泛，可以让你创建任何规模的 React 应用——从大部分静态博客到复杂的动态应用。要创建一个新的 Next.js 项目，请在你的终端运行：
```suggestion
**[Next.js](https://nextjs.org/) 是一个全栈式的 React 框架**。它用途广泛，可以让你创建任何规模的 React 应用——可以是静态博客，也可以是复杂的动态应用。要创建一个新的 Next.js 项目，请在你的终端运行：
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Next.js 由 [Vercel](https://vercel.com/) 维护。你可以 [将 Next.js 应用程序](https://nextjs.org/docs/deployment) 部署到任何 Node.js 或无服务器主机上，或部署到你自己的服务器上。[完全静态的 Next.js 应用程序](https://nextjs.org/docs/advanced-features/
```suggestion
Next.js 由 [Vercel](https://vercel.com/) 维护。你可以 [将 Next.js 应用程序](https://nextjs.org/docs/deployment) 部署到 Node.js 或 serverless 上，也可以部署到你自己的服务器上。[完全静态的 Next.js 应用程序](https://nextjs.org/docs/advanced-features/static-html-export) 支持静态部署。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**[Remix](https://remix.run/) 是一个具有嵌套路由的全栈式 React 框架**。它让你把你的应用程序分成嵌套部分，可以并行加载数据并根据用户操作进行刷新。要创建一个新的 Remix 项目，请运行：
这里翻译成“嵌套”吗，我不太清楚

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Remix 是由 [Shopify](https://www.shopify.com/) 维护的。当您创建一个 Remix 项目时，您需要 [选择您的部署目标](https://remix.run/docs/en/main/guides/deployment)。您可以通过使用或编写 [适配器](https://remix.run/docs/en/main/other-api/adapter) 将
所有的您请替换为你

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +你当然可以在没有框架的情况下使用 React ——这就是你如何 [将 React 用于你页面的一部分](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page)。**但是，如果你要用 React 构建一个新的应用程序或网站，我们建议使用一个框架**。
```suggestion
你当然可以在没有框架的情况下使用 React——这就是 [将 React 用于你页面的一部分](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page)**。但是，如果你要用 React 构建一个新的应用程序或网站，我们建议使用一个框架**。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +这是为什么。
```suggestion
这里是一些原因。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +在我们探索如何继续改进 React 的过程中，我们意识到将 React 与框架（特别是与路由、捆绑和服务器技术）更紧密地结合起来是我们帮助 React 用户构建更好的应用程序的最大机会。Next.js 团队已经同意与我们合作，研究、开发、集成和测试与框架无关的 React 前沿功能，如 [React 服务器组件](/blog/2023/03/22/react-labs-what-we-have-
```suggestion
在我们探索如何继续改进 React 的过程中，我们意识到将 React 与框架（特别是与路由、捆绑和服务器技术）更紧密地结合起来是我们帮助 React 用户构建更好的应用程序的最大机会。Next.js 团队已经同意与我们合作，研究、开发、集成和测试与框架无关的 React 前沿功能，如 [React 服务端组件](/blog/2023/03/22/react-labs-what-we-have-been-working-march-2023#react-server-components)。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js 的 App Router](https://beta.nextjs.org/docs/getting-started) 是对 Next.js APIs 的重新设计，旨在实现 React 团队的全栈架构愿景**。它让你在异步组件中获取数据，这些组件在服务器甚至构建过程中运行。
```suggestion
**[Next.js 的 App Router](https://beta.nextjs.org/docs/getting-started) 是对 Next.js API 的重新设计，旨在实现 React 团队的全栈架构愿景**。它让你在异步组件中获取数据，这些组件甚至能在服务端构建过程中运行。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Next.js 由 [Vercel](https://vercel.com/) 维护。你可以将 [Next.js 应用](https://nextjs.org/docs/deployment) 部署到任何 Node.js 或无服务器主机上，或部署到你自己的服务器上。Next.js 还支持 [静态导出](https://beta.nextjs.org/docs/configuring/static
```suggestion
ext.js 由 [Vercel](https://vercel.com/) 维护。你可以将 [Next.js 应用](https://nextjs.org/docs/deployment) 部署到 Node.js 或 serverless 主机上，或部署到你自己的服务器上。Next.js 还支持 [静态导出](https://beta.nextjs.org/docs/configuring/static-export)，不需要服务器。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Next.js 的 App Router 目前处于**测试阶段，还不建议用于生产**（截止到 2023 年 3 月）。要在现有的 Next.js 项目中试验它，[请遵循此增量迁移指南](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app)。
```suggestion
Next.js 的 App Router 目前处于 **测试阶段，还不建议用于生产**（截止到 2023 年 3 月）。要在现有的 Next.js 项目中试验它，[请遵循此增量迁移指南](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app)。
```

2023-04-02 09:34 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Next.js 的 App Router bundler 完全实现了官方的 [React 服务器组件规范](https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md)。这让你可以在一棵 React 树上混合构建时间、纯服务器和互动组件。
服务器改成服务端比较好。

2023-04-02 11:01 UTC, fwqaaq commented on src/content/learn/start-a-new-react-project.md
> +**[Remix](https://remix.run/) 是一个具有嵌套路由的全栈式 React 框架**。它让你把你的应用程序分成嵌套部分，可以并行加载数据并根据用户操作进行刷新。要创建一个新的 Remix 项目，请运行：
```suggestion
**[Remix](https://remix.run/) 是一个具有嵌套路由的全栈式 React 框架**。它让你把你的应用程序分成嵌套部分，该嵌套部分可以并行加载数据并响应用户操作进行刷新。要创建一个新的 Remix 项目，请运行：
```
嵌套路由，可以参考 vue router：https://router.vuejs.org/zh/guide/essentials/nested-routes.html#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1

2023-04-02 11:22 UTC, fwqaaq requested changes
Suggestions

2023-04-02 11:22 UTC, fwqaaq commented on src/content/learn/start-a-new-react-project.md
> +**这些问题不是 React 特有的。这就是为什么 Svelte 有 SvelteKit，Vue 有 Nuxt，等等**。要自己解决这些问题，你需要将你的 bundler 与你的路由器和你的数据获取库整合起来。初步的设置工作并不难，但要使一个应用程序在随着时间的推移而快速加载，还涉及很多微妙的问题。你想把应用代码的数量降到最低，但要在单一的客户端-服务器往返中进行，与页面所需的任何数据并行。你可
```suggestion
**这些问题不是 React 特有的。这就是为什么 Svelte 有 SvelteKit、Vue 有 Nuxt等等**。要自己解决这些问题，你需要将你的 bundler 与路由和数据获取库集成起来。使初步设置工作并不难，但要使一个应用程序在随着时间的推移而快速加载，还涉及很多微妙的问题。你想把应用代码的数量降到最低，但要在单一的客户端-服务器往返中进行，与页面所需的任何数据并行。甚至你可能希望在你的 JavaScript 代码运行之前，页面就已经可以交互，以支持渐进式增强。你可能想为你的营销页面生成一个完全静态的 HTML 文件夹，可以在任何地方托管，并且在禁用 JavaScript 的情况下仍然可以工作。要构建这些功能需要真正的工作。
```

2023-04-02 11:22 UTC, fwqaaq commented on src/content/learn/start-a-new-react-project.md
> +**本页面上的 React 框架默认解决了这些问题，不需要你做额外的工作**。它们让你在开始时非常精简，然后根据你的需求扩展你的应用程序。每个 React 框架都有一个社区，所以寻找问题的答案和升级工具都比较容易。框架还为你的代码提供了结构，帮助你和其他人在不同的项目之间保留背景和技能。相反，如果是自定义设置，则更容易卡在不支持的依赖版本上，而且你最终会创建自己的框架——尽管是一个没有社区或升级
```suggestion
**本页面上的 React 框架默认解决了这些问题，不需要你做额外的工作**。它们让你可以从非常精简的应用程序开始，然后根据你的需求扩展应用程序。每个 React 框架都有一个社区，所以寻找问题的答案和升级工具都比较容易。框架还为你的代码提供了结构，帮助你和其他人在不同的项目之间保留背景和技能。相反，如果是自定义设置，则更容易卡在不支持的依赖版本上，而且你最终会创建自己的框架，尽管没有社区或升级路径（如果你的自定义设置和我们过去创建的一样，那么它的设计可能会更加随意）。
```

2023-04-03 04:14 UTC, awxiaoxian2020 commented
code review 可以在 File changes 里面批量添加~

2023-04-09 00:17 UTC, awxiaoxian2020 requested changes

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**你需要安装 [Node.js](https://nodejs.org/zh-cn) 用于本地开发**。你也可以选择在生产中使用 Node.js，但你不一定要这样。许多 React 框架支持导出 HTML/CSS/JS 等静态文件。
```suggestion
**你需要安装 [Node.js](https://nodejs.org/zh-cn) 用于本地开发**。你也可以选择在生产环境中使用 Node.js，但你不一定要这样。许多 React 框架支持导出 HTML/CSS/JS 等静态文件。
```

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Next.js 由 [Vercel](https://vercel.com/) 维护。你可以 [将 Next.js 应用](https://nextjs.org/docs/deployment) 部署到 Node.js 或 serverless 上，也可以部署到你自己的服务器上。[完全静态的 Next.js 应用](https://nextjs.org/docs/advanced-feature
```suggestion
Next.js 由 [Vercel](https://vercel.com/) 维护。你可以 [将 Next.js 应用](https://nextjs.org/docs/deployment) 部署到 Node.js 或 serverless 上，也可以部署到你自己的服务器上。[完全静态的 Next.js 应用](https://nextjs.org/docs/advanced-features/static-html-export) 可以部署在任何支持静态服务的地方。
```

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**[Gatsby](https://www.gatsbyjs.com/) 是一个用于快速的支持 CMS 的网站的 React 框架**。其丰富的插件生态系统和 GraphQL 数据层简化了将内容、API 和服务整合到一个网站的过程。要创建一个新的 Gatsby 项目，请运行：
```suggestion
**[Gatsby](https://www.gatsbyjs.com/) 是一个快速的支持 CMS 的网站的 React 框架**。其丰富的插件生态系统和 GraphQL 数据层简化了将内容、API 和服务整合到一个网站的过程。要创建一个新的 Gatsby 项目，请运行：
```

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Gatsby 是由 [Netlify](https://www.netlify.com/) 维护的。你可以 [部署一个完全静态的 Gatsby 网站](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) 到任何静态主机。如果你选择使用服务器上的功能，请确保你的主机供应商支持 Gatsby 的功能。
```suggestion
Gatsby 是由 [Netlify](https://www.netlify.com/) 维护的。你可以 [部署一个完全静态的 Gatsby 网站](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) 到任何一个支持静态服务的地方。如果你选择使用服务器上的功能，请确保你的主机供应商支持 Gatsby 的功能。
```

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +### Expo（用于本地应用） {/*expo*/}
```suggestion
### Expo（用于原生应用） {/*expo*/}
```

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**[Expo](https://expo.dev/) 是一个 React 框架，可以让你创建具有真正本地 UI 的通用 Android、iOS 和 Web 应用**。它为 [React Native](https://reactnative.dev/) 提供了一个 SDK，使本地部分更容易使用。要创建一个新的 Expo 项目，请运行：
```suggestion
**[Expo](https://expo.dev/) 是一个 React 框架，可以让你创建具有真正原生 UI 的应用，可以是 Android、iOS 或 Web 应用**。它为 [React Native](https://reactnative.dev/) 提供了一个 SDK，使原生部分更容易使用。要创建一个新的 Expo 项目，请运行：
```

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Expo 是由 [Expo（公司）](https://expo.dev/about) 维护的。用 Expo 构建应用是免费的，而且你可以不受限制地将它们提交到谷歌和苹果的应用商店。此外，Expo 还提供选择性的付费云服务。
```suggestion
Expo 是由 [Expo 这家公司](https://expo.dev/about) 维护的。用 Expo 构建应用是免费的，而且你可以不受限制地将它们提交到谷歌和苹果的应用商店。此外，Expo 还提供选择性的付费云服务。
```

2023-04-09 00:17 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +你当然可以在没有框架的情况下使用 Reac——这就是 [将 React 用于你页面的一部分](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page)。**但是，如果你要用 React 构建一个新的应用或网站，我们建议使用一个框架**。
```suggestion
你当然可以在没有框架的情况下使用 React——这就是 [将 React 用于你页面的一部分](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page)。**但是，如果你要用 React 构建一个新的应用或网站，我们建议使用一个框架**。
```

2023-04-09 00:22 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +服务端组件和 Suspense 是 React 的功能，不是由 Next.js 提供的。然而，在框架层面上采用它们需要投入大量的实现工作。目前，Next.js App Router 是最完整的实现。React 团队正在与  开发人员合作，使这些功能在下一代框架中更容易实现。
```suggestion
服务端组件和 Suspense 是 React 的功能，不是由 Next.js 提供的。然而，在框架层面上采用它们需要投入大量的实现工作。目前，Next.js App Router 是最完整的实现。React 团队正在与 bundler 开发人员合作，使这些功能在下一代框架中更容易实现。
```

2023-04-09 00:33 UTC, awxiaoxian2020 requested changes

2023-04-09 00:33 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +**本页面上的 React 框架默认解决了这些问题，不需要你做额外的工作**。它们让你可以从非常精简的应用开始，然后根据你的需求扩展应用。每个 React 框架都有一个社区，所以寻找问题的答案和升级工具都比较容易。框架还为你的代码提供了结构，帮助你和其他人在不同的项目之间保留背景和技能。相反，如果是自定义设置，则更容易卡在不支持的依赖版本上，而且你最终会创建自己的框架，尽管没有社区或升级路径（如
我觉得这个地方的翻译需要润色一下。

2023-04-09 01:46 UTC, awxiaoxian2020 requested changes

2023-04-09 01:46 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +// 这个组件只在服务器上运行（或在构建期间）。
```suggestion
// 这个组件只在服务端运行（或在构建期间）。
```

2023-04-09 01:46 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +  // 1. 你在服务器上，所以你可以和你的数据层对话。不需要 API 端点。
```suggestion
  // 1. 你在服务端，所以你可以和你的数据层对话。不需要 API 端点。
```

2023-04-09 01:46 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Remix 是由 [Shopify](https://www.shopify.com/) 维护的。当你创建一个 Remix 项目时，你需要 [选择你的部署目标](https://remix.run/docs/en/main/guides/deployment)。你可以通过使用或编写 [适配器](https://remix.run/docs/en/main/other-api/adapter) 将
```suggestion
Remix 是由 [Shopify](https://www.shopify.com/) 维护的。当你创建一个 Remix 项目时，你需要 [选择你的部署目标](https://remix.run/docs/en/main/guides/deployment)。你可以通过使用或编写 [适配器](https://remix.run/docs/en/main/other-api/adapter) 将 Remix 应用部署到任何 Node.js 服务上或使用 serverless 进行托管。
```

2023-04-09 02:03 UTC, awxiaoxian2020 requested changes

2023-04-09 02:03 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Next.js 的 App Router bundler 完全实现了官方的 [React 服务端组件规范](https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md)。这让你可以在一棵 React 树上混合构建时间、纯服务端和交互组件。
```suggestion
Next.js 的 App Router bundler 完全实现了官方的 [React 服务端组件规范](https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md)。这让你可以在一棵 React 树上同时使用 *构建时*、*纯服务端*和 *交互组件*。
我觉得稍微做一点调整，可能会好一点。
```

2023-04-09 02:03 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +  // 2. 添加任何数量的渲染逻辑。它不会使你的 JavaScript bundle 变大。
```suggestion
  // 2. 添加任意数量的渲染逻辑。它不会使你的 JavaScript bundle 变大。
```

2023-04-09 05:00 UTC, awxiaoxian2020 requested changes

2023-04-09 05:11 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +Next.js 的 App Router 目前处于 **测试阶段，还不建议用于生产环境**（截止到 2023 年 3 月）。要在现有的 Next.js 项目中试验它，[请遵循此增量迁移指南](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app)。
```suggestion
Next.js 的 App Router 目前处于 **测试阶段，还不建议用于生产环境**（截止到 2023 年 3 月）。要在现有的 Next.js 项目进行实验，[参见逐步迁移指南](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app)。
```

2023-04-09 05:11 UTC, awxiaoxian2020 commented on src/content/learn/start-a-new-react-project.md
> +这些功能每天都在接近生产就绪，而且我们一直在与其他 bundler 和框架的开发者讨论整合它们。我们希望在一两年内，这个页面上列出的所有框架都能完全支持这些功能。（如果你是一个框架的作者，有兴趣与我们合作来试验这些功能，请让我们知道！）
```suggestion
这些功能每天都在接近生产就绪，而且我们一直在与其他 bundler 和框架的开发者讨论整合它们。我们希望在一两年内，这个页面上列出的所有框架都能完全支持这些功能。（如果你是一个框架的作者，有兴趣与我们合作来实验这些功能，请告诉我们！）
```

2023-04-09 05:14 UTC, awxiaoxian2020 submitted a review, later dismissed
LGTM! Thanks for your contribution!

2023-04-10 01:48 UTC, Yucohny commented on src/content/learn/start-a-new-react-project.md
> +如果你想完全用 React 构建一个新的应用或网站，我们建议选择社区中流行的，由 React 驱动的框架。这些框架提供大多数应用和网站最终需要的功能，包括路由、数据获取和生成 HTML。
```suggestion
如果你想完全用 React 构建一个新的应用或网站，我们建议选择社区中流行的、由 React 驱动的框架。这些框架提供大多数应用和网站最终需要的功能，包括路由、数据获取和生成 HTML。
```

2023-04-10 01:48 UTC, Yucohny commented on src/content/learn/start-a-new-react-project.md
> +Remix 是由 [Shopify](https://www.shopify.com/) 维护的。当你创建一个 Remix 项目时，你需要 [选择你的部署目标](https://remix.run/docs/en/main/guides/deployment)。你可以通过使用或编写 [适配器](https://remix.run/docs/en/main/other-api/adapter) 将
```suggestion
Remix 由 [Shopify](https://www.shopify.com/) 维护。当你创建一个 Remix 项目时，你需要 [选择你的部署目标](https://remix.run/docs/en/main/guides/deployment)。你可以通过使用或编写 [适配器](https://remix.run/docs/en/main/other-api/adapter) 将 Remix 应用部署到 Node.js 或 serverless 上进行托管。
```

2023-04-10 01:48 UTC, Yucohny commented on src/content/learn/start-a-new-react-project.md
> +Gatsby 是由 [Netlify](https://www.netlify.com/) 维护的。你可以 [部署一个完全静态的 Gatsby 网站](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) 到任何一个支持静态服务的地方。如果你选择使用服务器上的功能，请确保你的主机供应商支持 Gatsby 的功能。
```suggestion
Gatsby 由 [Netlify](https://www.netlify.com/) 维护。你可以 [部署一个完全静态的 Gatsby 网站](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) 到任何一个支持静态服务的地方。如果你选择使用服务器上的功能，请确保你的主机供应商支持 Gatsby 的功能。
```

2023-04-10 01:48 UTC, Yucohny commented on src/content/learn/start-a-new-react-project.md
> +**[Expo](https://expo.dev/) 是一个 React 框架，可以让你创建具有真正原生 UI 的应用，可以是 Android、iOS 或 Web 应用**。它为 [React Native](https://reactnative.dev/) 提供了一个 SDK，使原生部分更容易使用。要创建一个新的 Expo 项目，请运行：
```suggestion
**[Expo](https://expo.dev/) 是一个 React 框架，可以让你创建具有真正原生 UI 的应用，包括 Android、iOS，以及 Web 应用。它为 [React Native](https://reactnative.dev/) 提供了 SDK，使原生部分更容易使用。要创建一个新的 Expo 项目，请运行：
```

2023-04-10 02:50 UTC, Yucohny approved these changes

2023-04-10 02:52 UTC, awxiaoxian2020 approved these changes

2023-04-10 02:54 UTC, merged