docs(cn): translate learn/tutorial-tic-tac-toe into Chinese
reactjs/zh-hans.react.dev pull request #1116
Opened 2023-04-02 23:54 UTC by awxiaoxian2020

这个 PR 的内容比较多，所以还未对机翻部分作优化。格式上可能也存在问题。

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +如果现在单击一个方块，你应该会看到一条日志，上面写着 `"clicked!"` 在 CodeSandbox 中浏览器部分底部的控制台选项卡中。多次单击方块将再次记录 `"clicked!"`。具有相同消息的重复控制台日志不会在控制台中创建更多行。相反，你会在第一次 `"clicked!"` 旁边看到一个递增的计数器。
```suggestion
如果现在单击一个方块，你应该会看到一条日志，上面写着 `"clicked!"` 在 CodeSandbox 中 *Browser* 部分底部的 *Console* 选项卡中。多次单击方块将再次记录 `"clicked!"`。具有相同消息的重复控制台日志不会在控制台中创建更多行。相反，你会在第一次 `"clicked!"` 旁边看到一个递增的计数器。
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +在文件的顶部导入 `useState`。从 `Square` 组件中移除 value  prop。相反地，在调用 `useState` 的 `Square` 的开头添加一个新行。让它返回一个名为 value 的 state 变量：
```suggestion
在文件的顶部导入 `useState`。从 `Square` 组件中移除 `value` prop。相反地，在调用 `useState` 的 `Square` 的开头添加一个新行。让它返回一个名为 value 的 state 变量：
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +`value 存储值`，而 `setValue` 是可用于更改值的函数。传递给 `useState` 的 `null` 用作这个 state 变量的初始值，因此此处 `value` 的值开始时等于 null。
```suggestion
`value` 存储值，而 `setValue` 是可用于更改值的函数。传递给 `useState` 的 `null` 用作这个 state 变量的初始值，因此此处 `value` 的值开始时等于 null。
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +React 开发者工具可以检查 React 组件的 prop 和 state。可以在 CodeSandbox 的浏览器部分底部找到 React DevTools 选项卡：
```suggestion
React 开发者工具可以检查 React 组件的 prop 和 state。可以在 CodeSandbox 的 *Browser* 部分底部找到 React DevTools 选项卡：
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> + `Array(9).fill(null)` 创建一个包含九个元素的数组，并将它们中的每一个都设置为 `null`。围绕它的 `useState()` 调用声明了一个初始设置为该数组的 `squares` state 变量。数组中的每个条目对应于一个正方形的值。当你稍后填写棋盘时，`squares` 数组将如下所示：
```suggestion
`Array(9).fill(null)` 创建一个包含九个元素的数组，并将它们中的每一个都设置为 `null`。围绕它的 `useState()` 调用声明了一个初始设置为该数组的 `squares` state 变量。数组中的每个条目对应于一个正方形的值。当你稍后填写棋盘时，`squares` 数组将如下所示：
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +现在，每个 Square 都会收到一个 `value` 道具，对于空方块，该道具将是 `'X'` 、 `'O'` 或 `null` 。
```suggestion
现在，每个 Square 都会收到一个 `value` 道具，对于空方块，该道具将是 `'X'` 、`'O'` 或 `null`。
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +你将从 `Board` 组件向下传递一个函数到 `Square` 组件，你将让 `Square` 在单击方块时调用该函数。你将从单击 `Square` 组件时将调用的函数开始。你将调用该函数 `onSquareClick` ：
```suggestion
你将从 `Board` 组件向下传递一个函数到 `Square` 组件，你将让 `Square` 在单击方块时调用该函数。你将从单击 `Square` 组件时将调用的函数开始。你将调用该函数 `onSquareClick`：
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +现在，你将把 `onSquareClick` prop 连接到 `Board` 组件中的一个函数，你将命名为 `handleClick` 。要将 `onSquareClick` 连接到 `handleClick` ，你需要将一个函数传递给第一个 `Square` 组件的 `onSquareClick` prop ：
```suggestion
现在，你将把 `onSquareClick` prop 连接到 `Board` 组件中的一个函数，你将命名为 `handleClick` 。要将 `onSquareClick` 连接到 `handleClick` ，你需要将一个函数传递给第一个 `Square` 组件的 `onSquareClick` prop：
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> + `handleClick` 函数使用 JavaScript `slice()` Array 方法创建 `squares` 数组 ( `nextSquares` ) 的副本。然后，`handleClick` 更新 `nextSquares` 数组以将 `X` 添加到第一个（`[0]` 索引）方块。
```suggestion
 `handleClick` 函数使用 JavaScript `slice()` Array 方法创建 `squares` 数组（`nextSquares` ）的副本。然后，`handleClick` 更新 `nextSquares` 数组以将 `X` 添加到第一个（`[0]` 索引）方块。
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +现在你可以将 X 添加到棋盘上……但只能添加到左上角的方块。你的 `handleClick` 函数被硬编码为更新左上角方块 ( `0` ) 的索引。让我们更新 `handleClick` 以便能够更新任何正方形。将参数 `i` 添加到 `handleClick` 函数，该函数采用要更新的正方形索引：
```suggestion
现在你可以将 X 添加到棋盘上……但只能添加到左上角的方块。你的 `handleClick` 函数被硬编码为更新左上角方块（ `0`）的索引。让我们更新 `handleClick` 以便能够更新任何正方形。将参数 `i` 添加到 `handleClick` 函数，该函数采用要更新的正方形索引：
```

2023-04-03 00:12 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +接下来，你需要将 `i` 传递给 `handleClick` 。你可以尝试像这样在 JSX 中直接将 square 的 `onSquareClick` prop 设置为 `handleClick(0)` ，但这是行不通的：
```suggestion
接下来，你需要将 `i` 传递给 `handleClick`。你可以尝试像这样在 JSX 中直接将 square 的 `onSquareClick` prop 设置为 `handleClick(0)` ，但这是行不通的：
```

2023-04-04 11:20 UTC, fwqaaq requested changes
Suggestions

2023-04-04 11:20 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +### 将会构建什么？ {/*what-are-you-building*/}
```suggestion
- [添加“时间旅行”](#adding-time-travel) 可以让你更深入地了解 React 的独特优势。

### 将会构建什么？ {/*what-are-you-building*/}
```

2023-04-04 11:20 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +1. 安装 [Node.js](https://nodejs.org/en/)
```suggestion
1. 安装 [Node.js](https://nodejs.org/zh-cn/)
```

2023-04-04 11:20 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
>  ![CodeSandbox with starter code](../images/tutorial/react-starter-code-codesandbox.png)
这里应该可以翻译，在 MDN 中这里是出于无障碍考虑而编写的对图片的描述

2023-04-04 11:20 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
>  #### `index.js` {/*indexjs*/}
```suggestion
单击 CodeSandbox 中的 `styles.css` 文件。该文件定义了 React 应用的样式。前两个 CSS 选择器（`*` 和 `body`）定义应用大部分的样式，而 `.square` 选择器定义 `className` 属性设置为 `square` 的任何组件的样式。这将与 `App.js` 文件中的 `Square` 组件中的按钮相匹配。

#### `index.js` {/*indexjs*/}
```

2023-04-04 11:20 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +接下来，在 `Game` 组件中创建一个 `handlePlay` 函数，`Board` 组件将调用该函数来更新游戏。将 `xIsNext` 、 `currentSquares` 和 `handlePlay` 作为 props 传递给 `Board` 组件：
```suggestion
接下来，在 `Game` 组件中创建一个 `handlePlay` 函数，`Board` 组件将调用该函数来更新游戏。将 `xIsNext` 、`currentSquares` 和 `handlePlay` 作为 props 传递给 `Board` 组件：
```

2023-04-04 11:20 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +当你在传递给 `map` 的函数中遍历 `history` 数组时，`squares` 参数遍历 `history` 的每个元素，`move` 参数遍历每个数组索引：`0` 、@6 # , `2` , ….（在大多数情况下，你需要实际的数组元素，但要渲染移动列表，你只需要索引。）
```suggestion
当你在传递给 `map` 的函数中遍历 `history` 数组时，`squares` 参数遍历 `history` 的每个元素，`move` 参数遍历每个数组索引：`0` 、`1`、`2` , …。（在大多数情况下，你需要实际的数组元素，但要渲染移动列表，你只需要索引。）
```

2023-04-04 11:20 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +如果没有指定key，React会报错，默认使用数组索引作为key。在尝试重新排序列表项或插入/删除列表项时，使用数组索引作为键是有问题的。显式传递 `key={i}` 可以消除错误，但与数组索引有相同的问题，在大多数情况下不推荐使用。
```suggestion
如果没有指定 key，React 会报错，默认使用数组索引作为 key。在尝试重新排序列表项或插入/删除列表项时，使用数组索引作为键是有问题的。显式传递 `key={i}` 可以消除错误，但与数组索引有相同的问题，在大多数情况下不推荐使用。
```

2023-04-06 12:48 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +1. _Files_ 部分列出了一些文件：`App.js`、`index.js`、`styles.css` 和一个叫 `public` 的文件夹。
```suggestion
1. _Files_ 部分列出了一些文件：`App.js`、`index.js`、`styles.css` 和 `public` 文件夹。
```

2023-04-06 12:48 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +2. _code editor_ 里面你能够看到打开的代码。
```suggestion
2. _code editor_ 部分可以看到你所选中文件的源码。
```

2023-04-06 12:48 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +3. _browser_ 部分你将看到代码的实时效果。
```suggestion
3. _browser_ 部分可以预览代码的实时结果。
```

2023-04-06 12:48 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +现在，让我们仔细来看一看这些文件吧。
```suggestion
现在，让我们仔细研究一下这些文件吧。
```

2023-04-07 13:06 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +_browser_ 部分应该会像下面这样在方块里面显示一个 X：
```suggestion
_browser_ 部分应该会像下面这样在方块里面显示一个 X：

```

2023-04-08 14:14 UTC, fwqaaq requested changes

2023-04-08 14:14 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> + `handleClick` 函数使用 JavaScript Array 的 `slice()` 方法创建 `squares` 数组（`nextSquares`）的副本。然后，`handleClick` 更新 `nextSquares` 数组，将 `X` 添加到第一个（`[0]` 索引）方块。
```suggestion
 `handleClick` 函数使用 JavaScript 数组的 `slice()` 方法创建 `squares` 数组（`nextSquares`）的副本。然后，`handleClick` 更新 `nextSquares` 数组，将 `X` 添加到第一个（`[0]` 索引）方块。
```

这里的我觉得可以翻译，如果是代码快中的英文尽量不要翻译，如果翻译应该去除代码块🤔

2023-04-08 14:14 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +你已经有一组 `history` state 落子，所以现在你需要将其转换为一组 React 元素。在 JavaScript 中，要将一个数组转换为另一个数组，可以使用 [数组的 `map` 方法](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map)。
```suggestion
你已经有一组 `history` state 落子，所以现在你需要将其转换为一组 React 元素。在 JavaScript 中，要将一个数组转换为另一个数组，可以使用 [数组的 `map` 方法](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map)。
```
```suggestion
你已经有一组 state 为 `history` 的数组，所以现在你需要将其转换为一组 React 元素。在 JavaScript 中，要将一个数组转换为另一个数组，可以使用 [数组的 `map` 方法](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map)。
```

2023-04-08 14:14 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +在 `Game` 函数中，你可以将 key 添加为 `<li key={move}>`，如果你重新加载渲染的游戏，React 的“ key”错误应该会消失：
```suggestion
在 `Game` 函数中，你可以将 key 添加为 `<li key={move}>`，如果你重新加载渲染的游戏，React 的“key”错误应该会消失：
```

2023-04-08 14:18 UTC, fwqaaq commented
state -> 状态，完全可以翻译，全文出现大量的未翻译的 state，而且 [vue3](https://cn.vuejs.org/guide/scaling-up/state-management.html#what-is-state-management) 也翻译了，翻译为状态并无不妥

2023-04-08 14:21 UTC, fwqaaq commented
看了一下翻译指南，感觉可以更新一下

2023-04-08 14:22 UTC, awxiaoxian2020 commented
> state -> 状态，完全可以翻译，全文出现大量的未翻译的 state，而且 [vue3](https://cn.vuejs.org/guide/scaling-up/state-management.html#what-is-state-management) 也翻译了，翻译为状态并无不妥

Vue 3 和这里的情况不太一样。特指代码中的 state 时，不应翻译。我没有什么把握，要不你挑几处出来看看。

2023-04-08 14:26 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [概览](#overview) 介绍了 React 的 **基础知识**：组件、prop 和 state。
```suggestion
- [概览](#overview) 介绍了 React 的 **基础知识**：组件、prop 和 state。
```

这里的就是状态

2023-04-08 14:27 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [概览](#overview) 介绍了 React 的 **基础知识**：组件、prop 和 state。
状态的范围更广一点

2023-04-08 14:30 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +`value` 存储值，而 `setValue` 是可用于更改值的函数。传递给 `useState` 的 `null` 用作这个 state 变量的初始值，因此此处 `value` 的值开始时等于 null。
这里应该指的这个变量是有状态的

2023-04-09 10:12 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [概览](#overview) 介绍了 React 的 **基础知识**：组件、prop 和 state。
但是这里的 `state` 是 React 定义的术语吧，和 prop 一样，我个人倾向于保留原文不翻译

2023-04-09 10:25 UTC, fwqaaq commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [概览](#overview) 介绍了 React 的 **基础知识**：组件、prop 和 state。
🤔，但是 react 这里的 state 并不是指的 useState，我建议是翻译

2023-04-09 10:27 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [概览](#overview) 介绍了 React 的 **基础知识**：组件、prop 和 state。
目前 state 的翻译需要明确界限，我会开一个 discussion 讨论一下

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +第一行定义了一个名为 `Square` 的函数。`export` JavaScript 关键字使此函数可以在此文件之外访问。`default` 关键字表明它是文件中的主要函数。
```suggestion
第一行定义了一个名为 `Square` 的函数。JavaScript 的 `export` 关键字使此函数可以在此文件之外访问。`default` 关键字表明它是文件中的主要函数。
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +第二行返回一个按钮。`return` JavaScript 关键字意味着后面的内容都作为值返回给函数的调用者。`<button>` 是一个 JSX 元素。JSX 元素是 JavaScript 代码和 HTML 标签的组合，用于描述要显示的内容。`className="square"` 是一个 button 属性，它决定 CSS 如何设置按钮的样式。`X` 是按钮内显示的文本，`</button>
```suggestion
第二行返回一个按钮。JavaScript 的 `return` 关键字意味着后面的内容都作为值返回给函数的调用者。`<button>` 是一个 JSX 元素。JSX 元素是 JavaScript 代码和 HTML 标签的组合，用于描述要显示的内容。`className="square"` 是一个 button 属性，它决定 CSS 如何设置按钮的样式。`X` 是按钮内显示的文本，`</button>` 闭合 JSX 元素以表示不应将任何后续内容放置在按钮内。
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +单击 CodeSandbox 中的 `styles.css` 文件。该文件定义了 React 应用的样式。前两个 CSS 选择器（`*` 和 `body`）定义了应用大部分的样式，而 `.square` 选择器定义了 `className` 属性设置为 `square` 的组件的样式。这与 `App.js` 文件中的 `Square` 组件中的按钮是相匹配的。
```suggestion
单击 CodeSandbox 中的 `styles.css` 文件。该文件定义了 React 应用的样式。前两个 **CSS 选择器**（`*` 和 `body`）定义了应用大部分的样式，而 `.square` 选择器定义了 `className` 属性设置为 `square` 的组件的样式。这与 `App.js` 文件中的 `Square` 组件中的按钮是相匹配的。
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +将第 1-5 行将所有必要的部分组合在一起：
```suggestion
第 1-5 行将所有必要的部分组合在一起：
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +让我们回到 `App.js`。接下来我们将聚焦于这个文件。
```suggestion
让我们回到 `App.js`。接下来我们将专注于这个文件。
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +React 组件只能返回单个 JSX 元素，而不是像两个按钮那样的多个相邻的 JSX 元素。要解决此问题，可以使用 `<>` 和 `</>` 来包裹多个相邻的 JSX 元素，如下所示：
```suggestion
React 组件必须返回单个 JSX 元素，不能像两个按钮那样返回多个相邻的 JSX 元素。要解决此问题，可以使用 `<>` 和 `</>` 来包裹多个相邻的 JSX 元素，如下所示：
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +哦不！这些方块都在一条直线上，而不是排列成网格。要解决此问题，需要使用 `div` 将方块分到每一行中并添加一些 CSS 样式。当你这样做的时候，需要给每个方块一个数字，以确保你知道每个方块的位置。
```suggestion
但事与愿违的是这些方块并没有排列成网格，而是都在一条线上。要解决此问题，需要使用 `div` 将方块分到每一行中并添加一些 CSS 样式。当你这样做的时候，需要给每个方块一个数字，以确保你知道每个方块的位置。
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +`styles.css` 成功设置了样式！现在我们已经使用样式化的 `div` 将组件分组到行中，你拥有了井字棋棋盘：
```suggestion
借助 `styles.css` 中定义的 `board-row` 样式，我们将组件分到每一行的 `div` 中。最终完成了井字棋棋盘：
```

2023-04-09 12:24 UTC, loveloki commented on src/content/learn/tutorial-tic-tac-toe.md
> +嘶，要输入的内容太多了！可以从该页面复制和粘贴代码。但是，如果你愿意迎接一点挑战，我们建议只复制你自己至少手动输入过一次的代码。
```suggestion
嘶……要改的的内容也太多了！从该页面复制和粘贴代码是很好的办法。不过如果你愿意挑战一下自己，可以只复制手动输入过的代码。
```

2023-04-09 13:30 UTC, fwqaaq commented
> 这个我觉得是两码事，不是因为 useState 才有的 state，比如 class 组件就没有 useState 这种东西（？

你说的对，我只是举一个例子，像 component 一样，显而易见的是你也认为这是两码事，那很明显，其实它就是指的**状态**管理这个功能，而且 vue3 已经将其翻译，你不能不承认 vue 也是有状态管理的，但是它并未不翻译。

2023-04-09 13:45 UTC, awxiaoxian2020 commented
> > 这个我觉得是两码事，不是因为 useState 才有的 state，比如 class 组件就没有 useState 这种东西（？
> 
> 你说的对，我只是举一个例子，像 component 一样，其可以翻译为**组件**，所以它也完全可以翻译，并且显而易见的是你也认为这是两码事，那很明显，其实它就是指的**状态**管理这个功能，而且 vue3 已经将其翻译，你不能不承认 vue 也是有状态管理的，但是它并未不翻译。

我个人认为从宏观上讲这个概念的时候就翻译，否则不翻译。

2023-04-09 13:51 UTC, Yucohny commented on src/content/learn/tutorial-tic-tac-toe.md
> +`value` 存储值，而 `setValue` 是可用于更改值的函数。传递给 `useState` 的 `null` 用作这个 state 变量的初始值，因此此处 `value` 的值开始时等于 null。
句末的 null 调整为 `null`

2023-04-09 14:19 UTC, Yucohny commented on src/content/learn/tutorial-tic-tac-toe.md
> +title: '教程：井字棋游戏'
```suggestion
title: “教程：井字棋游戏”
```

2023-04-09 14:24 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +`App.js` 的代码创建了一个**组件**。在 React 中，组件是一段可重用代码，它通常作为 UI 界面的一部分。组件用于渲染、管理和更新应用中的 UI 元素。让我们逐行查看这段代码，看看发生了什么：
```suggestion
`App.js` 的代码创建了一个 **组件**。在 React 中，组件是一段可重用代码，它通常作为 UI 界面的一部分。组件用于渲染、管理和更新应用中的 UI 元素。让我们逐行查看这段代码，看看发生了什么：
```

2023-04-09 14:25 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +嘶……要改的的内容也太多了！从该页面复制和粘贴代码是很好的办法。不过如果你愿意挑战一下自己，可以只复制手动输入过的代码。
```suggestion
嘶……要改的内容也太多了！从该页面复制和粘贴代码是很好的办法。不过如果你愿意挑战一下自己，可以只复制手动输入过的代码。
```

2023-04-16 02:40 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +`value` 存储值，而 `setValue` 是可用于更改值的函数。传递给 `useState` 的 `null` 用作这个 state 变量的初始值，因此此处 `value` 的值开始时等于 null。
```suggestion
`value` 存储值，而 `setValue` 是可用于更改值的函数。传递给 `useState` 的 `null` 用作这个 state 变量的初始值，因此此处 `value` 的值开始时等于 `null`。
```

2023-04-16 02:41 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +React 提供了一个名为 `useState` 的特殊函数，可以从组件中调用它来让它“记住”一些东西。让我们将 `Square` 的当前值存储在 `state` 中，并在单击 `Square` 时更改它。
```suggestion
React 提供了一个名为 `useState` 的特殊函数，可以从组件中调用它来让它“记住”一些东西。让我们将 `Square` 的当前值存储在 state 中，并在单击 `Square` 时更改它。
```

2023-04-16 02:43 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +重新渲染列表时，React 获取每个列表项的 key 并搜索前一个列表的项以查找匹配的 key。如果当前列表有一个之前不存在的 key ，React 会创建一个组件。如果当前列表缺少前一个列表中存在的 key，React 会销毁前一个组件。如果两个 key 匹配，则落子相应的组件。
```suggestion
重新渲染列表时，React 获取每个列表项的 key 并搜索前一个列表的项以查找匹配的 key。如果当前列表有一个之前不存在的 key，React 会创建一个组件。如果当前列表缺少前一个列表中存在的 key，React 会销毁前一个组件。如果两个 key 匹配，则落子相应的组件。
```

2023-04-16 02:47 UTC, awxiaoxian2020 commented on src/content/learn/tutorial-tic-tac-toe.md
> +在本教程中，你已经接触到了 React 概念，包括元素、组件、props 和 state。现在你已经了解了这些概念在构建游戏时是如何工作的，请查看 [React 哲学](../learn/thinking-in-react) 以了解这些 React 概念在构建应用的 UI 时是如何工作的。
```suggestion
在本教程中，你已经接触到了 React 概念，包括元素、组件、props 和 state。现在你已经了解了这些概念在构建游戏时是如何工作的，请查看 [React 哲学](/learn/thinking-in-react) 以了解这些 React 概念在构建应用的 UI 时是如何工作的。
```

2023-06-21 12:24 UTC, merged