提交时的注释
reactjs/zh-hans.react.dev pull request #1129
Opened 2023-04-13 03:32 UTC by cxybd

2023-04-13 03:35 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +
```suggestion
```

2023-04-13 06:24 UTC, awxiaoxian2020 commented
请仔细阅读 https://github.com/reactjs/zh-hans.react.dev/blob/main/TRANSLATION.md 调整相关格式

2023-04-14 01:59 UTC, cxybd commented
> 仍然不是行行对应~请检查

行行对应是啥意思呀，要和英文文档行数一样嘛 @awxiaoxian2020

2023-04-14 02:44 UTC, awxiaoxian2020 commented
> > 仍然不是行行对应~请检查
> 
> 行行对应是啥意思呀，要和英文文档行数一样嘛 @awxiaoxian2020 

你可以在file changes里面看到，左边的红色减和右边的加在行数上要是对应的。

2023-04-14 02:50 UTC, cxybd commented
> > > 仍然不是行行对应~请检查
> > 
> > 
> > 行行对应是啥意思呀，要和英文文档行数一样嘛 @awxiaoxian2020
> 
> 你可以在file changes里面看到，左边的红色减和右边的加在行数上要是对应的。

2023-04-14 02:51 UTC, cxybd commented
> > > > 仍然不是行行对应~请检查
> > > 
> > > 
> > > 行行对应是啥意思呀，要和英文文档行数一样嘛 @awxiaoxian2020
> > 
> > 
> > 你可以在file changes里面看到，左边的红色减和右边的加在行数上要是对应
但是中文翻译之后行数会变少怎么办

2023-04-14 02:56 UTC, awxiaoxian2020 commented
> > > > > 仍然不是行行对应~请检查
> > > > 
> > > > 
> > > > 行行对应是啥意思呀，要和英文文档行数一样嘛 @awxiaoxian2020
> > > 
> > > 
> > > 你可以在file changes里面看到，左边的红色减和右边的加在行数上要是对应
> > > 但是中文翻译之后行数会变少怎么办

使用空行补齐，终极目的要对应

2023-04-14 03:27 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +## 参考
```suggestion
## 参考

```

2023-04-14 03:28 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +在你组件的顶层调用 `useCallback` 以便于在多次渲染中缓存函数：
```suggestion
在你组件的顶层调用 `useCallback` 以便于在多次渲染中缓存函数：

```

2023-04-14 03:28 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +#### 警告 {/*caveats*/}
```suggestion

#### 警告 {/*caveats*/}
```

2023-04-14 03:30 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion
```

2023-04-14 03:31 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +}
```suggestion
```

2023-04-14 03:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
漏翻了，请再次检查行数问题

2023-04-14 03:35 UTC, awxiaoxian2020 requested changes

2023-04-14 03:35 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
漏翻了，加上以后请再次检查行数问题

2023-04-14 06:17 UTC, cxybd commented on src/content/reference/react/useCallback.md
谢谢谢谢！

2023-04-14 07:23 UTC, awxiaoxian2020 commented
个人建议关闭这个 PR。重新从 main 分支新建分支，重新翻译。

你应该是因为漏翻，又动了代码块，所以导致行数混乱

2023-04-14 07:25 UTC, awxiaoxian2020 commented
代码块的翻译可以放在后面，先不翻译，等行数稳定了我们再说

2023-04-14 07:50 UTC, cxybd commented on src/content/reference/react/useCallback.md
> +<<<<<<< HEAD
okok谢谢！

2023-04-14 07:56 UTC, awxiaoxian2020 requested changes

2023-04-14 07:56 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +
这个地方行数以及代码块内容似乎出现问题，请修正

2023-04-14 09:29 UTC, awxiaoxian2020 commented
你不小心新建了一个空文件，请删除，目前看来行数似乎仍然不对应，请继续检查

2023-04-14 09:30 UTC, awxiaoxian2020 requested changes

2023-04-14 09:30 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +```
比如说这个地方多了 Markdown 标记，请仔细对照英文原文检查~

2023-04-14 10:06 UTC, cxybd commented on src/content/reference/react/useCallback.md
> +```
我加了个空格让行数保持一致但是我没有加标记哦

2023-04-14 11:35 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion
```

2023-04-14 11:38 UTC, awxiaoxian2020 requested changes

2023-04-14 11:38 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> -On the following renders, React will compare the <CodeStep step={2}>dependencies</CodeStep> with the dependencies you passed during the previous render. If none of the dependencies have changed (comp
86 行漏翻，请检查

2023-04-15 02:30 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
>  ```js {3,5}
```suggestion

```js {3,5}
```

2023-04-15 02:32 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion
```

2023-04-15 02:32 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +
```suggestion
}
```

2023-04-15 02:33 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +       {/*那么ShippingForm永远都不会是同一个，并且它每次都会重新渲染 */}
```suggestion
      {/*那么ShippingForm永远都不会是同一个，并且它每次都会重新渲染 */}
```

2023-04-15 02:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +  const handleSubmit = useCallback((orderDetails) => {  // 缓存函数本身
```suggestion
  const handleSubmit = useCallback((orderDetails) => { // 缓存函数本身
```

2023-04-15 02:34 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +function ProductPage({ productId, referrer, theme }) {
```suggestion
function ProductPage({ productId, referrer, theme }) {
```

2023-04-15 02:36 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
>  ```
```suggestion
}
```
```

2023-04-15 02:39 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
>    }
```suggestion
  }
  
```

2023-04-15 02:41 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
>  ```
```suggestion
}
```
```

2023-04-15 02:42 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion


```

2023-04-15 02:42 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion
```
```

2023-04-15 02:50 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion
```

2023-04-15 02:50 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion
```

2023-04-15 02:51 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
>  ```js {2,3,8,12-13}
```suggestion

```js {2,3,8,12-13}
```

2023-04-15 02:52 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
```suggestion
```

2023-04-15 02:53 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +在其他情况下，将函数包装在 `useCallback` 中没有任何益处。这样做也没有很大的害处。所以有些团队选择不考虑个案，并且尽可能记住。不好的部分是代码可读性降低了。而且，并不是所有的记忆都是有效的：一个 “始终新” 的值足以破坏整个组件的记忆。
```suggestion

在其他情况下，将函数包装在 `useCallback` 中没有任何益处。这样做也没有很大的害处。所以有些团队选择不考虑个案，并且尽可能记住。不好的部分是代码可读性降低了。而且，并不是所有的记忆都是有效的：一个 “始终新” 的值足以破坏整个组件的记忆。
```

2023-04-15 03:01 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
>  </DeepDive>
```suggestion

</DeepDive>
```

2023-04-15 03:02 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
>  <Sandpack>
```suggestion

<Sandpack>
```

2023-04-15 03:02 UTC, awxiaoxian2020 commented on src/content/reference/react/useCallback.md
> +#### 始终重新渲染组件{/*always-re-rendering-a-component*/}
```suggestion
#### 始终重新渲染组件{/*always-re-rendering-a-component*/}

```

2023-04-15 03:14 UTC, cxybd commented
还有需要修改的吗，抱歉一直打扰你，第一次做，出现了很多低级错误

2023-04-15 03:43 UTC, awxiaoxian2020 commented
我已经帮你修改完毕。但是我建议你查看一下我给你修改的[内容](https://github.com/reactjs/zh-hans.react.dev/pull/1129/commits/6c29ae71ef1ec3cda60c5d92abb97faba602a07e)，设法以后避免出现这一不对应的情况。

2023-04-15 08:01 UTC, cxybd commented
> 我已经帮你修改完毕。但是我建议你查看一下我给你修改的[内容](https://github.com/reactjs/zh-hans.react.dev/pull/1129/commits/6c29ae71ef1ec3cda60c5d92abb97faba602a07e)，设法以后避免出现这一不对应的情况。
还需要我做什么嘛，还是等待校对完成

2023-04-15 08:54 UTC, awxiaoxian2020 commented
> > 我已经帮你修改完毕。但是我建议你查看一下我给你修改的[内容](https://github.com/reactjs/zh-hans.react.dev/pull/1129/commits/6c29ae71ef1ec3cda60c5d92abb97faba602a07e)，设法以后避免出现这一不对应的情况。
> 还需要我做什么嘛，还是等待校对完成

等待新的 review 吧

2023-04-15 10:53 UTC, Yucohny commented on src/content/reference/react/useCallback.md
> +* `fn` ： 你想要缓存的函数。 这个函数可以接受任何参数并且返回任何值。React将会在初次渲染中（并不是调用！）将这个函数返回。下一次渲染时, 如果 `dependencies` 自从上一次从未改变，React将会返回相同的函数。否则, React将返回你在最新一次渲染中传入的函数, 并且将其缓存下来以便稍后使用。 React将不会调用你的函数。这个函数返回给你，如此你可以决定何时调用它
```suggestion
* `fn`：你想要缓存的函数。这个函数可以接受任何参数并且返回任何值。React 将会在初次渲染中（并不是调用！）将这个函数返回。下一次渲染时，如果 `dependencies` 自从上一次从未改变，React 将会返回相同的函数。否则，React 将返回你在最新一次渲染中传入的函数，并且将其缓存下来以便稍后使用。React 将不会调用你的函数。这个函数返回给你，如此你可以决定何时调用它或者是否调用它。
```

2023-04-15 10:53 UTC, Yucohny commented
请检查中英文标点与必要的空格。

2023-06-19 10:23 UTC, Yucohny reviewed
烦请自查一下格式~

2023-06-19 10:23 UTC, Yucohny commented on src/content/reference/react/useCallback.md
> +**默认情况下，当一个组件重新渲染时， React 将递归渲染它的所有子组件。** 这就是为什么， 当含有不同 `theme` 值的 `ProductPage` 组件重新渲染时，`ShippingForm` 组件**也**重新渲染。这对于不需要大量计算去重新渲染的组件来说影响很小。但如果你发现某次重新渲染很慢，你可以将 `ShippingForm` 组件包裹在 [`memo`](/referen
句末表达移至加粗外。

2023-06-19 10:23 UTC, Yucohny commented on src/content/reference/react/useCallback.md
> +**有了这个变化，`ShippingForm` 将跳过重新渲染，如果它的所有props都与上次渲染时相同。** 这时候缓存函数就变得很重要了！假设你定义了 `handleSubmit` 而没有定义 `useCallback`:
句末标点移至加粗外。

2023-06-19 10:23 UTC, Yucohny commented on src/content/reference/react/useCallback.md
> +  // 每一次theme改变的时候，都会生成一个不同的函数
空格

2023-06-19 10:23 UTC, Yucohny commented on src/content/reference/react/useCallback.md
> +      {/*那么ShippingForm永远都不会是同一个，并且它每次都会重新渲染 */}
空格

2023-06-19 10:23 UTC, Yucohny commented on src/content/reference/react/useCallback.md
> +**在JavaScript中， `function () {}` 或者 `() => {}` 总是会生成不同的函数，** 和字面对象 `{}` 总会创建新的对象类似。正常情况下，这不会产生问题，但是这意味着 `ShippingForm` 的props将永远不会是相同的，并且你的 [`memo`](/reference/react/memo) 优化永远不会生效。这就是 `useCallback`
空格

2023-06-29 07:06 UTC, closed without merging

2023-06-29 07:06 UTC, Yucohny commented
考虑到原译者许久未更新且此 PR 仍然存在 **太多** 格式与翻译问题，关闭此 PR。

2023-10-26 12:10 UTC, cxybd commented
看到待校对就没关注，抱歉！贡献者名单里面会有我吗