translate reference/react/useRef
reactjs/zh-hans.react.dev pull request #1132
Opened 2023-04-14 16:33 UTC by Yukiniro

2023-04-15 10:48 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +有时，你可能想让父级组件在你的组件中操纵 DOM。例如，也许你正在写一个 `MyInput` 组件，但你希望父组件能够聚焦 input（父组件无法访问）。你可以使用一个组合，通过 `useRef` 持有 input 并且通过 [`forwardRef`](/reference/react/forwardRef) 来将其暴露给父组件。在这里阅读一个[详细演练](/learn/manipulatin
```suggestion
有时，你可能想让父级组件在你的组件中操纵 DOM。例如，也许你正在写一个 `MyInput` 组件，但你希望父组件能够聚焦 input（父组件无法访问）。你可以使用一个组合，通过 `useRef` 持有 input 并且通过 [`forwardRef`](/reference/react/forwardRef) 来将其暴露给父组件。在这里阅读一个 [详细演练](/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes)。
```

2023-04-15 10:48 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +React 保存首次的 ref 初始值，并在后续的渲染中忽略他。
```suggestion
React 保存首次的 ref 初始值，并在后续的渲染中忽略它。
```

2023-04-15 10:48 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +#### 如何避免在初始化 useRef 之后进行 null 的类型检查 {/*how-to-avoid-null-checks-when-initializing-use-ref-later*/}
```suggestion
#### 如何避免在初始化 `useRef` 之后进行 `null` 的类型检查 {/*how-to-avoid-null-checks-when-initializing-use-ref-later*/}
```

2023-04-15 10:48 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +默认情况下，你自己的组件不会暴露它们内部的 DOM 节点的 refs。
```suggestion
默认情况下，你自己的组件不会暴露它们内部的 DOM 节点的 ref。
```

2023-04-15 10:48 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +阅读更多关于[访问另一个组件的 DOM 节点](/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes)。
```suggestion
阅读更多关于 [访问另一个组件的 DOM 节点](/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes)。
```

2023-04-20 01:07 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +改变 ref 不会触发重新渲染，所以 refs 不适合存储用于你想要显示在屏幕上的信息。使用 state 代替。阅读更多[在 `useRef` 和 `useState` 之间选择。](/learn/referencing-values-with-refs#differences-between-refs-and-state)
```suggestion
改变 ref 不会触发重新渲染，所以 ref 不适合存储用于你想要显示在屏幕上的信息。如有需要，使用 state 代替。阅读更多 [在 `useRef` 和 `useState` 之间选择](/learn/referencing-values-with-refs#differences-between-refs-and-state)。
```

2023-04-20 01:07 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +你可以在 **事件处理函数或者 effects** 中读取和写入 refs。
```suggestion
你可以在 **事件处理函数或者 effects** 中读取和写入 ref。
```

2023-04-20 01:07 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +    // ✅ 你可以在 effects 中读取和写入 refs
```suggestion
    // ✅ 你可以在 effects 中读取和写入 ref
```

2023-04-20 01:07 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +    // ✅ 你可以在事件处理函数中读取和写入 refs
```suggestion
    // ✅ 你可以在事件处理函数中读取和写入 ref
```

2023-04-20 01:07 UTC, Yucohny commented on src/content/reference/react/useRef.md
> +阅读更多关于[用 ref 操纵DOM](/learn/manipulating-the-dom-with-refs)
```suggestion
阅读更多关于 [用 ref 操纵DOM](/learn/manipulating-the-dom-with-refs)
```

2023-04-20 07:02 UTC, awxiaoxian2020 requested changes

2023-04-20 07:02 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +React 期望你的组件的主体[表现得像一个纯函数](/learn/keeping-components-pure)：
```suggestion
React 期望你的组件的主体 [表现得像一个纯函数](/learn/keeping-components-pure)：
```

2023-04-23 13:31 UTC, Yucohny approved these changes

2023-04-24 02:01 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +* 在严格模式下，React 将会 **调用两次你的组件方法**，这是为了[帮助你发现意外的问题](#my-initializer-or-updater-function-runs-twice)。这只是开发模式下的行为，不影响生产模式。每个 ref 对象将会创建两次，但是其中一个版本将被丢弃。如果你的组件函数是纯的（应该如此），这不会影响其行为。
```suggestion
* 在严格模式下，React 将会 **调用两次你的组件方法**，这是为了 [帮助你发现意外的问题](#my-initializer-or-updater-function-runs-twice)。这只是开发模式下的行为，不影响生产模式。每个 ref 对象将会创建两次，但是其中一个版本将被丢弃。如果你的组件函数是纯的（应该如此），这不会影响其行为。
```

2023-04-24 02:02 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +阅读更多关于 [访问另一个组件的 DOM 节点](/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes)。
```suggestion
阅读 [访问另一个组件的 DOM 节点](/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes) 了解更多信息。
```

2023-04-24 02:02 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +然后像这样将其包装在 [`forwardRef`](/reference/react/forwardRef)：
```suggestion
然后像这样将其包装在 [`forwardRef`](/reference/react/forwardRef) 里：
```

2023-04-24 02:03 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +在这里，`playerRef` 本身是可以为空的。然而，你应该能够说服你的类型检查器，不存在 `getPlayer()` 返回 `null` 的情况。然后在你的事件处理程序中使用 `getPlayer()`。
```suggestion
在这里，`playerRef` 本身是可以为空的。然而，你应该能够使你的类型检查器确信，不存在 `getPlayer()` 返回 `null` 的情况。然后在你的事件处理程序中使用 `getPlayer()`。
```

2023-04-24 02:05 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +当你打破这些规则时，你的组件可能仍然可以工作，但我们添加到 React 的大多数新功能将依赖于这些预期行为。阅读更多关于[保持你的组件纯粹。](/learn/keeping-components-pure#where-you-can-cause-side-effects)
```suggestion
当你打破这些规则时，你的组件可能仍然可以工作，但我们添加到 React 的大多数新功能将依赖于这些预期行为。阅读 [保持你的组件纯粹](/learn/keeping-components-pure#where-you-can-cause-side-effects) 以了解更多信息。
```。

2023-04-24 02:06 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +使用 ref 操作 [DOM](https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_DOM_API) 是非常常见的。React 对此有内置支持。
```suggestion
使用 ref 操作 [DOM](https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_DOM_API) 是非常常见的。React 内置了对它的支持。
```

2023-04-24 02:07 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +阅读更多关于 [用 ref 操纵DOM](/learn/manipulating-the-dom-with-refs)
```suggestion
阅读 [用 ref 操纵 DOM](/learn/manipulating-the-dom-with-refs) 以了解更多信息。
```

2023-04-24 02:09 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +当你打破这些规则时，你的组件可能仍然可以工作，但我们添加到 React 的大多数新功能将依赖于这些预期行为。阅读 [保持你的组件纯粹](/learn/keeping-components-pure#where-you-can-cause-side-effects) 以了解更多信息。
```suggestion
当你打破这些规则时，你的组件可能仍然可以工作，但我们添加到 React 的大多数新功能将依赖于这些预期行为。阅读 [保持你的组件纯粹](/learn/keeping-components-pure#where-you-can-cause-side-effects) 以了解更多信息。

```

2023-04-24 02:09 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
> +```。
```suggestion
```
```

2023-04-24 02:10 UTC, awxiaoxian2020 commented on src/content/reference/react/useRef.md
```suggestion
```

2023-04-24 02:14 UTC, awxiaoxian2020 requested changes
建议按照中文表达习惯作一些优化~

2023-04-25 00:10 UTC, awxiaoxian2020 approved these changes
LGTM! Welcome aboard!

2023-04-25 00:13 UTC, merged