docs(cn): translate hydrateRoot
reactjs/zh-hans.react.dev pull request #1139
Opened 2023-04-24 14:06 UTC by childrentime

2023-04-24 14:07 UTC, childrentime commented
@QC-L

2023-04-25 00:17 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/client/hydrateRoot.md
> +#### 返回值 {/*returns*/}
```suggestion

#### 返回值 {/*returns*/}
```

2023-04-25 00:18 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/client/hydrateRoot.md
> +#### 返回值 {/*root-render-returns*/}
```suggestion

#### 返回值 {/*root-render-returns*/}
```

2023-04-25 00:19 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/client/hydrateRoot.md
> +`root.unmount` 不接受任何参数。
```suggestion

`root.unmount` 不接受任何参数。
```

2023-04-25 00:24 UTC, awxiaoxian2020 requested changes
hydrate hydration 目前不翻译，请调整

2023-04-25 00:24 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/client/hydrateRoot.md
> +* React 可以从一些水合错误中恢复，但**你必须像处理其他 bug 一样修复它们**。在最好的情况下，它们会导致应用程序加载减速；在最坏的情况下，事件处理程序可能会附加到错误的元素上。
这里出现漏翻

2023-04-27 02:00 UTC, awxiaoxian2020 commented
请将 hydrate 相关单词调整为动词、名词的原形，不保留过去式相关。

2023-04-27 06:39 UTC, childrentime commented
已更改

2023-05-10 13:45 UTC, childrentime commented
@awxiaoxian2020  any other problems

2023-06-20 08:50 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +* `domNode`: 一个在服务器端渲染时呈现为根元素的 [DOM 元素](https://developer.mozilla.org/zh-CN/docs/Web/API/Element)。
```suggestion
* `domNode`：一个在服务器端渲染时呈现为根元素的 [DOM 元素](https://developer.mozilla.org/zh-CN/docs/Web/API/Element)。
```

2023-06-20 08:50 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +* **可选**  `options` ：一个包含此 React 根元素选项的对象。
```suggestion
* **可选**  `options`：一个包含此 React 根元素选项的对象。
```

2023-06-20 08:50 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +  * **可选**  `identifierPrefix` ：字符串前缀，用于标识由 [`useId`](/reference/react/useId) 生成的 ID ，可以避免在同一页面上使用多个 React 根元素时出现冲突。必须与服务端使用的前缀相同。
```suggestion
  * **可选**  `identifierPrefix` ：字符串前缀，用于标识由 [`useId`](/reference/react/useId) 生成的 ID，可以避免在同一页面上使用多个 React 根元素时出现冲突。必须与服务端使用的前缀相同。
```

2023-06-21 07:58 UTC, childrentime commented
@Yucohny 重新查了一遍

2023-06-25 11:55 UTC, Yucohny reviewed
请自查相关格式。

2023-06-25 11:55 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +* `domNode`： 一个在服务器端渲染时呈现为根元素的 [DOM 元素](https://developer.mozilla.org/zh-CN/docs/Web/API/Element)。
意外的空格问题。

2023-06-25 11:55 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +使用  `root.render` 更新一个 hydrate 根组件中的 React 组件来渲染浏览器端 DOM 元素。
意外的空格问题。

2023-06-29 07:41 UTC, Yucohny commented
请注意，在 review 后长时间未针对评论指出的问题进行更新，将会关闭此 PR。

2023-06-29 12:52 UTC, childrentime commented
@Yucohny  又修改了一下

2023-07-03 01:51 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +* `reactNode`： 用于渲染已存在 HTML 的 "React 节点"。这个节点通常是一些类似于 `<App />` 的 JSX  ，它会在 `ReactDOM Server` 端使用类似于  `renderToPipeableStream(<App />)` 的方法进行渲染。
```suggestion
* `reactNode`：用于渲染已存在 HTML 的“React 节点”。这个节点通常是一些类似于 `<App />` 的 JSX，它会在 `ReactDOM Server` 端使用类似于 `renderToPipeableStream(<App />)` 的方法进行渲染。
```

2023-07-03 01:51 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +* 在开发模式下，React 会在 hydration 期间发出不匹配警告。在不匹配的情况下，不能保证内容差异会被修补。出于性能原因，这很重要，因为在大多数应用程序中，不匹配很少见，因此验证所有标记将是昂贵而不可行的。
```suggestion
* 在开发模式下，React 会在 hydrate 期间发出不匹配警告。在不匹配的情况下，不能保证内容差异会被修补。出于性能原因，这很重要，因为在大多数应用程序中，不匹配很少见，因此验证所有标记将是昂贵而不可行的。
```

2023-07-03 01:51 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +这主要适用于 React 根节点的 DOM 节点（或其任何祖先节点）可能会被其他代码从 DOM 中移除的情况。例如，想象一下一个 jQuery 标签面板，它会将非活动标签从 DOM 中移除。如果一个标签被移除，其内部的所有内容（包括其中的 React 根节点）也将从 DOM 中移除。你需要调用 root.unmount 来告诉 React “停止”管理已移除根节点的内容。否则，已移除根节点内的组
```suggestion
这主要适用于 React 根节点的 DOM 节点（或其任何祖先节点）可能会被其他代码从 DOM 中移除的情况。例如，想象一下一个 jQuery 标签面板，它会将非活动标签从 DOM 中移除。如果一个标签被移除，其内部的所有内容（包括其中的 React 根节点）也将从 DOM 中移除。你需要调用 `root.unmount` 来告诉 React “停止”管理已移除根节点的内容。否则，已移除根节点内的组件将无法清理和释放已使用的资源，例如订阅。
```

2023-07-03 01:51 UTC, Yucohny commented on src/content/reference/react-dom/client/hydrateRoot.md
> +* 如果你在根节点还没有完成 hydrating 的情况下调用了 `root.render`，React 将清除现有的服务端渲染 HTML 内容，并将整个根节点切换到客户端渲染。
```suggestion
* 如果你在根节点还没有完成 hydrate 的情况下调用了 `root.render`，React 将清除现有的服务端渲染 HTML 内容，并将整个根节点切换到客户端渲染。
```

2023-07-03 01:53 UTC, merged