docs(cn): translate reference/react-dom/createPortal into Chinese
reactjs/zh-hans.react.dev pull request #1140
Opened 2023-04-24 15:08 UTC by Yucohny

翻译 reference/react-dom/createPortal

2023-04-25 03:35 UTC, awxiaoxian2020 requested changes

2023-04-25 03:35 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/createPortal.md
> +*Portals* 允许组件将它们的某些子元素渲染到 DOM 中的不同位置。这使得组件的一部分可以“逃脱”它所在的容器。例如，组件可以显示出现在页面其余部分之上和之外的模态对话框或工具提示。
```suggestion
*portal* 允许组件将它们的某些子元素渲染到 DOM 中的不同位置。这使得组件的一部分可以“逃脱”它所在的容器。例如，组件可以显示出现在页面其余部分之上和之外的模态对话框或工具提示。
```

2023-05-05 16:06 UTC, loveloki commented on src/content/reference/react-dom/createPortal.md
> +要创建 portal，请使用 <CodeStep step={1}>JSX</CodeStep> 和 <CodeStep step={2}>应该放置的 DOM 节点</CodeStep> 渲染 `createPortal` 的结果：
不知道是不是因为夹杂了 <CodeStep> 的原因

2023-05-18 14:23 UTC, loveloki approved these changes

2023-05-18 14:23 UTC, loveloki commented on src/content/reference/react-dom/createPortal.md
> +portal 只改变 DOM 节点的所处位置。在其他方面，入 portal 中的 JSX 将作为渲染它的 React 组件的子节点。该子节点可以访问由父节点树提供的 context 对象、事件将仍然从子节点冒泡到父节点树。
```suggestion
portal 只改变 DOM 节点的所处位置。另一方面，portal 中的 JSX 将作为实际渲染它的 React 组件的子节点。该子节点可以访问由父节点树提供的 context 对象、事件将仍然从子节点冒泡到父节点树。
```

2023-05-18 14:23 UTC, loveloki commented on src/content/reference/react-dom/createPortal.md
> +你可以使用 portal 创建一个浮动在页面其余部分之上的模态对话框，即使呼出对话框的组件位于带有 `overflow: hidden` 或其他干扰对话框的样式的容器中。
```suggestion
你可以使用 portal 创建一个浮动在页面其余部分之上的模态对话框，即使呼出对话框的组件位于带有 `overflow: hidden` 或其他干扰对话框样式的容器中。
```

2023-05-18 14:23 UTC, loveloki commented on src/content/reference/react-dom/createPortal.md
> +创建模态对话框时，请遵循 [WAI-ARIA 模态作者实践指南](https://www.w3.org/WAI/ARIA/apg/#dialog_modal)。如果你使用了社区包，请确保它是无障碍的，并遵循这些指南。
```suggestion
创建模态对话框时，请遵循 [WAI-ARIA 模态实践指南](https://www.w3.org/WAI/ARIA/apg/#dialog_modal)。如果你使用了社区包，请确保它是无障碍的，并遵循这些指南。
```

2023-05-18 14:23 UTC, loveloki commented on src/content/reference/react-dom/createPortal.md
> +如果你的网站只有一部分使用 React 构建，而其他部分是静态页面或由服务器呈现的页面，则 portal 可能非常有用。如果你的页面使用 Rails 等服务端框架构建，则可以在静态区域（例如侧边栏）中创建交互区域。与拥有 [多个独立的 React 根](/reference/react-dom/client/createRoot#rendering-a-page-partially-built-
```suggestion
如果你在静态或服务端渲染的网站中只有某一部分使用 React，则 portal 可能非常有用。如果你的页面使用 Rails 等服务端框架构建，则可以在静态区域（例如侧边栏）中创建交互区域。与拥有 [多个独立的 React 根](/reference/react-dom/client/createRoot#rendering-a-page-partially-built-with-react) 相比，portal 将应用程序视为具有共享状态的单个 React 树，即使其部分呈现到 DOM 的不同部分也是如此。
```

2023-05-19 23:31 UTC, awxiaoxian2020 approved these changes

2023-05-19 23:34 UTC, merged