docs(cn): translate reference/react/useSyncExternalStore into Chinese
reactjs/zh-hans.react.dev pull request #1143
Opened 2023-04-26 15:58 UTC by levinqdl

2023-05-19 23:28 UTC, awxiaoxian2020 requested changes

2023-05-19 23:28 UTC, awxiaoxian2020 commented on src/content/reference/react/useSyncExternalStore.md
> +* `getSnapshot` 返回的 store 快照必需是不可变的。如果底层 store 有可变数据，要数据改变时返回一个新的不可变快照。否则，返回上次缓存的快照。
```suggestion
* `getSnapshot` 返回的 store 快照必须是不可变的。如果底层 store 有可变数据，要数据改变时返回一个新的不可变快照。否则，返回上次缓存的快照。
```

2023-05-19 23:28 UTC, awxiaoxian2020 commented on src/content/reference/react/useSyncExternalStore.md
> +  return true; // 服务端生成的HTML总是显示“在线“
```suggestion
  return true; // 服务端生成的 HTML 总是显示“在线”
```

2023-05-19 23:28 UTC, awxiaoxian2020 commented on src/content/reference/react/useSyncExternalStore.md
> +- 在客户端 [水合](/reference/react-dom/client/hydrateRoot) 时，如：当 React 拿到服务端的 HTML 并使其可交互。
hydration 不翻译。

2023-05-20 03:54 UTC, levinqdl commented
@awxiaoxian2020 已经按 review 建议更新

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +在你的组件顶层调用 `useSyncExternalStore` 来从外部数据 store 读取值。
store 就是用来存储 data，因此把“data store”翻译为“数据 store”有点冗余，两个单词都保留原文也很怪，可以考虑直接使用 store。

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +* `subscribe`: 一个函数，接收一个单独的 `callback` 参数并把它订阅到 store 上。 当 store 发生改变，它应当调用被提供的 `callback`。这会导致组件重新渲染。`subscribe` 函数会返回清除订阅的函数。
```suggestion
* `subscribe`: 一个函数，接收一个单独的 `callback` 参数并把它订阅到 store 上。当 store 发生改变，它应当调用被提供的 `callback`。这会导致组件重新渲染。`subscribe` 函数会返回清除订阅的函数。
```

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +#### 返回 {/*returns*/}
```suggestion
#### 返回值 {/*returns*/}
```

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +添加 `useSyncExternalStore` 的另一个原因是当你想订阅一些由浏览器暴露的，随时间变化的值时。例如，假设你想要你的组件展示是否网络连接正常。浏览器通过一个叫做 [`navigator.onLine`.](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) 的属性暴露出这一信息。
```suggestion
添加 `useSyncExternalStore` 的另一个场景是当你想订阅一些由浏览器暴露的并随时间变化的值时。例如，假设你想要你的组件展示是否网络连接正常。浏览器通过一个叫做 [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) 的属性暴露出这一信息。
```

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +添加 `useSyncExternalStore` 的另一个原因是当你想订阅一些由浏览器暴露的，随时间变化的值时。例如，假设你想要你的组件展示是否网络连接正常。浏览器通过一个叫做 [`navigator.onLine`.](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) 的属性暴露出这一信息。
此处翻译后的内容使用“原因”有点奇怪

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +- 如果你连接到一个浏览器特有的API，因为它在服务端不存在，所以是不行的。
```suggestion
- 如果你连接到一个浏览器特有的 API，因为它在服务端不存在，所以是不行的。
```

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +  return true; // 服务端生成的 HTML 总是显示“在线“
```suggestion
  return true; // 服务端生成的 HTML 总是显示“在线”
```

2023-06-16 07:58 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +### 遇到一个错误: "The result of `getSnapshot` should be cached" {/*im-getting-an-error-the-result-of-getsnapshot-should-be-cached*/}
```suggestion
### 遇到一个错误：“The result of `getSnapshot` should be cached” {/*im-getting-an-error-the-result-of-getsnapshot-should-be-cached*/}
```

2023-06-24 13:05 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +* `subscribe`: 一个函数，接收一个单独的 `callback` 参数并把它订阅到 store 上。当 store 发生改变，它应当调用被提供的 `callback`。这会导致组件重新渲染。`subscribe` 函数会返回清除订阅的函数。
```suggestion
* `subscribe`：一个函数，接收一个单独的 `callback` 参数并把它订阅到 store 上。当 store 发生改变，它应当调用被提供的 `callback`。这会导致组件重新渲染。`subscribe` 函数会返回清除订阅的函数。
```

2023-06-24 13:05 UTC, Yucohny commented on src/content/reference/react/useSyncExternalStore.md
> +* `subscribe`: 一个函数，接收一个单独的 `callback` 参数并把它订阅到 store 上。当 store 发生改变，它应当调用被提供的 `callback`。这会导致组件重新渲染。`subscribe` 函数会返回清除订阅的函数。
请自查相关标点问题。

2023-06-24 21:28 UTC, Yucohny approved these changes

2023-06-24 21:28 UTC, merged