docs(cn): translate reference/react/useInsertionEffect into Chinese
reactjs/zh-hans.react.dev pull request #1166
Opened 2023-05-11 10:56 UTC by NewVo1d

reference/react/useInsertionEffect 已翻译完成，辛苦review
@QC-L @Yucohny @awxiaoxian2020

2023-05-18 02:44 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +`useInsertionEffect` 适用于 CSS-in-JS 库作者。除非你正在使用 CSS-in-JS 库并且需要注入样式，否则你应该使用 [`useEffect`](/reference/react/useEffect) 或者 [`useLayoutEffect`](/reference/react/useLayoutEffect)。
```suggestion
`useInsertionEffect` 是为 CSS-in-JS 库的作者特意打造的。除非你正在使用 CSS-in-JS 库并且需要注入样式，否则你应该使用 [`useEffect`](/reference/react/useEffect) 或者 [`useLayoutEffect`](/reference/react/useLayoutEffect)。
```

2023-05-18 02:44 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +`useInsertionEffect` 是 [`useEffect`](/reference/react/useEffect) 的一个版本，在任何 DOM 变化前触发。
原文虽然是使用的 ”version“，但是这个地方使用”一个版本“意思有点怪，会不会有些不合适？”一种实现“？可以再考虑考虑。

2023-05-18 02:44 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +[请参考下方更多示例](#usage)
```suggestion
[请参考下方更多示例](#usage)。
```

2023-05-18 02:44 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +* `setup`：处理副作用的函数。setup 函数选择性返回一个 **清理（cleanup）** 函数。在将组件首次添加到 DOM 之前，React 将运行 setup 函数。在每次依赖项变更重新渲染后，React 将首先使用旧值运行 cleanup 函数（如果你提供了该函数），然后使用新值运行 setup 函数。在组件从 DOM 中移除前，React 将运行 cleanup 函数。
```suggestion
* `setup`：处理副作用的函数。setup 函数选择性返回一个 **清理（cleanup）** 函数。在将组件首次添加到 DOM 之前，React 将运行 setup 函数。在每次依赖项变更重新渲染后，如果你提供了 cleanup 函数，那么 React 将首先使用旧值运行该函数，然后使用新值运行 setup 函数。在组件从 DOM 中移除前，React 将运行 cleanup 函数。
```

2023-05-18 02:44 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +如果你使用 CSS-in-JS，我们建议结合使用前两种方法（静态样式使用 CSS 文件，动态样式使用内联样式）。**我们不建议运行时注入 `<style>` 标签有两个原因：**
```suggestion
如果你使用 CSS-in-JS，我们建议结合使用前两种方法（静态样式使用 CSS 文件，动态样式使用内联样式）。**我们不建议运行时注入 `<style>` 标签有两个原因**：
```

2023-05-18 02:44 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +#### 这与渲染期间或 useLayoutEffect 中注入样式相比有何优势？ {/*how-is-this-better-than-injecting-styles-during-rendering-or-uselayouteffect*/}
```suggestion
#### 这与渲染期间或 `useLayoutEffect` 中注入样式相比有何优势？ {/*how-is-this-better-than-injecting-styles-during-rendering-or-uselayouteffect*/}
```

2023-05-18 02:44 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +如果你在渲染期间注入样式并且 React 正在处理[非阻塞更新](/reference/react/useTransition#marking-a-state-update-as-a-non-blocking-transition)，那么浏览器将在渲染组件树时每一帧都会重新计算样式，这可能会**非常慢**。
```suggestion
如果你在渲染期间注入样式并且 React 正在处理 [非阻塞更新](/reference/react/useTransition#marking-a-state-update-as-a-non-blocking-transition)，那么浏览器将在渲染组件树时每一帧都会重新计算样式，这可能会 **非常慢**。
```

2023-05-18 02:45 UTC, Yucohny commented
由于本篇文档主题原因，原文出现了大量 ”Effect“，而有的时候翻译为了”副作用“，有的时候保留了原文，因此除去 review 当中直接提及的，可以再多考虑本篇文档中对 ”Effect“ 的处理。

2023-05-18 06:53 UTC, NewVo1d commented
> 由于本篇文档主题原因，原文出现了大量 ”Effect“，而有的时候翻译为了”副作用“，有的时候保留了原文，因此除去 review 当中直接提及的，可以再多考虑本篇文档中对 ”Effect“ 的处理。

收到，辛苦校对

2023-05-21 10:54 UTC, NewVo1d commented
> 由于本篇文档主题原因，原文出现了大量 ”Effect“，而有的时候翻译为了”副作用“，有的时候保留了原文，因此除去 review 当中直接提及的，可以再多考虑本篇文档中对 ”Effect“ 的处理。

参考了 React 中文翻译指南 #2 后，我认为本文正文中出现的五次 Effect（包含 Effects）均应不翻译。

2023-05-21 10:55 UTC, NewVo1d commented
另外，对本文中部分用词进行了修改，辛苦再次校对。 @Yucohny

2023-05-26 07:38 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +* 你不能在 `useInsertionEffect` 内部更新 state。
```suggestion
* 避免在 `useInsertionEffect` 内部更新 state。
```

2023-05-26 07:38 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +* 你不能在 `useInsertionEffect` 内部更新 state。
这个地方虽然原文直译的意思就是“你不能”，但是使用“避免”会更加流畅一点。

2023-05-26 07:38 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +* 在 `useInsertionEffect` 运行期间，refs 还没有附加，DOM 也还没有更新。
```suggestion
* 在 `useInsertionEffect` 运行期间，ref 还没有附加，DOM 也还没有更新。
```

2023-05-26 07:38 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +* 在 `useInsertionEffect` 运行期间，refs 还没有附加，DOM 也还没有更新。
“附加”这个表达感觉有点点怪，有没有其他更合适的表达方式？

2023-05-26 07:38 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +[阅读更多将 `useInsertionEffect` 应用于带有运行时注入的 CSS-in-JS 库的相关信息](https://github.com/reactwg/react-18/discussions/110)
```suggestion
[阅读更多将 `useInsertionEffect` 应用于带有运行时注入的 CSS-in-JS 库的相关信息](https://github.com/reactwg/react-18/discussions/110)。
```

2023-05-26 07:38 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +#### 这与渲染期间或 `useLayoutEffect` 中注入样式相比有何优势？ {/*how-is-this-better-than-injecting-styles-during-rendering-or-uselayouteffect*/}
```suggestion
#### 这与在渲染期间或 `useLayoutEffect` 中注入样式相比有何优势？ {/*how-is-this-better-than-injecting-styles-during-rendering-or-uselayouteffect*/}
```

2023-05-26 07:38 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +#### 这与渲染期间或 `useLayoutEffect` 中注入样式相比有何优势？ {/*how-is-this-better-than-injecting-styles-during-rendering-or-uselayouteffect*/}
“这与渲染期间注入样式……”与“这与在渲染期间注入样式……”两者区别不大，但是“这与 `useLayoutEffect` 中……”与“这与在 `useLayoutEffect` 中……”两者的表达会有一些差别，故添加了一个“在”字。

2023-05-30 05:39 UTC, NewVo1d commented on src/content/reference/react/useInsertionEffect.md
> +* 在 `useInsertionEffect` 运行期间，refs 还没有附加，DOM 也还没有更新。
当初翻译的时候，考虑如下：
-  `ref` 如果用于计算值的时候，使用 **赋值** 比较合适；
- `ref` 如果用于 `DOM` 的时候，使用 **赋值** 感觉差点意思，故使用了 `attach` 的直译  **附加**；

暂未想到对 `attach` 更好的表达方式，但是 **赋值** 并无不妥之处。如同意，我会将其改为 **赋值**。

2023-05-30 13:39 UTC, loveloki commented on src/content/reference/react/useInsertionEffect.md
> +* **可选** `dependencies`：`setup` 代码中引用的所有响应式值的列表。响应式值包括 props、state 以及所有直接在组件内部声明的变量和函数。如果你的代码检查工具 [配置了 React](/learn/editor-setup#linting)，那么它将验证每个响应式值都被正确地指定为一个依赖项。依赖项列表必须具有固定数量的项，并且必须像 `[dep1, dep2
```suggestion
* **可选** `dependencies`：`setup` 代码中引用的所有响应式值的列表。响应式值包括 props、state 以及所有直接在组件内部声明的变量和函数。如果你的代码检查工具 [配置了 React](/learn/editor-setup#linting)，那么它将验证是否每个响应式值都被正确地指定为依赖项。依赖列表必须具有固定数量的项，并且必须像 `[dep1, dep2, dep3]` 这样内联编写。React 将使用 [`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) 来比较每个依赖项和它先前的值。如果省略此参数，则将在每次重新渲染组件之后重新运行 Effect。
```

2023-05-30 13:44 UTC, loveloki commented on src/content/reference/react/useInsertionEffect.md
> +2. 如果运行时注入发生在 React 生命周期的错误时间，它可能会非常慢。
```suggestion
2. 如果在 React 生命周期中某个错误的时机进行运行时注入，它可能会非常慢。
```

2023-05-30 13:46 UTC, loveloki commented on src/content/reference/react/useInsertionEffect.md
> +[阅读更多将 `useInsertionEffect` 应用于带有运行时注入的 CSS-in-JS 库的相关信息](https://github.com/reactwg/react-18/discussions/110)。
```suggestion
[阅读更多使用 `useInsertionEffect` 升级 CSS-in-JS 库的相关指南](https://github.com/reactwg/react-18/discussions/110)。
```

2023-05-30 13:47 UTC, loveloki commented on src/content/reference/react/useInsertionEffect.md
> +`useInsertionEffect` 是 [`useEffect`](/reference/react/useEffect) 的另一种实现，在任何 DOM 变化前触发。
```suggestion
`useInsertionEffect` 是 [`useEffect`](/reference/react/useEffect) 的另一种实现，会在任何 DOM 变化前触发。
```

2023-05-30 13:52 UTC, loveloki commented on src/content/reference/react/useInsertionEffect.md
> +* 在 `useInsertionEffect` 运行期间，refs 还没有附加，DOM 也还没有更新。
可以考虑加个因果关系？类似于：因为 DOM 还没有更新，所以 ref 还没有被赋值。

2023-06-09 06:51 UTC, Yucohny commented on src/content/reference/react/useInsertionEffect.md
> +* 在 `useInsertionEffect` 运行期间，refs 还没有附加，DOM 也还没有更新。
> 可以考虑加个因果关系？类似于：因为 DOM 还没有更新，所以 ref 还没有被赋值。

这个因果关系是确认的吗？

2023-06-16 06:16 UTC, loveloki requested changes

2023-06-16 06:16 UTC, loveloki commented on src/content/reference/react/useInsertionEffect.md
> +`useInsertionEffect` 比在 [`useLayoutEffect`](/reference/react/useLayoutEffect) 或 [`useEffect`](/reference/react/useEffect) 期间注入样式更好。因为它确保其他 Effect 在你的组件中运行时，`<style>` 标签已经被注入。否则，正常的 Effect 中的布局计算将由于过时
```suggestion
`useInsertionEffect` 比在 [`useLayoutEffect`](/reference/react/useLayoutEffect) 或 [`useEffect`](/reference/react/useEffect) 期间注入样式更好。因为它会确保`<style>` 标签在其它 Effect 运行前被注入。否则，正常的 Effect 中的布局计算将由于过时的样式而出错。
```

2023-06-16 06:21 UTC, loveloki approved these changes

2023-06-16 06:24 UTC, Yucohny approved these changes

2023-06-16 06:24 UTC, merged