docs(cn): translate reference/react-dom/client/index into Chinese
reactjs/zh-hans.react.dev pull request #1171
Opened 2023-05-17 11:18 UTC by neo-of-matrix

翻译 reference/react-dom/client/index

2023-05-27 12:36 UTC, hexiaokang approved these changes

2023-05-28 03:34 UTC, awxiaoxian2020 requested changes

2023-05-28 03:34 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/client/index.md
> +## 客户端 APIs {/*client-apis*/}
```suggestion
## 客户端 API {/*client-apis*/}
```

2023-05-28 03:34 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/client/index.md
> +React 支持所有流行的浏览器，包括 Internet Explorer 9 以及以上版本的浏览器。更旧的浏览器比如 IE9 和 IE10 需要使用 polyfills。
```suggestion
React 支持所有流行的浏览器，包括 Internet Explorer 9 以及以上版本的浏览器。更旧的浏览器比如 IE9 和 IE10 需要使用 polyfill。
```

2023-05-28 03:34 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/client/index.md
> +`react-dom/client` APIs 让你可以在客户端（浏览器）渲染 React 组件。这些 API 通常在你的应用的顶端初始化 React tree。一个 [框架](/learn/start-a-new-react-project#production-grade-react-frameworks) 可能会为你调用它们。你的大部分组件不需要导入和使用它们。
```suggestion
`react-dom/client` APIs 让你可以在客户端（浏览器）渲染 React 组件。这些 API 通常在你的应用的顶端初始化 React 树。一个 [框架](/learn/start-a-new-react-project#production-grade-react-frameworks) 可能会为你调用它们。你的大部分组件不需要导入和使用它们。
```

2023-06-19 10:11 UTC, Yucohny commented on src/content/reference/react-dom/client/index.md
> +`react-dom/client` APIs 让你可以在客户端（浏览器）渲染 React 组件。这些 API 通常在你的应用的顶端初始化 React 树。一个 [框架](/learn/start-a-new-react-project#production-grade-react-frameworks) 可能会为你调用它们。你的大部分组件不需要导入和使用它们。
```suggestion
`react-dom/client` API 让你可以在客户端（浏览器）渲染 React 组件。这些 API 通常在你的应用的顶端初始化 React 树。一个 [框架](/learn/start-a-new-react-project#production-grade-react-frameworks) 可能会为你调用它们。你的大部分组件不需要导入和使用它们。
```

2023-06-21 12:27 UTC, merged