docs(cn): translate learn/lifecycle-of-reactive-effects into Chinese
reactjs/zh-hans.react.dev pull request #1178
Opened 2023-05-23 07:59 UTC by GarlicGo

learn/lifecycle-of-reactive-effects 已翻译完成，辛苦review
@QC-L @Yucohny @awxiaoxian2020

2023-06-19 12:04 UTC, Yucohny commented on src/content/learn/lifecycle-of-reactive-effects.md
> +有些 Effect 根本不返回清理函数。[在大多数情况下](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)，你可能希望返回一个清理函数，但如果没有返回，React将表现得好像你返回了一个空的清理函数。
注意空格。

2023-06-19 12:04 UTC, Yucohny commented on src/content/learn/lifecycle-of-reactive-effects.md
> +想象一下，这个 `ChatRoom` 组件接收一个 `roomId` 属性，用户可以在下拉菜单中选择。假设初始时，用户选择了 `"所有"` 作为 `roomId`。你的应用程序会显示 `"所有"` 聊天室：
此问题出现较多，烦请自查。

2023-06-19 12:04 UTC, Yucohny commented on src/content/learn/lifecycle-of-reactive-effects.md
> +之后，用户在下拉菜单中选择了不同的房间（例如 `"旅游"`）。首先，React会更新 UI：
空格

2023-06-19 12:04 UTC, Yucohny commented on src/content/learn/lifecycle-of-reactive-effects.md
> +思考接下来应该发生什么。用户在界面中看到 `"旅游"` 是当前选定的聊天室。然而，上次运行的 Effect 仍然连接到 `"所有"` 聊天室。**`roomId` 属性已经发生了变化，所以之前 Effect 所做的事情（连接到 `"所有"` 聊天室）不再与 UI 匹配。**
句末标点移至加粗外。

2023-06-20 03:48 UTC, adntin commented on src/content/learn/lifecycle-of-reactive-effects.md
> +## 响应式 Effect 的生命周期 {/*the-lifecycle-of-an-effect*/}
Effect 的生命周期

2023-06-20 03:54 UTC, Yucohny commented on src/content/learn/lifecycle-of-reactive-effects.md
> +## 响应式 Effect 的生命周期 {/*the-lifecycle-of-an-effect*/}
对，此处不应该出现“响应式”。 @GarlicGo

2023-06-21 15:15 UTC, GarlicGo commented on src/content/learn/lifecycle-of-reactive-effects.md
> +## 响应式 Effect 的生命周期 {/*the-lifecycle-of-an-effect*/}
谢谢提醒，已改正

2023-06-23 06:17 UTC, GarlicGo commented on src/content/learn/lifecycle-of-reactive-effects.md
> +想象一下，这个 `ChatRoom` 组件接收一个 `roomId` 属性，用户可以在下拉菜单中选择。假设初始时，用户选择了 `"所有"` 作为 `roomId`。你的应用程序会显示 `"所有"` 聊天室：
> 此问题出现较多，烦请自查。

此问题已经完成自查并更改，修改内容为将行内的"所有"、"旅游"、"音乐"由中文改回了原文的英文状态，并在使用到它们作为值的地方（option中的value）以及相关代码注释也从中文改回了英文状态，但是option标签对中的内容仍保留了中文的翻译状态。这样可以不。

2023-06-23 10:18 UTC, Yucohny commented on src/content/learn/lifecycle-of-reactive-effects.md
> +但是想象一下，如果以后你给这个 Effect 添加了另一个需要重新建立连接的依赖项。如果这个 Effect 重新进行同步，它将为相同的房间调用 `logVisit(roomId)`，而这不是你的意图。记录访问行为是 **一个独立的过程**，与连接不同。将它们作为两个单独的 Effects 编写：
使用 Effect 而非 Effects。

2023-06-26 14:43 UTC, yionr requested changes

2023-06-26 14:43 UTC, yionr commented on src/content/learn/lifecycle-of-reactive-effects.md
> +另一方面，`roomId` 在重新渲染时可能会不同。**在组件内部声明的 props、state 和其他值都是 _响应式_ 的，因为它们是在渲染过程中计算的，并参与了 React 的数据流。**
这里的 “响应式” 依然是斜体，不符合中文排版规则

2023-06-26 14:43 UTC, yionr commented on src/content/learn/lifecycle-of-reactive-effects.md
> +或者，你可以将*事件订阅*的逻辑包裹在 `if (canMove) { ... }` 条件语句中：
这里的 “事件订阅” 依然是斜体，不符合中文排版规则

2023-06-26 14:43 UTC, yionr commented on src/content/learn/lifecycle-of-reactive-effects.md
> +你可以将 Effect 的依赖项更改为 `[handleMove]`，但由于它在每次渲染时都会被重新定义，你也可以完全删除依赖项数组。然后，Effect 将在*每次重新渲染后重新同步*：
这里的“每次重新渲染后重新同步”同理，也是斜体的，不符合中文排版规则

2023-06-26 14:43 UTC, yionr commented on src/content/learn/lifecycle-of-reactive-effects.md
> +更好的解决方案是将 `handleMove` 函数*移动到* Effect 内部。然后，`handleMove` 就不会成为一个响应式值，因此你的 Effect 不会依赖于一个函数。相反，它将依赖于你的代码从 Effect 内部读取的 `canMove`。这符合你想要的行为，因为你的 Effect 现在将始终与 `canMove` 的值保持同步：
这里的“移动到”也是斜体。

2023-06-26 14:43 UTC, yionr commented on src/content/learn/lifecycle-of-reactive-effects.md
> +请注意，最初控制台日志显示连接未加密。尝试切换复选框：不会发生任何变化。然而，如果在此之后更改所选的聊天室，那么聊天将重新连接 *并且* 启用加密（从控制台日志中可以看到）。这是一个错误。修复这个错误，以便切换复选框 *也* 会使重新连接聊天室。
这句话中的“并且”、“也”为斜体，不符合中文排版规范哦

2023-06-26 14:43 UTC, yionr commented on src/content/learn/lifecycle-of-reactive-effects.md
> +**如果从不禁止 linter，就不会遇到过时值的问题。**解决这个 bug 有几种不同的方法，但你应该始终从移除 linter 禁止开始。然后修改代码来修复 lint 错误。
这个地方应该把句号移到 md 标记外面，因为页面渲染后出现了转换问题：
![](https://github.com/reactjs/zh-hans.react.dev/assets/30925732/fb6ae868-165b-4bc9-8d40-db2196a4d1e1)

中文排版规范中对此也有说明的：

> 超链接与加粗文本 末尾 的标点符号无论原文如何，一律移至超链接外。

2023-06-27 13:05 UTC, yionr approved these changes

2023-06-28 06:28 UTC, Yucohny commented
参考上次提交，请再自查相关表达与格式问题。

2023-06-29 23:29 UTC, GarlicGo commented
> 参考上次提交，请再自查相关表达与格式问题。

好的👌

2023-07-05 13:27 UTC, GarlicGo commented
@Yucohny 已修改，辛苦再看一下可不可以

2023-07-06 03:55 UTC, merged