docs(cn): update learn/responding-to-events translate
reactjs/zh-hans.react.dev pull request #1184
Opened 2023-05-30 02:35 UTC by Brucia323

更新 响应事件 翻译

2023-06-19 12:00 UTC, Yucohny commented
请参照相关说明修改 PR title。

2023-06-20 01:10 UTC, Yucohny commented
请参阅 [更新流程](https://github.com/reactjs/zh-hans.react.dev/issues/603) 进行相关调整。

2023-07-03 13:05 UTC, awxiaoxian2020 requested changes

2023-07-03 13:08 UTC, awxiaoxian2020 commented on src/content/learn/responding-to-events.md
> +确保为事件处理程序使用适当的 HTML 标签。例如，要处理点击事件，请使用 [`<button onClick={handleClick}>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/button) 而不是 `<div onClick={handleClick}>`。使用真正的浏览器 `<button>` 启用内置的浏
```suggestion
确保为事件处理程序使用适当的 HTML 标签。例如，要处理点击事件，请使用 [`<button onClick={handleClick}>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/button) 而不是 `<div onClick={handleClick}>`。使用真正的浏览器 `<button>` 启用内置的浏览器行为，如键盘导航。 如果你不喜欢按钮的默认浏览器样式，并且想让它看起来更像一个链接或不同的 UI 元素，您可以使用 CSS 来实现。[了解有关编写无障碍标签的更多信息。](https://developer.mozilla.org/zh-CN/docs/Learn/Accessibility/HTML)
```

2023-07-03 16:55 UTC, Yucohny commented on src/content/learn/responding-to-events.md
> +确保为事件处理程序使用适当的 HTML 标签。例如，要处理点击事件，请使用 [`<button onClick={handleClick}>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/button) 而不是 `<div onClick={handleClick}>`。使用真正的浏览器 `<button>` 启用内置的浏
```suggestion
确保为事件处理程序使用适当的 HTML 标签。例如，要处理点击事件，请使用 [`<button onClick={handleClick}>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/button) 而不是 `<div onClick={handleClick}>`。使用真正的浏览器 `<button>` 启用内置的浏览器行为，如键盘导航。如果你不喜欢按钮的默认浏览器样式，并且想让它看起来更像一个链接或不同的 UI 元素，你可以使用 CSS 来实现。[了解有关编写无障碍标签的更多信息](https://developer.mozilla.org/zh-CN/docs/Learn/Accessibility/HTML)。
```

2023-07-03 16:56 UTC, merged