translate Tag.tsx
reactjs/zh-hans.react.dev pull request #1185
Opened 2023-05-30 02:48 UTC by Brucia323

翻译 Tag.tsx

2023-06-16 00:58 UTC, awxiaoxian2020 requested changes

2023-06-16 00:58 UTC, awxiaoxian2020 commented on src/components/Tag.tsx
> +    name: '实验',
```suggestion
    name: '实验性的',
```

2023-06-16 01:26 UTC, Brucia323 commented on src/components/Tag.tsx
> +    name: '实验',
我翻译的时候想保持统一的长度，如果不需要，`弃用` 是否改成 `已弃用`？

2023-06-19 09:46 UTC, Yucohny commented
请对照规范更改 PR title

2023-06-19 09:47 UTC, Yucohny commented on src/components/Tag.tsx
> +    name: '实验',
不必保证长度一致

2023-06-28 12:20 UTC, merged