docs(cn): translate /reference/react/StrictMode into Chinese
reactjs/zh-hans.react.dev pull request #1186
Opened 2023-05-30 02:57 UTC by NewVo1d

translate /reference/react/StrictMode 已翻译完成，辛苦review
@QC-L @Yucohny @awxiaoxian2020

2023-06-05 05:45 UTC, awxiaoxian2020 commented on src/content/reference/react/StrictMode.md
> +如果要为整个应用启用严格模式，请在渲染根组件时使用 `<StrictMode>` 包裹它：
```suggestion

如果要为整个应用启用严格模式，请在渲染根组件时使用 `<StrictMode>` 包裹它：
```

2023-06-05 05:58 UTC, awxiaoxian2020 requested changes

2023-06-05 05:58 UTC, awxiaoxian2020 commented on src/content/reference/react/StrictMode.md
> +- 传递给 [`useState`](/reference/react/useState)、[`set 函数`](/reference/react/useState#setstate)、[`useMemo`](/reference/react/useMemo) 或 [`useReducer`](/reference/react/useReducer) 的函数。
```suggestion
- 传递给 [`useState`](/reference/react/useState)、[`set` 函数](/reference/react/useState#setstate)、[`useMemo`](/reference/react/useMemo) 或 [`useReducer`](/reference/react/useReducer) 的函数。
```

2023-06-19 15:04 UTC, loveloki submitted a review, later dismissed

2023-06-19 16:28 UTC, Yucohny approved these changes

2023-06-20 00:29 UTC, loveloki approved these changes

2023-06-20 00:45 UTC, merged