Kcw translate
reactjs/zh-hans.react.dev pull request #1187
Opened 2023-06-01 06:28 UTC by kecanwen

2023-06-01 11:19 UTC, awxiaoxian2020 commented
The PR has many extra files.

2023-06-02 03:04 UTC, kecanwen commented
> The PR has many extra files.



> The PR has many extra files.

sorry ,I commit some .idea files

2023-06-02 03:08 UTC, kecanwen commented
> The PR has many extra files.

@awxiaoxian2020 done

2023-06-03 05:35 UTC, awxiaoxian2020 requested changes
请保持行行对应

2023-06-05 02:53 UTC, kecanwen commented
> 请保持行行对应

done

2023-06-05 03:28 UTC, awxiaoxian2020 commented
请查看右上角新增行数和删减行数进行核对，它们应该一致。

2023-06-05 06:56 UTC, kecanwen commented
> 请查看右上角新增行数和删减行数进行核对，它们应该一致。

done  辛苦CR

2023-06-05 07:11 UTC, awxiaoxian2020 requested changes
句号和汉字之间的空格去掉

2023-06-05 08:15 UTC, kecanwen commented
> 句号和汉字之间的空格去掉

done 辛苦CR

2023-06-06 01:09 UTC, kecanwen commented
> > 句号和汉字之间的空格去掉
> 
> done 辛苦CR

@awxiaoxian2020

2023-06-23 11:30 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +title: "常见组件 (例如 <div>)"
```suggestion
title: "常见组件（例如 <div>)"

```

2023-06-23 11:30 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +<div className="wrapper">Some content</div>
需要翻译代码中的“内容”。

2023-06-23 11:30 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +[查看更多用例](#usage)
标点缺失。

2023-06-23 11:30 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +* `children`: 一个 React 节点 (可以是元素, 字符串, 数字, [portal,](/reference/react-dom/createPortal) 空节点（ 如`null`, `undefined`） 和 布尔值, 或其他 React 数组节点)。指定组件内部的内容. 当你使用JSX时, 通常会通过嵌套标签 `<div><span /></div>` 隐式地指定 `c
请对照翻译规范自行审视调整。

2023-07-03 02:18 UTC, symant233 commented on src/content/reference/react-dom/components/common.md
> +* [`on aimationEnd`](https://developer.mozilla.org/en-US/docs/Web/API/Element/animationend_event): 一个 [`动画事件`处理](#动画事件-handler)函数。在CSS动画完成时触发。
`onAnimationEnd`
之后几行也有这个错误

2023-07-03 02:33 UTC, symant233 commented on src/content/reference/react-dom/components/common.md
> +* [`itemProp`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemprop): 一个字符串。指定元素代表的属性，供结构化数据爬取程序使用
标点缺失：结束句号。

2023-07-03 02:33 UTC, symant233 commented on src/content/reference/react-dom/components/common.md
> +* `on aimationStartCapture`: 跟`on 一个imationStart`一样, 但是是在 [捕获阶段.](/learn/responding-to-events#capture-phase-events)触发。
还有几处这种问题：
```suggestion
* `onAnimationStartCapture`: 跟`onAnimationStart`一样, 但是是在[捕获阶段](/learn/responding-to-events#capture-phase-events)触发。

```

2023-07-03 09:57 UTC, Yucohny commented
@kecanwen 请注意，在 review & comment 后如果长时间未进行更新，将会关闭此 PR。

2023-07-05 02:05 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> +title: "常见组件 (例如 <div>)"
done

2023-07-05 02:16 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> +<div className="wrapper">Some content</div>
done

2023-07-05 02:33 UTC, kecanwen commented
> @kecanwen 请注意，在 review & comment 后如果长时间未进行更新，将会关闭此 PR。

done

2023-07-05 06:54 UTC, Yucohny reviewed
请注意，此篇仍然存在 **大量** 格式问题。同时，请保持之前调整过的 MDN 中文站点。

2023-07-05 06:54 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +ß
这里是怎么回事？

2023-07-05 06:54 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +* [`is`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/is): 一个字符串。如果指定，该组件将表现得像一个[自定义元素](/reference/react-dom/components#custom-html-elements)。
请使用全角冒号。

2023-07-05 06:54 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +* `onBeforeInputCapture`: 一个在[捕获阶段.](/learn/responding-to-events#capture-phase-events)触发的 `onBeforeInput` 版本。
意外的格式问题。

2023-07-06 07:04 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> +ß
这块问题是什么呢  没有理解

2023-07-06 07:20 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +ß
28行出现特殊符号

2023-07-06 07:32 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> +ß
done

2023-07-07 03:55 UTC, Yucohny reviewed
请注意，此篇翻译存在 **大量** 格式问题，请自查。同时，请保留 MDN 的中文站点链接。

2023-07-07 03:55 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +* `onClickCapture`：在[捕获阶段.](/learn/responding-to-events#capture-phase-events)触发的 `onClick` 版本。
意外的格式问题。

2023-07-07 03:55 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +* `onBlurCapture`：在 [捕获阶段.](/learn/responding-to-events#capture-phase-events)触发的`onBlur`版本。
意外的格式问题。

2023-07-07 03:55 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +* [`onAimationStart`](https://developer.mozilla.org/en-US/docs/Web/API/Element/animationstart_event)：一个 [`动画事件`处理](#动画事件-handler)函数。当 CSS 动画开始时触发。
```suggestion
* [`onAimationStart`](https://developer.mozilla.org/en-US/docs/Web/API/Element/animationstart_event)：一个 [`动画事件`处理](#animationevent-handler)函数。当 CSS 动画开始时触发。

```

2023-07-10 01:03 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +* `onClickCapture`：在[捕获阶段.](/learn/responding-to-events#capture-phase-events)触发的 `onClick` 版本。
[译文规范](https://github.com/reactjs/zh-hans.react.dev/wiki/React-Translation-Guide)。

2023-07-10 01:05 UTC, Yucohny commented
请对照 [译文规范](https://github.com/reactjs/zh-hans.react.dev/wiki/React-Translation-Guide) 自查格式问题。

2023-07-13 10:09 UTC, Yucohny commented
请注意及时更新~

2023-07-14 06:55 UTC, kecanwen commented
> 请注意及时更新~

done

2023-07-14 09:05 UTC, awxiaoxian2020 requested changes

2023-07-14 09:05 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +        onClick={e => console.log('点击（按钮二）')}
这种地方不建议翻译

2023-07-14 12:32 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> +        onClick={e => console.log('点击（按钮二）')}
done

2023-07-19 08:35 UTC, awxiaoxian2020 submitted a review, later dismissed

2023-07-19 12:48 UTC, Yucohny reviewed
此篇翻译存在较多格式问题，烦请自查。

2023-07-19 12:48 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +title："常见组件（例如 <div>)"
```suggestion
title："常见组件（例如 <div>）"

```

2023-07-19 12:48 UTC, Yucohny commented on src/content/reference/react-dom/components/common.md
> +### 通用组件 (例如 `<div>`) {/*common*/}
```suggestion
### 通用组件（例如 `<div>`） {/*common*/}
```

2023-07-25 00:10 UTC, awxiaoxian2020 requested changes

2023-07-25 00:10 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `onPointerMoveCapture`:一个在捕获阶段[捕获阶段](/learn/responding-to-events#capture-phase-events)触发的 `onPointerMove` 版本。
这里少了一行

2023-07-25 03:19 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> +* `onPointerMoveCapture`:一个在捕获阶段[捕获阶段](/learn/responding-to-events#capture-phase-events)触发的 `onPointerMove` 版本。
* [`onCancel`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLDialogElement/cancel_event): An [`Event` handler](#event-handler) function. Fires when the user tries to dismiss the dialog.
* `onCancelCapture`: A version of `onCancel` that fires in the [capture phase.](/learn/responding-to-events#capture-phase-events)
capture-phase-events)
* [`onClose`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLDialogElement/close_event): An [`Event` handler](#event-handler) function. Fires when a dialog has been closed.
* `onCloseCapture`: A version of `onClose` that fires in the [capture phase.](/learn/responding-to-events#capture-phase-events)
原文 172行好像有点问题

2023-07-25 03:21 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> +* `onPointerMoveCapture`:一个在捕获阶段[捕获阶段](/learn/responding-to-events#capture-phase-events)触发的 `onPointerMove` 版本。
我已经在译文中删除了172行。现在译文全文1183行。原文1184行

2023-07-25 03:47 UTC, awxiaoxian2020 requested changes

2023-07-25 03:47 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +title："常见组件（例如 <div>）"
```suggestion
title: "常见组件（例如 <div>）"
```
元信息的冒号不要改动

2023-07-25 03:49 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `onPointerMoveCapture`:一个在捕获阶段[捕获阶段](/learn/responding-to-events#capture-phase-events)触发的 `onPointerMove` 版本。
请以空行方式保证行行对应。我稍后去看看原文的情况。

2023-07-25 03:51 UTC, awxiaoxian2020 requested changes

2023-07-25 03:51 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* [`onClose`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLDialogElement/close_event)：一个 [`Event` 处理](#event-handler) 函数。当对话框已关闭时触发。
```suggestion

* [`onClose`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLDialogElement/close_event)：一个 [`Event` 处理](#event-handler) 函数。当对话框已关闭时触发。
```

2023-07-25 03:55 UTC, awxiaoxian2020 requested changes

2023-07-25 03:55 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `onAbortCapture`：一个在捕获阶段[捕获阶段](/learn/responding-to-events#capture-phase-events)触发的 `onAbort` 版本。
“捕获阶段”翻译有问题

2023-07-25 04:08 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `onPointerMoveCapture`:一个在捕获阶段[捕获阶段](/learn/responding-to-events#capture-phase-events)触发的 `onPointerMove` 版本。
https://github.com/reactjs/react.dev/pull/6167 3 小时前这个 PR 修复了这个问题。为了避免后续冲突，我们等待明天早上仓库同步后处理冲突~

2023-07-25 06:20 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +title："常见组件（例如 <div>）"
```suggestion
title: "普通组件（例如 <div>）"
```

2023-07-26 00:03 UTC, awxiaoxian2020 commented
请处理冲突，并保持行行对应。

2023-07-26 01:42 UTC, Yucohny commented
@kecanwen 文件冲突似乎仍然存在，请自行处理。

2023-07-26 02:37 UTC, kecanwen commented
> @kecanwen 文件冲突似乎仍然存在，请自行处理。

done

2023-07-28 11:48 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `dangerouslySetInnerHTML`：一个形如 `{ __html：'<p>一些 HTML</p>' }` 的对象，其中包含原始的 HTML 字符串。覆盖 DOM 节点的 [`innerHTML`](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/innerHTML) 属性 ，并在内部显示传递的 HTML 内容。
```suggestion
* `dangerouslySetInnerHTML`：一个形如 `{ __html: '<p>一些 HTML</p>' }` 的对象，其中包含原始的 HTML 字符串。覆盖 DOM 节点的 [`innerHTML`](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/innerHTML) 属性 ，并在内部显示传递的 HTML 内容。这个属性应该极度谨慎使用! 如果内部的 HTML 不可信（例如，如果它基于用户数据），你有引入 [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting) 漏洞的风险。[阅读更多关于使用`dangerouslySetInnerHTML`的内容](#dangerously-setting-the-inner-html)。

```

2023-07-28 11:48 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `ref`：来自 [`useRef`](/reference/react/useRef) 或者 [`createRef`](/reference/react/createRef)的 ref 对象，或者一个 [`ref` 回调函数](#ref-callback)。 或者一个用于 [传统 refs](https://reactjs.org/docs/refs-and-the-dom.html#l
```suggestion
* `ref`：来自 [`useRef`](/reference/react/useRef) 或者 [`createRef`](/reference/react/createRef)的 ref 对象，或者一个 [`ref` 回调函数](#ref-callback)。 或者一个用于 [传统 refs](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) 的字符串，你的引用将被填充为此节点的 DOM 元素。[阅读更多关于使用 ref 操纵 DOM 的内容](#manipulating-a-dom-node-with-a-ref)。

```

2023-07-28 11:49 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `onBlur`：一个[`聚焦事件` 处理](#focusevent-handler) 函数。当元素失去焦点时触发。与内置的浏览器 [`blur`](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/blur_event) 不同，在 React 中，`onBlur` 事件会冒泡。
```suggestion
* `onBlur`：一个 [`聚焦事件` 处理](#focusevent-handler) 函数。当元素失去焦点时触发。与内置的浏览器 [`blur`](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/blur_event) 不同，在 React 中，`onBlur` 事件会冒泡。

```

2023-07-28 11:49 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `onBlurCapture`：在 [捕获阶段](/learn/responding-to-events#capture-phase-events)触发的`onBlur`版本。
```suggestion
* `onBlurCapture`：在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发的`onBlur`版本。

```

2023-07-28 11:51 UTC, awxiaoxian2020 requested changes

2023-07-28 11:51 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `onSeekedCapture`：一个在捕获阶段[捕获阶段](/learn/responding-to-events#capture-phase-events)触发的 `onSeeked` 版本。
这里的重复仍未解决

2023-07-31 02:22 UTC, awxiaoxian2020 requested changes

2023-07-31 02:22 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* [`onAimationEnd`](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/animationend_event)：一个 [`动画事件`处理](#animationevent-handler) 函数。在 CSS 动画完成时触发。
相关单词拼写错误

2023-07-31 03:36 UTC, awxiaoxian2020 requested changes

2023-07-31 03:36 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +阅读更多关于 [使用 refs 操纵 DOM](/learn/manipulating-the-dom-with-refs) 的内容并 [查看更多示例](/reference/react/useRef#examples-dom)。
```suggestion
阅读更多关于 [使用 ref 操纵 DOM](/learn/manipulating-the-dom-with-refs) 的内容并 [查看更多示例](/reference/react/useRef#examples-dom)。

```

2023-07-31 03:36 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* [`aria-*`](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA/Attributes)：ARIA 属性允许你为此元素指定辅助功能树信息。请参阅 [ARIA属性](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA/Attribute
```suggestion
* [`aria-*`](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA/Attributes)：ARIA 属性允许你为此元素指定辅助功能树信息。请参阅 [ARIA 属性](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA/Attributes) 以获取完整的参考。在 React 中，所有 ARIA 属性名称与 HTML 中完全相同。

```

2023-07-31 03:36 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +    <div className={cn('row',{
格式不要变动（空格），一并检查其他代码块

2023-08-01 02:51 UTC, awxiaoxian2020 requested changes

2023-08-01 02:51 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +    <input ref={inputRef} />)}
这里仍然有问题，请自查

2023-08-01 14:52 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +  const [postContent , setPostContent] = useState('你好，_ **Markdown**!');
```suggestion
  const [postContent, setPostContent] = useState('你好，_ **Markdown**!');

```

2023-08-01 14:54 UTC, awxiaoxian2020 requested changes

2023-08-01 14:54 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +* `e`:一个没有 额外属性](#react-event-object) 的 React 事件对象。
这个地方处理一下

2023-08-01 15:33 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> +* `children`：一个 React 节点 (可以是元素，字符串，数字，[portal](/reference/react-dom/createPortal) ，空节点（ 如 `null`，`undefined`） 和布尔值，或其他 React 数组节点)。指定组件内部的内容。当你使用 JSX 时，通常会通过嵌套标签 `<div><span /></div>` 隐式地指定 `childre
这里括号嵌套括号有点奇怪，再优化下表达吧。

2023-08-01 15:33 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> +  on animationEnd={e => console.log('on animationEnd')}
这里有问题。`onAnimationStart`不能拆成`on animationStart`

2023-08-01 15:33 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> +一个用于 [输入法编辑器（IME）](https://developer.mozilla.org/zh-CN/docs/Glossary/Input_method_editor) 事件的事件处理程序类型。
**事件的事件**读起来也很奇怪，可以考虑去掉一个事件

2023-08-01 15:33 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> + 一个 [HTML_Drag_and_Drop_API](https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_Drag_and_Drop_API) 事件的一个事件处理程序类型。
这里的 `HTML_Drag_and_Drop_API`？

2023-08-01 15:33 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> +一个用于 CSS 过渡事件的事件处理程序类型。
这里也是两个事件，读起来比较别扭，文章其它类似的地方也一起修改一下吧

2023-08-01 15:33 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> +在上述例子中，`style={{}}` 不是一个特殊的语法， 而是将 `style={ }` [JSX curly braces.](/learn/javascript-in-jsx-with-curly-braces) 放在一个普通 `{}`里。我们建议只在样式依赖于 JavaScript 变量时使用 `style` 属性。
`JSX curly braces` 看起来应该翻译一下

2023-08-01 15:41 UTC, loveloki commented
另外，这个文件不太对，每一行都有修改。

我看了下，应该是换行符从 `LF` 改成了 `CRLF`，要么新创建个分支，把目前需要修改的改一下重新提交 mr，不想切新分支的话把这个文件的换行符全部换回去也可以。但是不能出现修改换行符的行为，这样没有办法进行合理的对比。

注意一下你的 git 对于换行符的设置（可能是 `core.autocrlf`），一般来说随便修改文件的换行符是错误的行为。

2023-08-01 15:42 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> + 一个 [HTML_Drag_and_Drop_API](https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_Drag_and_Drop_API) 事件的一个事件处理程序类型。
是的 可以参考原文

2023-08-01 15:46 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> + 一个 [HTML_Drag_and_Drop_API](https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_Drag_and_Drop_API) 事件的一个事件处理程序类型。
不好意思我没有表达清楚。我的意思是原文没有下划线，这里添上了。可以考虑修改为类似于 **[HTML Drag 和 Drop API]** 这样。

2023-08-01 15:47 UTC, kecanwen commented on src/content/reference/react-dom/components/common.md
> + 一个 [HTML_Drag_and_Drop_API](https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_Drag_and_Drop_API) 事件的一个事件处理程序类型。
好的

2023-08-01 22:05 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +这些事件会触发在 [`<img>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/img)，[`<iframe>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/iframe)，[`<object>`](https://developer.mozilla
```suggestion
这些事件会触发在 [`<img>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/img)、[`<iframe>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/iframe)，[`<object>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/object)，[`<embed>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/embed)，[`<link>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/link)，和 [SVG `<image>`](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/SVG_Image_Tag) 元素。与浏览器事件不同，React 中的事件会冒泡：

```

2023-08-01 23:12 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> +一个用于 [CSS 动画](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Animations/Using_CSS_animations) 事件的事件处理程序类型。
```suggestion
一个用于 [CSS 动画](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Animations/Using_CSS_animations) 的事件处理程序类型。
```

2023-08-01 23:12 UTC, loveloki commented on src/content/reference/react-dom/components/common.md
> +一个用于鼠标事件的事件处理程序类型。
**处理程序类型**里面的 **类型** 是不需要的，**处理程序** 也和标题使用的翻译不同，建议保持一致。

可以考虑如下翻译：

**鼠标事件处理函数。**

或

**用于鼠标事件的处理函数。**


全文很多地方都有这种翻译，一起改下吧。

2023-08-02 01:33 UTC, awxiaoxian2020 requested changes

2023-08-02 01:33 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/common.md
> +
这个地方多余的空行又回来了，检查你的编辑器配置是否有问题

2023-08-03 00:25 UTC, awxiaoxian2020 approved these changes
LGTM! Welcome aboard! :tada:

2023-08-03 00:25 UTC, merged