add reference/react-dom/components/index
reactjs/zh-hans.react.dev pull request #1188
Opened 2023-06-01 12:49 UTC by taosimjoan

2023-06-01 13:04 UTC, taosimjoan reviewed
翻译 react-dom/components/index

2023-06-03 05:30 UTC, awxiaoxian2020 requested changes
请仔细阅读 wiki 中的翻译指南

2023-06-29 07:39 UTC, Yucohny commented
请注意，在 review 后长时间未针对评论指出的问题进行更新，将会关闭此 PR。

2023-07-03 04:53 UTC, awxiaoxian2020 commented
因长时间没有回应，暂时关闭此 PR。感谢你的贡献！

2023-07-03 04:53 UTC, closed without merging