docs(cn):translate reference/react/useReducer into Chinese
reactjs/zh-hans.react.dev pull request #1189
Opened 2023-06-02 02:46 UTC by exposir

reference/react/useReducer 辛苦CR

2023-06-03 05:24 UTC, awxiaoxian2020 commented on src/content/reference/react/useReducer.md
> +接下来，你需要编写计算并返回下一个状态的代码。按照惯例，我们通常会使用 [`switch` 语句](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/switch) 来进行编写。对于 `switch` 中的每个 `case`，都需要计算并返回某个下一个状态。
```suggestion

接下来，你需要编写计算并返回下一个状态的代码。按照惯例，我们通常会使用 [`switch` 语句](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/switch) 来进行编写。对于 `switch` 中的每个 `case`，都需要计算并返回某个下一个状态。
```

2023-06-03 05:26 UTC, awxiaoxian2020 requested changes

2023-06-03 05:26 UTC, awxiaoxian2020 commented on src/content/reference/react/useReducer.md
> +接下来，你需要编写计算并返回下一个状态的代码。按照惯例，我们通常会使用 [`switch` 语句](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/switch) 来进行编写。对于 `switch` 中的每个 `case`，都需要计算并返回某个下一个状态。
请保持行行对应

2023-06-29 07:40 UTC, Yucohny commented
存在较多格式问题，请对照翻译规范自查。

2023-06-29 07:40 UTC, Yucohny commented
请注意，在 review 后长时间未针对评论指出的问题进行更新，将会关闭此 PR。

2023-07-04 10:37 UTC, Yucohny commented
因原译者长时间未更新，故关闭此 PR。

2023-07-04 10:37 UTC, closed without merging