docs(cn): translate reference/react-dom/components/textarea into Chinese
reactjs/zh-hans.react.dev pull request #1201
Opened 2023-06-20 22:36 UTC by Yucohny

翻译 reference/react-dom/components/select

2023-06-21 01:15 UTC, awxiaoxian2020 requested changes

2023-06-21 01:15 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/textarea.md
> +    	写下你的贴子
```suggestion
 写下你的贴子
```

2023-06-21 01:15 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/textarea.md
> +**如果要渲染一个受控选择框，请传递 `value` 属性。**React 将强制传递 `value` 属性给文本框。通常，你可以通过声明一个 [state](/reference/react/useState) 来控制文本框：
```suggestion
**如果要渲染一个受控选择框，请传递 `value` 属性**。React 将强制传递 `value` 属性给文本框。通常，你可以通过声明一个 [state](/reference/react/useState) 来控制文本框：
```

2023-06-21 01:15 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/textarea.md
> +### 当我输入时，文本区域没有更新 {/*my-text-area-doesnt-update-when-i-type-into-it*/}
```suggestion
### 输入时文本框没有更新 {/*my-text-area-doesnt-update-when-i-type-into-it*/}
```

2023-06-21 01:17 UTC, Yucohny commented on src/content/reference/react-dom/components/textarea.md
> +    	写下你的贴子
没太看懂这个地方是什么改动？

2023-06-21 01:42 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/components/textarea.md
> +    	写下你的贴子
缩进保持统一，只有文字改动较好。在网页上我也不好操作，请在本地IDE对照修改。

2023-06-21 01:48 UTC, Yucohny commented on src/content/reference/react-dom/components/textarea.md
> +    	写下你的贴子
呃，我记得是缩进是统一的

2023-06-23 07:40 UTC, loveloki requested changes

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +* `onChangeCapture`：与 `onChange` 类似，但是是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```suggestion
* `onChangeCapture`：与 `onChange` 类似，但是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +* [`onInput`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/input_event)：一个 [`Event` 处理函数](/reference/react-dom/components/common#event-handler)。在用户更改值时立即触发。由于历史原因，在 React 习惯于使用 `onCha
```suggestion
* [`onInput`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/input_event)：一个 [`Event` 处理函数](/reference/react-dom/components/common#event-handler)。在用户更改值时立即触发。由于历史原因，在 React 习惯于使用工作方式类似的 `onChange`。
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +* `onInputCapture`：与 `onInput` 类似，但是是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```suggestion
* `onInputCapture`：与 `onInput` 类似，但是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +* `onInvalidCapture`：与 `onInvalid` 类似，但是是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```suggestion
* `onInvalidCapture`：与 `onInvalid` 类似，但是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +* `onSelectCapture`: 与 `onSelect` 类似，但是是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```suggestion
* `onSelectCapture`: 与 `onSelect` 类似，但是在 [捕获阶段](/learn/responding-to-events#capture-phase-events) 触发。
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +如果无法将 `<textarea>` 放置在 `<label>` 内，请通过将相同的 ID 传递给 `<textareaid>` 与 [`<label htmlFor>`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLLabelElement/htmlFor) 来将它们关联起来。为了避免一个组件的多实例之间的冲突，使用 [`useId
```suggestion
如果无法将 `<textarea>` 放置在 `<label>` 内，请通过将相同的 ID 传递给 `<textareaid>` 与 [`<label htmlFor>`](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLLabelElement/htmlFor) 来将它们关联起来。为了避免组件在多个实例之间产生冲突，使用 [`useId`](/reference/react/useId) 生成这样的 ID。
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +    // 你可以直接将 formData 作为 fetch 的请求 body：
```suggestion
    // 你可以直接将 formData 作为 fetch 请求的 body：
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +      onChange={e => setPostContent(e.target.value)} // ...并在每次改变（change）时更新 stateany edits!
```suggestion
      onChange={e => setPostContent(e.target.value)} // ...并在每次改变（change）时更新 state！
```

2023-06-23 07:40 UTC, loveloki commented on src/content/reference/react-dom/components/textarea.md
> +你不能一会传递 `value={undefined}` 一会传递 `value="some string"`，这会导致 React 不情出你是想指定受控组件还是非受控组件。受控组件的 `value` 属性应该始终接收字符串，而不是 `null` 或 `undefined`。
```suggestion
你不能先传递 `value={undefined}` 再传递 `value="some string"`，这会导致 React 不知道你是想指定受控组件还是非受控组件。受控组件的 `value` 属性应该始终接收字符串，而不是 `null` 或 `undefined`。
```

2023-06-23 11:19 UTC, loveloki approved these changes

2023-06-23 11:28 UTC, merged