docs(cn): translate reference/react/cloneElement into Chinese
reactjs/zh-hans.react.dev pull request #1207
Opened 2023-06-22 14:35 UTC by li-jia-nan

docs(cn): translate reference/react/cloneElement into Chinese

2023-06-23 01:33 UTC, awxiaoxian2020 requested changes

2023-06-23 01:33 UTC, awxiaoxian2020 commented on src/content/reference/react/cloneElement.md
> +* `props`：`props` 参数必须是一个对象或 `null`。 如果传 `null`，克隆后的元素将保留所有原始的 `element.props`。 否则，对于 `props` 对象中的每个 prop 属性，返回的元素将“优先”使用 `props` 中的值而不是 `element.props` 中的值。 其余的 props 将从原始的 `element.props` 中填充。如果你传递
汉字和中文标点之间不应有空格。请调整。

2023-06-23 07:15 UTC, li-jia-nan commented on src/content/reference/react/cloneElement.md
> +* `props`：`props` 参数必须是一个对象或 `null`。 如果传 `null`，克隆后的元素将保留所有原始的 `element.props`。 否则，对于 `props` 对象中的每个 prop 属性，返回的元素将“优先”使用 `props` 中的值而不是 `element.props` 中的值。 其余的 props 将从原始的 `element.props` 中填充。如果你传递
done~

2023-06-23 14:08 UTC, li-jia-nan commented
顺便想问一下，中文官网隔多久部署一次？

2023-06-24 11:39 UTC, awxiaoxian2020 commented
> 顺便想问一下，中文官网隔多久部署一次？

应该是即时部署

2023-06-25 00:59 UTC, Yucohny reviewed
请自查有关表达是否顺畅、贴切。

2023-06-25 00:59 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +[请参阅下面的更多示例](#usage)
标点缺失。

2023-06-25 00:59 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +* `element`：`element` 参数必须是一个有效的 React 元素。例如它可以是一个像 `<Something />` 这样的 JSX 节点，调用 [`createElement`](/reference/react/createElement) 的结果，或者另一个 `cloneElement` 调用的结果。
后半句略有拗口。

2023-06-25 00:59 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +* 如果 children 已知是静态的，则你应该 **将它们作为多个参数传递给 `cloneElement`**，例如 `cloneElement(element, null, child1, child2, child3)`。如果你的 children 是动态的，请将整个数组作为第三个参数传递：`cloneElement(element, null, listItems)`。这确保了 Rea
```suggestion
* 如果已知 children 是静态的，则你应该 **将它们作为多个参数传递给 `cloneElement`**，例如 `cloneElement(element, null, child1, child2, child3)`。如果你的 children 是动态的，请将整个数组作为第三个参数传递：`cloneElement(element, null, listItems)`。这确保了 React 会对任何动态列表 [警告你缺少“key”](/learn/rendering-lists#keeping-list-items-in-order-with-key)，对于静态的列表，这是不必要的，因为它们不会重新排序。
```

2023-06-25 00:59 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +接受类似 `renderItem` 这样的 *render prop* 代替 `cloneElement` 的用法。在这里，`List` 接收 `renderItem` 作为 prop。`List` 为数组每一项调用 `renderItem`，并传递 `isHighlighted` 作为参数：
```suggestion
接受类似 `renderItem` 这样的 *render prop* 代替 `cloneElement` 的用法。在这里，`List` 接收 `renderItem` 作为 props。`List` 为数组每一项调用 `renderItem`，并传递 `isHighlighted` 作为参数：
```

2023-06-25 13:26 UTC, li-jia-nan commented on src/content/reference/react/cloneElement.md
> +[请参阅下面的更多示例](#usage)
done~

2023-06-25 13:26 UTC, li-jia-nan commented on src/content/reference/react/cloneElement.md
> +* `element`：`element` 参数必须是一个有效的 React 元素。例如它可以是一个像 `<Something />` 这样的 JSX 节点，调用 [`createElement`](/reference/react/createElement) 的结果，或者另一个 `cloneElement` 调用的结果。
优化了一下

2023-06-27 11:17 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +**让我们看一个示例，看看它什么时候有用。**
```suggestion
**让我们看一个示例，看看它什么时候有用**。
```

2023-06-27 11:17 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +想象一个 `List` 组件将其 [`children`](/learn/passing-props-to-a-component#passing-jsx-as-children) 呈现为可选择行的列表，并带有可更改的“下一步”按钮选择了哪一行。`List` 组件需要以不同的方式渲染所选的 `Row`，因此它克隆它收到的每个 `<Row>` 子级，并添加额外的 `isHighlighted: t
```suggestion
想象一个 `List` 组件将其 [`children`](/learn/passing-props-to-a-component#passing-jsx-as-children) 渲染为可选择行的列表，并带有可更改的“下一步”按钮选择了哪一行。`List` 组件需要以不同的方式渲染所选的 `Row`，因此它克隆它收到的每个 `<Row>` 子级，并添加额外的 `isHighlighted: true` 或 `isHighlighted: false` 属性：
```

2023-06-27 11:17 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +总而言之，`List` 克隆了它接收的 `<Row />` 元素，并向它们添加了一个额外的 prop。
```suggestion
总而言之，`List` 克隆了它接收的 `<Row />` 元素，并向它们添加额外的 props。
```

2023-06-27 11:17 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +你的 `List` 组件可以将其呈现的每个 item 传递到 `HighlightContext` provider 中：
```suggestion
`List` 组件可以将其呈现的每个 item 传递到 `HighlightContext` provider 中：
```

2023-06-27 11:17 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +通过这种方法，`Row` 不需要接收 `isHighlighted`属性，它可以从上下文读取到：
```suggestion
通过这种方法，`Row` 不需要接收 `isHighlighted`属性，因为它可以从 context 中读取：
```

2023-06-27 11:19 UTC, merged

2023-06-28 03:34 UTC, whalesink commented on src/content/reference/react/cloneElement.md
> +接受类似 `renderItem` 这样的 *render prop* 代替 `cloneElement` 的用法。在这里，`List` 接收 `renderItem` 作为 prop。`List` 为数组每一项调用 `renderItem`，并传递 `isHighlighted` 作为参数：
为啥原文 `as a prop` 能翻译成 `props`

2023-06-28 03:52 UTC, Yucohny commented on src/content/reference/react/cloneElement.md
> +接受类似 `renderItem` 这样的 *render prop* 代替 `cloneElement` 的用法。在这里，`List` 接收 `renderItem` 作为 prop。`List` 为数组每一项调用 `renderItem`，并传递 `isHighlighted` 作为参数：
在翻译为中文时，如果是表达 React props 这样整体的概念的时候，优先使用 props；其次才考虑原文的单数 prop 是否是特指到某一个具体的 prop，然后保留单数 prop。
此处原文 as a prop 尽管是使用的单数，但是表达的意思更加倾向于前者所述的整体的概念，即是作为组件的 props（尽管只有一个），而不是作为 props 的“某一个 prop”，所以考虑使用 props。