docs(cn): translate legacy/Component into Chinese
reactjs/zh-hans.react.dev pull request #1234
Opened 2023-07-02 14:49 UTC by Tosuke-sama

2023-07-02 18:00 UTC, CoderSerio commented on src/content/reference/react/Component.md
> +`Component` 是被定义为 [JavaScript 类](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) 的 React 基类，类组件仍然被 React 支持，但我们不建议在新代码中使用它们。
> `Component` is the base class for the React components defined as [JavaScript classes.] 
注意这里末尾有个句号，需要断句。

看翻译结果似乎没有注意到这个句号，所以导致结果有些偏差。

2023-07-02 18:03 UTC, CoderSerio commented on src/content/reference/react/Component.md
> +在类组件中读取 `this.props` 等同于在函数式组件中使用的 [declaring props](/learn/passing-props-to-a-component#step-2-read-props-inside-the-child-component) 。
这里的 declaring 不是关键字，可以考虑翻译为 声明式的 ？

2023-07-02 18:03 UTC, CoderSerio commented on src/content/reference/react/Component.md
> +使用 `this.state` 来访问一个类组件的 state 。 `state` 字段必须是一个对象。请不要直接改变 state 的值。如果你希望改变 state ，使用新的 state 来调用 `setState` 函数。
这里的标点符号似乎有些多余的空格

2023-07-02 18:08 UTC, CoderSerio reviewed
存在一些格式问题，部分问题已经在评论中指出，辛苦之后再修改一下重新push。

2023-07-02 18:08 UTC, CoderSerio commented on src/content/reference/react/Component.md
> +在类组件中定义 `state` 等同于在函数式组件中通过调用 [`useState`](/reference/react/useState) 函数所创造的 state 。
格式有些问题，建议使用全局搜索: `[空格]。`，`[空格]，`等， 对这一系列规范进行检查。 
同时也要注意全局替换的影响范围，避免误伤了正确的内容。

2023-07-02 18:08 UTC, CoderSerio commented on src/content/reference/react/Component.md
> +如果你使用更新的 JavaScript 语法的话，那么很少需要使用到 constructors 。相反，你可以使用现代浏览器和像 [Babel](https://babeljs.io/) 这样的工具都支持的[公有类字段语法](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class
> ... 使用到 constructors 。

这里句号前不应该有空格

2023-07-03 02:00 UTC, Tosuke-sama commented
收到，感谢指正，正在根据规则审查

2023-07-03 17:00 UTC, Yucohny reviewed
此篇翻译存在较多格式问题，请自查。除此之外，同样有许多地方的表达值得再三琢磨。

2023-07-03 17:00 UTC, Yucohny commented on src/content/reference/react/Component.md
> +我们建议将组件定义为函数而不是类。[了解如何迁移](#alternatives)
```suggestion
我们建议将组件定义为函数而不是类。[了解如何迁移](#alternatives)。
```

2023-07-03 17:00 UTC, Yucohny commented on src/content/reference/react/Component.md
> +我们建议将组件定义为函数而不是类。[了解如何迁移](#alternatives)
可以考虑调整为“我们建议使用函数式组件，而不是类式组件。”

2023-07-03 17:00 UTC, Yucohny commented on src/content/reference/react/Component.md
> +`Component` 是被定义为 [JavaScript 类](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) 的 React 基类，类组件仍然被 React 支持，但我们不建议在新代码中使用它们。
`Component` 是被定义为 JavaScript 类，此处表达有些拗口。

2023-07-03 17:00 UTC, Yucohny commented on src/content/reference/react/Component.md
> +[查看以下的更多实例](#usage)
```suggestion
[查看以下的更多实例](#usage)。
```

2023-07-03 17:00 UTC, Yucohny commented on src/content/reference/react/Component.md
> +一个类组件的 [context](/learn/passing-data-deeply-with-context) 可以通过使用 `this.context` 来实现。 只有当你使用 [`static contextType`](#static-contexttype) (更新的)或者 [`static contextTypes`](#static-contexttypes) (已被废弃) 来特
```suggestion
一个类组件的 [context](/learn/passing-data-deeply-with-context) 可以通过使用 `this.context` 来实现。 只有当你使用 [`static contextType`](#static-contexttype)（更新的）或者 [`static contextTypes`](#static-contexttypes) (已被废弃) 来特别指定你想要接受 **哪一个** context 时它才会有效。
```

2023-07-05 11:35 UTC, Yucohny reviewed
请注意，此篇仍然存在 **大量** 格式问题。同时，请保持之前调整过的 MDN 中文站点。

2023-07-05 11:35 UTC, Yucohny commented on src/content/reference/react/Component.md
> +对于大多数的使用场景来说，在类组件中一起定义 `componentDidMount`， `componentDidUpdate` 和 `componentWillUnmount` 等同于在函数组件中调用 [`useEffect`](/reference/react/useEffect)。在一些少数的情况，例如在浏览器绘制前执行代码很重要时，更像是等同于 [`useLayoutEffect`](/
```suggestion
对于大多数的使用场景来说，在类组件中一起定义 `componentDidMount`，`componentDidUpdate` 和 `componentWillUnmount` 等同于在函数组件中调用 [`useEffect`](/reference/react/useEffect)。在一些少数的情况，例如在浏览器绘制前执行代码很重要时，更像是等同于 [`useLayoutEffect`](/reference/react/useLayoutEffect)。
```

2023-07-05 11:35 UTC, Yucohny commented on src/content/reference/react/Component.md
> +- 虽然你可以在 `componentDidMount` 中立即调用[`setState`](#setstate)，不过最好避免这样做。 因为这将触发一次额外的渲染，但是这是在浏览器更新屏幕之前发生的。 在这种情况下即使 [`render`](#render) 被调用了两次， 用户也无法看到中间的状态。请谨慎使用这种模式因为它可能会造成性能问题。在大多数情况下， 你应该能在[`construct
```suggestion
- 虽然你可以在 `componentDidMount` 中立即调用[`setState`](#setstate)，不过最好避免这样做。 因为这将触发一次额外的渲染，但是这是在浏览器更新屏幕之前发生的。 在这种情况下即使 [`render`](#render) 被调用了两次， 用户也无法看到中间的状态。请谨慎使用这种模式因为它可能会造成性能问题。在大多数情况下， 你应该能在 [`constructor`](#constructor) 中设置初始的 state。 但是，对于 modal 和 tooltip 等当你的渲染依赖于 DOM 节点的大小或位置情况下，这种方法可能是必要的。
```

2023-07-10 01:07 UTC, Yucohny reviewed
请对照 [译文规范](https://github.com/reactjs/zh-hans.react.dev/wiki/React-Translation-Guide) 自查格式问题。

2023-07-10 01:07 UTC, Yucohny commented on src/content/reference/react/Component.md
> +- 虽然你可以在 `componentDidMount` 中立即调用 [`setState`](#setstate)，不过最好避免这样做。 因为这将触发一次额外的渲染，但是这是在浏览器更新屏幕之前发生的。在这种情况下即使 [`render`](#render) 被调用了两次，用户也无法看到中间的状态。请谨慎使用这种模式因为它可能会造成性能问题。在大多数情况下，你应该能在 [`constructo
```suggestion
- 虽然你可以在 `componentDidMount` 中立即调用 [`setState`](#setstate)，不过最好避免这样做。因为这将触发一次额外的渲染，但是这是在浏览器更新屏幕之前发生的。在这种情况下即使 [`render`](#render) 被调用了两次，用户也无法看到中间的状态。请谨慎使用这种模式因为它可能会造成性能问题。在大多数情况下，你应该能在 [`constructor`](#constructor) 中设置初始的 state。但是对于 modal 和 tooltip 等当你的渲染依赖于 DOM 节点的大小或位置情况下，这种方法可能是必要的。
```

2023-07-10 01:07 UTC, Yucohny commented on src/content/reference/react/Component.md
> +#### 说明 {/*componentdidupdate-caveats*/}
```suggestion
#### 注意 {/*componentdidupdate-caveats*/}
```

2023-07-10 01:07 UTC, Yucohny commented on src/content/reference/react/Component.md
> +- 如果你定义了 [`shouldComponentUpdate`](#shouldcomponentupdate) 并且返回 false 的话，那么 `componentDidUpdate` 将不会被调用。
```suggestion
- 如果你定义了 [`shouldComponentUpdate`](#shouldcomponentupdate) 并且返回 `false` 的话，那么 `componentDidUpdate` 将不会被调用。
```

2023-07-10 01:07 UTC, Yucohny commented on src/content/reference/react/Component.md
> +对于大多数用例来说， 在类组件中一起定义 `componentDidMount`，`componentDidUpdate` 和 `componentWillUnmount` 等同于在函数组件中定义 [`useEffect`](/reference/react/useEffect)。在一些少数的情况，例如在浏览器绘制前执行代码很重要时，更像是等同于[`useLayoutEffect`](/refe
```suggestion
对于大多数用例来说，在类组件中一起定义 `componentDidMount`，`componentDidUpdate` 和 `componentWillUnmount` 等同于在函数组件中定义 [`useEffect`](/reference/react/useEffect)。在一些少数的情况，例如在浏览器绘制前执行代码很重要时，更像是等同于[`useLayoutEffect`](/reference/react/useLayoutEffect)。
```

2023-07-13 16:49 UTC, Tosuke-sama commented
前段日子突发棘事，故翻译自查略显仓促，劳烦了校对者。若有问题可直接指出，我将在当日内重新修改。

2023-07-14 06:44 UTC, Yucohny reviewed
问题较多，最好还是花时间自查一遍……

2023-07-14 06:44 UTC, Yucohny commented on src/content/reference/react/Component.md
> +我们建议使用函数组件，而不是类组件。[了解如何迁移](#alternatives)。
统一使用「类式组件」与「函数式组件」。

2023-07-14 06:44 UTC, Yucohny commented on src/content/reference/react/Component.md
> +`Component` 是一个 [JavaScript 类](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)，是被定义为react组件的基类，类组件仍然被 React 支持，但我们不建议在新代码中使用它们。
注意，MDN 保留中文站点链接。

2023-07-14 06:44 UTC, Yucohny commented on src/content/reference/react/Component.md
> +`Component` 是一个 [JavaScript 类](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)，是被定义为react组件的基类，类组件仍然被 React 支持，但我们不建议在新代码中使用它们。
```suggestion
`Component` 是一个 [JavaScript 类](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)，其被定义为 React 组件的基类，类式组件仍然被 React 支持，但我们不建议在新代码中使用它们。
```

2023-07-14 06:44 UTC, Yucohny commented on src/content/reference/react/Component.md
> +要想将 React 组件定义为一个类，你需要扩展内置的 `Component` 类并定义一个 [`render` 方法](#render)：
```suggestion
如果想要使用类式组件，需要继承内置的 `Component` 类并定义 [`render` 方法](#render)：
```

2023-07-14 06:44 UTC, Yucohny commented on src/content/reference/react/Component.md
> +允许你获取此组件的 [过时的字符串 refs](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs)
```suggestion
允许你获取此组件的 [过时的字符串 ref](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) 
```

2023-07-14 06:44 UTC, Yucohny commented on src/content/reference/react/Component.md
> +运行 [`rename-unsafe-lifecycles` 重构器](https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles) 来自动更新你的组件。
```suggestion
运行 [`rename-unsafe-lifecycles` codemod](https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles) 来自动更新你的组件。
```

2023-07-14 06:44 UTC, Yucohny commented on src/content/reference/react/Component.md
> +你应该将 `render` 方法编写为纯函数，这意味着如果 props、state 和 context 相同，它应该返回相同的结果。它也不应该包含副作用（例如设置监听）或与浏览器 API 交互。副作用应该发生在事件处理程序或 [`componentDidMount`](#componentdidmount) 等方法中。
```suggestion
你应该将 `render` 方法编写为纯函数，这意味着如果 props、state 和 context 相同，它应该返回相同的结果。它也不应该包含副作用（例如订阅监听事件）或与浏览器 API 交互。副作用应该发生在事件处理程序或 [`componentDidMount`](#componentdidmount) 等方法中。
```

2023-07-19 12:54 UTC, Yucohny reviewed
请先自查。

2023-07-19 12:54 UTC, Yucohny commented on src/content/reference/react/Component.md
> +[参加下方更多示例](#usage)。
```suggestion
[参见下方更多示例](#usage)。
```

2023-07-19 12:54 UTC, Yucohny commented on src/content/reference/react/Component.md
> +可以通过使用 `this.context` 来访问一个类式组件的 [context](/learn/passing-data-deeply-with-context)。只有当你使用 [`static contextType`](#static-contexttype) （最新的）或者 [`static contextTypes`](#static-contexttypes) （已被废弃的）来特别
```suggestion
类式组件可以通过使用 `this.context` 访问 [context](/learn/passing-data-deeply-with-context)。只有使用 [`static contextType`](#static-contexttype)（最新的）或 [`static contextTypes`](#static-contexttypes)（已废弃）特别指定想要接受 **哪一个** context 时才会有效。
```

2023-07-19 12:54 UTC, Yucohny commented on src/content/reference/react/Component.md
> +类式组件一次只能读取一个context。
```suggestion
类式组件一次只能读取一个 context。
```

2023-07-19 12:54 UTC, Yucohny commented on src/content/reference/react/Component.md
> +在类式组件中读取 `this.props` 等同于在函数式组件中使用的 [声明式 props](/learn/passing-props-to-a-component#step-2-read-props-inside-the-child-component)。
```suggestion
在类式组件中读取 `this.props` 等同于在函数式组件中使用 [声明式 props](/learn/passing-props-to-a-component#step-2-read-props-inside-the-child-component)。
```

2023-07-19 12:54 UTC, Yucohny commented on src/content/reference/react/Component.md
> +允许你获取此组件的 [非法字符串 ref](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs)
```suggestion
允许你获取此组件的 [历史用法的字符串 ref](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs)。
```

2023-07-19 12:54 UTC, Yucohny commented on src/content/reference/react/Component.md
> +constructor 不应该包含任何副作用或者监听相关的代码。
```suggestion
构造函数不应包含任何存在副作用或者事件监听相关的代码。
```

2023-07-19 12:54 UTC, Yucohny commented on src/content/reference/react/Component.md
> +constructor 不应该包含任何副作用或者监听相关的代码。
此处原文使用「a constructor」，可以理解为「类中的构造器函数」，也可以直接当做 `constructor` 讲。

2023-07-26 01:43 UTC, Yucohny commented
@Tosuke-sama 请自行处理文件冲突。

2023-07-28 11:53 UTC, awxiaoxian2020 commented on src/content/reference/react/Component.md
> +* `prevState`：更新之前的 State。`prevState` 将会与 [`this.state`](#state) 进行比较来确定发生了什么改变。
```suggestion
* `prevState`：更新之前的 state。`prevState` 将会与 [`this.state`](#state) 进行比较来确定发生了什么改变。
```

2023-07-28 11:54 UTC, awxiaoxian2020 commented on src/content/reference/react/Component.md
> +* `prevProps`：更新之前的 Props。`prevProps` 将会与 [`this.props`](#props) 进行比较来确定发生了什么改变。
```suggestion
* `prevProps`：更新之前的 props。`prevProps` 将会与 [`this.props`](#props) 进行比较来确定发生了什么改变。
```

2023-07-28 11:58 UTC, awxiaoxian2020 requested changes

2023-07-28 11:58 UTC, awxiaoxian2020 commented on src/content/reference/react/Component.md
> +允许你获取此组件的 [历史用法的字符串 ref](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs)。
```suggestion
允许你获取此组件 [过时的字符串 ref](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs)。
```

2023-07-28 12:07 UTC, awxiaoxian2020 approved these changes
LGTM! Welcome aboard! 🎉

2023-07-28 12:08 UTC, merged