docs(cn): translate react-dom/server/renderToPipeableStream into Chin…
reactjs/zh-hans.react.dev pull request #1257
Opened 2023-07-08 09:13 UTC by CoderSerio

2023-07-08 15:01 UTC, awxiaoxian2020 requested changes

2023-07-08 15:01 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/server/renderToPipeableStream.md
> +### 将 shell 之内的异常恢复 {/*recovering-from-errors-inside-the-shell*/}
未能做到对应，请调整

2023-07-09 13:00 UTC, CoderSerio commented on src/content/reference/react-dom/server/renderToPipeableStream.md
> +### 将 shell 之内的异常恢复 {/*recovering-from-errors-inside-the-shell*/}
Done

2023-07-10 01:11 UTC, Yucohny reviewed
麻烦自查一下~

2023-07-10 01:11 UTC, Yucohny commented on src/content/reference/react-dom/server/renderToPipeableStream.md
> +`renderToPipeableStream` 将一个 React 组件树渲染为管道化的 [Node.js Stream](https://nodejs.org/api/stream.html)。
Stream 可以考虑直接翻译为「流」。

2023-07-10 01:11 UTC, Yucohny commented on src/content/reference/react-dom/server/renderToPipeableStream.md
> +这个 API 是专供 Node.js 使用的。像 Deno 这类新式非主流运行时环境，可以支持 [Web 流](https://developer.mozilla.org/zh-CN/docs/Web/API/Streams_API)，它们应该使用另一个 API [`renderToReadableStream`](/reference/react-dom/server/renderToRead
```suggestion
这个 API 是专供 Node.js 使用的。像 Deno 这类可以支持 [Web 流](https://developer.mozilla.org/zh-CN/docs/Web/API/Streams_API) 的新式非主流运行时环境，它们应该使用另一个 API [`renderToReadableStream`](/reference/react-dom/server/renderToReadableStream)。
```

2023-07-10 01:11 UTC, Yucohny commented on src/content/reference/react-dom/server/renderToPipeableStream.md
> +## 参考资料 {/*reference*/}
```suggestion
## 参考 {/*reference*/}
```

2023-07-10 01:11 UTC, Yucohny commented on src/content/reference/react-dom/server/renderToPipeableStream.md
> +调用 `renderToPipeableStream` 可以将 React 组件树渲染为 HTML 并形成 [Node.js 流](https://nodejs.org/api/stream.html#writable-streams)。
```suggestion
调用 `renderToPipeableStream` 将 React 组件树渲染为 HTML 后注入 [Node.js 流](https://nodejs.org/api/stream.html#writable-streams)。
```

2023-07-10 01:11 UTC, Yucohny commented on src/content/reference/react-dom/server/renderToPipeableStream.md
> +* `reactNode`: 一个你想要将其渲染为 HTML 的 React 节点。比如，像 `<App />` 这样的 JSX 元素。这样做意味着整个页面文档都将被渲染，所以这里提到的 `App` 组件将渲染 `<html>` 标签.
```suggestion
* `reactNode`：一个你想要将其渲染为 HTML 的 React 节点。比如，像 `<App />` 这样的 JSX 元素。这样做意味着整个页面文档都将被渲染，所以这里提到的 `App` 组件将渲染 `<html>` 标签.
```

2023-07-11 03:24 UTC, merged