docs(cn):translate learn/typescript into Chinese
reactjs/zh-hans.react.dev pull request #1296
Opened 2023-08-14 07:48 UTC by ysh199882

2023-08-14 07:53 UTC, ysh199882 commented
@awxiaoxian2020 你好，已翻译完成，本地已check，请校对

2023-08-14 10:11 UTC, ysh199882 commented
> 请保持行行对应。

已修改

2023-08-14 12:53 UTC, awxiaoxian2020 commented on src/content/learn/typescript.md
> +[`useCallback`](/reference/react/useCallback) 只要传递到第二个参数的依赖项保持不变，就会提供对函数的稳定引用。像 `useMemo` 一样，函数的类型是从第一个参数中的函数的返回值推断的，你可以通过为 hook 提供类型参数来更明确地指定。
这里仍然错位，请重新调整

2023-08-14 12:55 UTC, Yucohny reviewed
请自行检查相关格式。

2023-08-14 12:55 UTC, Yucohny commented on src/content/learn/typescript.md
> +所有的[生产级 React 框架](https://react-dev-git-fork-orta-typescriptpage-fbopensource.vercel.app/learn/start-a-new-react-project#production-grade-react-frameworks)都支持使用 TypeScript。请按照框架特定的指南进行安装：
```suggestion
所有的 [生产级 React 框架](https://react-dev-git-fork-orta-typescriptpage-fbopensource.vercel.app/learn/start-a-new-react-project#production-grade-react-frameworks) 都支持使用 TypeScript。请按照框架特定的指南进行安装：
```

2023-08-15 01:24 UTC, ysh199882 commented on src/content/learn/typescript.md
> +[`useCallback`](/reference/react/useCallback) 只要传递到第二个参数的依赖项保持不变，就会提供对函数的稳定引用。像 `useMemo` 一样，函数的类型是从第一个参数中的函数的返回值推断的，你可以通过为 hook 提供类型参数来更明确地指定。
已重新调整

2023-08-15 01:25 UTC, ysh199882 commented on src/content/learn/typescript.md
> +所有的[生产级 React 框架](https://react-dev-git-fork-orta-typescriptpage-fbopensource.vercel.app/learn/start-a-new-react-project#production-grade-react-frameworks)都支持使用 TypeScript。请按照框架特定的指南进行安装：
已调整相关格式

2023-08-15 02:21 UTC, awxiaoxian2020 commented on src/content/learn/typescript.md
> +[`useCallback`](/reference/react/useCallback) 只要传递到第二个参数的依赖项保持不变，就会提供对函数的稳定引用。像 `useMemo` 一样，函数的类型是从第一个参数中的函数的返回值推断的，你可以通过为 hook 提供类型参数来更明确地指定。
仍未行行对应

2023-08-15 03:22 UTC, ysh199882 commented on src/content/learn/typescript.md
> +[`useCallback`](/reference/react/useCallback) 只要传递到第二个参数的依赖项保持不变，就会提供对函数的稳定引用。像 `useMemo` 一样，函数的类型是从第一个参数中的函数的返回值推断的，你可以通过为 hook 提供类型参数来更明确地指定。
<img width="732" alt="image" src="https://github.com/reactjs/zh-hans.react.dev/assets/76462784/f659ad59-c1a7-4375-873e-e7e1f140f54d">

2023-08-15 03:50 UTC, ysh199882 commented
@awxiaoxian2020 已重新修改

2023-08-15 03:51 UTC, awxiaoxian2020 commented on src/content/learn/typescript.md
> +[`useCallback`](/reference/react/useCallback) 只要传递到第二个参数的依赖项保持不变，就会提供对函数的稳定引用。像 `useMemo` 一样，函数的类型是从第一个参数中的函数的返回值推断的，你可以通过为 hook 提供类型参数来更明确地指定。
@ysh199882 请保证 git diff 增加行数和减少行数一致

2023-08-15 03:53 UTC, awxiaoxian2020 requested changes

2023-08-15 03:53 UTC, awxiaoxian2020 commented on src/content/learn/typescript.md
> +当你需要使用不包含在此列表中的事件时，你可以使用 `React.SyntheticEvent` 类型，这是所有事件的基类型。
原文第412行翻译缺失

2023-08-15 03:57 UTC, Yucohny commented on src/content/learn/typescript.md
> +* [The TypeScript handbook](https://www.typescriptlang.org/docs/handbook/) 是 TypeScript 的官方文档，涵盖了大多数关键的语言特性。
```suggestion
* [TypeScript 官方文档](https://www.typescriptlang.org/docs/handbook/)，涵盖了大多数关键的语言特性。
```

2023-08-15 03:57 UTC, Yucohny commented on src/content/learn/typescript.md
> +* [The TypeScript release notes](https://devblogs.microsoft.com/typescript/) 深入介绍了每一个新特性。
```suggestion
* [TypeScript 发布笔记](https://devblogs.microsoft.com/typescript/) 深入介绍了每一个新特性。
```

2023-08-15 07:07 UTC, ysh199882 commented on src/content/learn/typescript.md
> +当你需要使用不包含在此列表中的事件时，你可以使用 `React.SyntheticEvent` 类型，这是所有事件的基类型。
已补充

2023-08-15 07:07 UTC, ysh199882 commented on src/content/learn/typescript.md
> +[`useCallback`](/reference/react/useCallback) 只要传递到第二个参数的依赖项保持不变，就会提供对函数的稳定引用。像 `useMemo` 一样，函数的类型是从第一个参数中的函数的返回值推断的，你可以通过为 hook 提供类型参数来更明确地指定。
> 一致

已修改

2023-08-15 07:08 UTC, ysh199882 commented on src/content/learn/typescript.md
> +* [The TypeScript release notes](https://devblogs.microsoft.com/typescript/) 深入介绍了每一个新特性。
已调整，但不清楚余下两个是否应该翻译？* [React TypeScript Cheatsheet] * [TypeScript Community Discord]
<img width="865" alt="image" src="https://github.com/reactjs/zh-hans.react.dev/assets/76462784/97f947ae-ec4a-4705-a078-5a567e716f7f">

2023-08-15 07:13 UTC, Yucohny commented on src/content/learn/typescript.md
> +* [The TypeScript release notes](https://devblogs.microsoft.com/typescript/) 深入介绍了每一个新特性。
如果没有合适的表达可以保留。

2023-08-15 08:24 UTC, Yucohny reviewed
烦请自查相关表达是否合适、通顺、流畅。

2023-08-15 08:24 UTC, Yucohny commented on src/content/learn/typescript.md
> +TypeScript 是一种流行的方式，用于为 JavaScript 代码库添加类型定义。开箱即用，TypeScript 支持 JSX，只需在项目中添加 [`@types/react`](https://www.npmjs.com/package/@types/react) 和 [`@types/react-dom`](https://www.npmjs.com/package/@types/r
```suggestion
TypeScript 是一种向 JavaScript 代码添加类型定义的常用方法。TypeScript 天然支持 JSX——只需在项目中添加 [`@types/react`](https://www.npmjs.com/package/@types/react) 和 [`@types/react-dom`](https://www.npmjs.com/package/@types/react-dom) 即可获得完整的 React Web 支持。
```

2023-08-15 08:24 UTC, Yucohny commented on src/content/learn/typescript.md
> +所有的 [生产级 React 框架](https://react-dev-git-fork-orta-typescriptpage-fbopensource.vercel.app/learn/start-a-new-react-project#production-grade-react-frameworks)都支持使用 TypeScript。请按照框架特定的指南进行安装：
```suggestion
所有的 [生产级 React 框架](https://react-dev-git-fork-orta-typescriptpage-fbopensource.vercel.app/learn/start-a-new-react-project#production-grade-react-frameworks) 都支持使用 TypeScript。请按照框架特定的指南进行安装：
```

2023-08-15 08:24 UTC, Yucohny commented on src/content/learn/typescript.md
> +* [Expo](https://docs.expo.dev/guides/typescript/)
保留原文符号……

2023-08-16 05:37 UTC, ysh199882 commented
> 烦请自查相关表达是否合适、通顺、流畅。

好的

2023-08-16 10:09 UTC, awxiaoxian2020 requested changes

2023-08-16 10:09 UTC, awxiaoxian2020 commented on src/content/learn/typescript.md
> +本指南已经介绍了如何在 React 中使用 TypeScript 的基础知识，但还有更多内容等待学习。官网中的单个 API 页面或许包含了如何与 TypeScript 一起使用它们的更深入的说明。
453行翻译缺失

2023-08-17 03:52 UTC, awxiaoxian2020 requested changes

2023-08-17 03:52 UTC, awxiaoxian2020 commented on src/content/learn/typescript.md
> +* [TypeScript 官方文档](https://www.typescriptlang.org/docs/handbook/)，涵盖了大多数关键的语言特性。
保持原文 `-` 的表示形式为宜

2023-08-18 00:43 UTC, Yucohny commented on src/content/learn/typescript.md
> +TypeScript 是一种流行的方式，用于为 JavaScript 代码库添加类型定义。开箱即用，TypeScript 支持 JSX，只需在项目中添加 [`@types/react`](https://www.npmjs.com/package/@types/react) 和 [`@types/react-dom`](https://www.npmjs.com/package/@types/r
@ysh199882 这种可以直接 commit……不必再去原文对应修改。

2023-08-18 02:11 UTC, awxiaoxian2020 requested changes
请调整全文翻译，使其更加流畅，符合中文表达习惯，并解决冲突

2023-08-21 02:46 UTC, merged