docs(cn): improve reference/react/useTransition translation
reactjs/zh-hans.react.dev pull request #1311
Opened 2023-09-08 06:57 UTC by Yucohny

优化 reference/react/useTransition 翻译。

2023-09-08 09:42 UTC, awxiaoxian2020 requested changes

2023-09-08 09:42 UTC, awxiaoxian2020 commented on src/content/reference/react/useTransition.md
> +// React 工作的简易版本
```suggestion
// React 运行的简易版本
```

2023-09-08 10:04 UTC, awxiaoxian2020 approved these changes

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +通过 transition，UI 仍将在重新渲染过程中保持响应性。例如，如果用户点击一个选项卡，但改变了主意并点击另一个选项卡，他们可以在不等待第一个重新渲染完成的情况下完成操作。
```suggestion
通过 transition，UI 仍将在重新渲染过程中保持响应性。例如用户点击一个选项卡，但改变了主意并点击另一个选项卡，他们可以在不等待第一个重新渲染完成的情况下完成操作。
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +<Recipes titleText="使用 useTransition 与寻常状态更新的区别" titleId="examples">
```suggestion
<Recipes titleText="使用 useTransition 与常规状态更新的区别" titleId="examples">
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +由于父组件的状态更新在 `onClick` 事件处理程序内，所以该状态更新会被标记为 transition。这就是为什么，就像之前的例子一样，点击“Posts”后可以立即点击“Contact”。由于更新选定选项卡被标记为了 transition，因此它不会阻止用户交互。
```suggestion
由于父组件的状态更新在 `onClick` 事件处理程序内，所以该状态更新会被标记为 transition。这就是为什么可以在点击“Posts”后立即点击“Contact”。由于更新选定选项卡被标记为了 transition，因此它不会阻止用户交互。
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +你可以使用 `useTransition` 返回的 `isPending` 布尔值来向用户表明存在 transition 正在进行中。例如，选项卡按钮可以有一个特殊的“pending”视觉状态：
```suggestion
你可以使用 `useTransition` 返回的 `isPending` 布尔值来向用户表明当前处于 transition 中。例如，选项卡按钮可以有一个特殊的“pending”视觉状态：
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +// 取决于与 Suspense 一同使用的框架
```suggestion
// 与 Suspense 一同使用的框架
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +// 通常，缓存逻辑会嵌入在框架内部。
```suggestion
// 通常缓存逻辑是由框架内部处理的。
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +// 取决于与 Suspense 一同使用的框架
```suggestion
// 与 Suspense 一同使用的框架
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +// 通常，缓存逻辑会嵌入在框架内部。
```suggestion
// 通常缓存逻辑是由框架内部处理的。
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +// 取决于与 Suspense 一同使用的框架
```suggestion
// 与 Suspense 一同使用的框架
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +// 通常，缓存逻辑会嵌入在框架内部。
```suggestion
// 通常缓存逻辑是由框架内部处理的。
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +不应在将控制输入框的状态变量标记为 transition：
```suggestion
不应将控制输入框的状态变量标记为 transition：
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +  // ❌ 不能将受控输入框的状态变量标记为 transition
```suggestion
  // ❌ 不应将受控输入框的状态变量标记为 transition
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +2. 或者，使用一个状态变量，并添加 [`useDeferredValue`](/reference/react/useDeferredValue)，它将“滞后”于实际值。它会自动触发非阻塞的重新渲染以“追赶”新值。
```suggestion
2. 或者使用一个状态变量，并添加 [`useDeferredValue`](/reference/react/useDeferredValue)，它将“滞后”于实际值，并自动触发非阻塞的重新渲染以“追赶”新值。
```

2023-09-09 06:13 UTC, loveloki commented on src/content/reference/react/useTransition.md
> +`useTransition` 是一个 Hook，因此不能在组件外部调用 `useTransition`；否则，请使用独立的 [`startTransition`](/reference/react/startTransition) 方法。它的工作方式相同，但不提供 `isPending` 指示器。
```suggestion
`useTransition` 是一个 Hook，因此不能在组件外部调用。请使用独立的 [`startTransition`](/reference/react/startTransition) 方法。它们的工作方式相同，但不提供 `isPending` 标记。
```

2023-09-09 10:34 UTC, merged