docs(cn): improve reference/react/suspense translation
reactjs/zh-hans.react.dev pull request #1312
Opened 2023-09-08 09:27 UTC by Yucohny

优化 reference/react/suspense 翻译。

2023-09-08 09:39 UTC, awxiaoxian2020 requested changes

2023-09-08 09:39 UTC, awxiaoxian2020 commented on src/content/reference/react/Suspense.md
> +// 在实际中你可以尝试已经
这里翻译需要调整。

2023-09-08 09:41 UTC, Yucohny commented on src/content/reference/react/Suspense.md
> +// 在实际中你可以尝试已经
```suggestion
// 在实际的例子中，你可以尝试已经
```

2023-09-08 10:09 UTC, awxiaoxian2020 requested changes

2023-09-08 10:09 UTC, awxiaoxian2020 commented on src/content/reference/react/Suspense.md
> +### 应该如何阻止 UI 在更新期间被 fallback 替换 {/*preventing-unwanted-fallbacks*/}
```suggestion
### 如何阻止 UI 在更新期间被 fallback 替换 {/*preventing-unwanted-fallbacks*/}
```
“我应该”是英语中人称多用的独有语言风格，若不想保留，“应该”也应删去，体现中文风格

2023-09-08 10:09 UTC, awxiaoxian2020 commented on src/content/reference/react/Suspense.md
> +  // 如果此更新被挂起，不要隐藏已经展示的内容
```suggestion
  // 如果此更新被挂起，不会隐藏已经展示的内容
```

2023-09-08 10:11 UTC, awxiaoxian2020 submitted a review, later dismissed

2023-09-08 12:38 UTC, loveloki commented on src/content/reference/react/Suspense.md
> +加载数据的组件不必是 Suspense 边界的直接子组件。例如，你可以将 `Biography` 和 `Albums` 移动到一个新的 `Details` 组件中——这不会改变其行为。`Biography` 和 `Albums` 共享最近的父级 `<Suspense>` 边界，因此它们的显示同时进行的。
```suggestion
加载数据的组件不必是 Suspense 边界的直接子组件。例如，你可以将 `Biography` 和 `Albums` 移动到一个新的 `Details` 组件中——这不会改变其行为。`Biography` 和 `Albums` 共享最近的父级 `<Suspense>` 边界，因此它们的同时显示的。
```

2023-09-08 12:38 UTC, loveloki commented on src/content/reference/react/Suspense.md
> +当你按下按钮时，`Router` 组件渲染了 `ArtistPage`，而不是 `IndexPage`。`ArtistPage` 内部的一个组件被挂起，所以最近的 Suspense 边界开始显示 fallback。最近的 Suspense 边界在根附近，所以整个站点布局被 `BigSpinner` 替换了。
```suggestion
当你按下按钮时，`Router` 组件渲染了 `ArtistPage` 而不是 `IndexPage`。因为 `ArtistPage` 内部的一个组件被挂起，所以最近的 Suspense 边界开始显示 fallback。最近的 Suspense 边界在根附近，所以整个站点布局被 `BigSpinner` 替换了。
```

2023-09-08 12:38 UTC, loveloki commented on src/content/reference/react/Suspense.md
> +为了防止这种情况发生，[使用 `startTransition` 将更新标记为非紧急的](#preventing-already-revealed-content-from-hiding)。在 transition 期间，React 将等待足够的数据加载，以防止不需要的退路方案 fallback 出现：
```suggestion
为了防止这种情况发生，[使用 `startTransition` 将更新标记为非紧急的](#preventing-already-revealed-content-from-hiding)。在 transition 期间，React 将等待足够的数据加载，以防止不需要的 fallback 出现：
```

2023-09-09 05:54 UTC, loveloki approved these changes

2023-09-09 10:33 UTC, merged