docs(cn): translate reference/react/experimental_taintObjectReference into Chinese
reactjs/zh-hans.react.dev pull request #1335
Opened 2023-10-07 02:13 UTC by Yucohny

翻译 reference/react/experimental_taintObjectReference。

2023-10-07 05:49 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +* `message`：对象被传递给客户端组件希望显示的消息。如果对象被传递给客户端组件，此消息将作为错误的一部分显示。
```suggestion
* `message`：对象被传递给客户端组件时显示的消息。如果对象被传递给客户端组件，此消息将作为错误的一部分显示。
```

2023-10-07 05:49 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +* `object`：要标记的对象。函数和类实例可以作为 `object` 传递给 `taintObjectReference`。已经阻止将函数和类传递给客户端组件，但 React 的默认错误消息将被替换为您在 `message` 中定义的内容。当将特定类型数组的实例作为 `object` 传递给 `taintObjectReference` 时，该类型数组的其他副本将不会被标记。
```suggestion
* `object`：要标记的对象。函数和类实例可以作为 `object` 传递给 `taintObjectReference`。 React 会阻止将函数和类传递给客户端组件，并且把默认的错误消息替换为在 `message` 中定义的内容。当将特定类型数组的实例作为 `object` 传递给 `taintObjectReference` 时，该类型数组的其他副本将不会被标记。
```

2023-10-07 05:49 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +- 重新创建或克隆一个被标记的对象会创建一个新的未标记的对象，其中可能包含敏感数据。例如，如果有一个被标记的 `user` 对象，`const userInfo = {name: user.name, ssn: user.ssn}` 或 `{...user}` 将创建新的未标记对象。`taintObjectReference` 仅在对象无改变地传递给客户端组件时防止简单的错误。
```suggestion
- 重新创建或克隆一个被标记的对象会创建一个新的未标记的对象，其中可能包含敏感数据。如果有一个被标记的 `user` 对象，执行 `const userInfo = {name: user.name, ssn: user.ssn}` 或 `{...user}` 将创建新的未标记对象。`taintObjectReference` 只能防止把未修改的对象传递给客户端组件这种简单的错误。
```

2023-10-07 05:49 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +### 防止用户数据无意间传递到客户端 {/*prevent-user-data-from-unintentionally-reaching-the-client*/}
```suggestion
### 防止用户数据被无意间传递到客户端 {/*prevent-user-data-from-unintentionally-reaching-the-client*/}
```

2023-10-07 05:49 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +客户端组件不应接受携带敏感数据的对象。理想情况下，数据获取函数不应暴露当前用户不应访问的数据。有时在重构过程中会发生错误。为了防止这些错误在以后发生，我们可以在数据 API 中“标记”用户对象。
```suggestion
客户端组件不应接受携带敏感数据的对象。理想情况下数据获取函数不应暴露当前用户不允许访问的数据。有时在重构过程中会发生错误。为了防止这些错误在以后发生，我们可以在数据 API 中“标记”用户对象。
```

2023-10-07 05:49 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +如果正在运行具有对敏感数据访问权限的服务器组件环境，必须小心不要直接传递对象：
```suggestion
如果处于对敏感数据具有访问权限的服务器组件环境，必须牢记不要直接传递对象：
```

2023-10-07 05:49 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +理想情况下，`getUser` 不应暴露当前用户不应访问的数据。为了防止将来将 `user` 对象传递给客户端组件，我们可以对用户对象进行“标记”：
```suggestion
理想情况下 `getUser` 不应暴露当前用户不允许访问的数据。为了防止将来把 `user` 对象传递给客户端组件，我们可以对用户对象进行“标记”：
```

2023-10-07 09:23 UTC, awxiaoxian2020 requested changes

2023-10-11 01:32 UTC, Yucohny commented
I opened an issue to discuss how to understand the word taint. See https://github.com/reactjs/react.dev/issues/6343 plz.

2023-10-16 11:44 UTC, loveloki commented on src/content/reference/react/experimental_taintObjectReference.md
> +* `object`：要标记的对象。函数和类实例可以作为 `object` 传递给 `taintObjectReference`。React 已经阻止直接将函数和类传递给客户端组件，而默认错误消息将被替换为在 `message` 中定义的内容。当将特定类型数组的实例作为 `object` 传递给 `taintObjectReference` 时，该类型数组的其他副本将不会被标记。
```suggestion
* `object`：要标记的对象。函数和类实例可以作为 `object` 传递给 `taintObjectReference`。React 会阻止直接将函数和类传递给客户端组件，并把默认的错误消息替换为在 `message` 中定义的内容。当将特定类型数组的实例作为 `object` 传递给 `taintObjectReference` 时，该类型数组的其他副本将不会被标记。
```

2023-10-16 12:07 UTC, loveloki approved these changes

2023-10-16 12:08 UTC, merged