docs(cn): translate reference/react-dom/useFormStatus into Chinese
reactjs/zh-hans.react.dev pull request #1348
Opened 2023-10-19 03:11 UTC by Yucohny

翻译 reference/react-dom/useFormStatus。

2023-10-19 03:14 UTC, awxiaoxian2020 requested changes

2023-10-19 03:14 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +`useFormStatus` 是一个 Hook，用于提供上次表单提交的状态信息。
```suggestion
`useFormStatus` 是一个用于提供上次表单提交的状态信息的 Hook。
```

2023-10-19 03:23 UTC, awxiaoxian2020 submitted a review, later dismissed

2023-10-19 13:35 UTC, loveloki commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +`useFormStatus` 是一个用于提供上次表单提交的状态信息的 Hook。
```suggestion
`useFormStatus` 是一个提供上次表单提交状态信息的 Hook。
```

2023-10-19 13:35 UTC, loveloki commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +* `data`：实现了 [`FormData interface`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) 的对象，包含父级 `<form>` 正在提交的数据；如果没有活动提交或没有父级 `<form>`，它将为 `null`。
```suggestion
* `data`：实现了 [`FormData 接口`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) 的对象，包含父级 `<form>` 正在提交的数据；如果没有进行提交或没有父级 `<form>`，它将为 `null`。
```

活动提交感觉有点怪，想了下这里表达的是“进行过”提交？

2023-10-19 13:35 UTC, loveloki commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +* `action`：引用传递给父级 `<form>` 的 `action` 属性的函数。如果没有父级 `<form>`，则该属性为 `null`。如果在 `action` 属性上提供了 URI 值，或者未指定 `action` 属性，`status.action` 将为 `null`。
```suggestion
* `action`：一个传递给父级 `<form>` 的 `action` 属性的函数引用。如果没有父级 `<form>`，则该属性为 `null`。如果在 `action` 属性上提供了 URI 值，或者未指定 `action` 属性，`status.action` 将为 `null`。
```

2023-10-19 13:35 UTC, loveloki commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +可以在一个在 `<form>` 中渲染的组件中调用 `useFormStatus` Hook，并读取返回的 `pending` 属性，以在表单提交期间显示待定状态。
```suggestion
可以在 `<form>` 中渲染的子组件中调用 `useFormStatus` Hook，并读取返回的 `pending` 属性，以在表单提交期间显示待定状态。
```

2023-10-19 13:35 UTC, loveloki commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +而应该从位于 `<form>` 内部的组件中调用 `useFormStatus`。
```suggestion
正确的做法是从位于 `<form>` 内部的组件中调用 `useFormStatus`。
```

2023-10-19 13:35 UTC, loveloki commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +如果调用 `useFormStatus` 的组件未嵌套在 `<form>` 中，`status.pending` 总是返回 `false`。请验证 `useFormStatus` 是否在一个 `<form>` 元素的子组件中调用。
```suggestion
如果调用 `useFormStatus` 的组件未嵌套在 `<form>` 中，`status.pending` 总是返回 `false`。请验证 `useFormStatus` 是否在 `<form>` 元素的子组件中调用。
```

2023-10-20 01:07 UTC, Yucohny commented on src/content/reference/react-dom/hooks/useFormStatus.md
> +* `data`：实现了 [`FormData interface`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) 的对象，包含父级 `<form>` 正在提交的数据；如果没有活动提交或没有父级 `<form>`，它将为 `null`。
嗯，这个地方翻译为「进行提交」更为妥当。前面一个地方 `FormData interface` 考虑到这是行内代码，interface 保留应该比较好吧。即使将「接口」从行内代码剔除变为「`FormData` 接口」也感觉有点怪怪的。

2023-10-20 01:18 UTC, loveloki approved these changes

2023-10-20 01:39 UTC, merged