docs(cn): translate the new content of learn/preserving-and-resetting-state into Chinese
reactjs/zh-hans.react.dev pull request #1352
Opened 2023-10-20 02:43 UTC by Yucohny

翻译 learn/preserving-and-resetting-state 新增内容。

2023-10-20 07:50 UTC, awxiaoxian2020 requested changes

2023-10-20 07:50 UTC, awxiaoxian2020 commented on src/content/learn/preserving-and-resetting-state.md
> +* React 合适选择保留或重置状态
```suggestion
* React 何时选择保留或重置状态
```

2023-10-22 13:06 UTC, loveloki commented on src/content/learn/preserving-and-resetting-state.md
> +* 键和类型如何影响状态是否被保留
```suggestion
* 键和类型对是否保留状态的影响
```

2023-10-22 13:09 UTC, awxiaoxian2020 commented on src/content/learn/preserving-and-resetting-state.md
> +* 键和类型如何影响状态是否被保留
@loveloki 虽然我觉得这里略有不顺，需要调整，但是还是觉得调整要在问句的范围内好一点，这样形式统一。

2023-10-22 13:12 UTC, loveloki commented on src/content/learn/preserving-and-resetting-state.md
> +* 键和类型如何影响状态是否被保留
**键和类型如何影响是否保留状态（的逻辑）**

这样子稍微顺口一些

2023-10-23 00:54 UTC, Yucohny commented on src/content/learn/preserving-and-resetting-state.md
> +* 键和类型如何影响状态是否被保留
我感觉原本的翻译好像也还是比较顺口

2023-10-23 13:20 UTC, loveloki approved these changes

2023-10-24 01:05 UTC, merged