docs(cn): translate learn/understanding-your-ui-as-a-tree into Chinese
reactjs/zh-hans.react.dev pull request #1353
Opened 2023-10-20 03:03 UTC by Yucohny

翻译 learn/understanding-your-ui-as-a-tree。

2023-10-20 07:43 UTC, awxiaoxian2020 requested changes

2023-10-20 07:43 UTC, awxiaoxian2020 commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +当 React 应用程序逐渐成形时，许多组件嵌套在彼此之内。那么 React 是如何跟踪应用程序组件结构的？
```suggestion
当 React 应用程序逐渐成形时，许多组件会出现嵌套。那么 React 是如何跟踪应用程序组件结构的？
```

2023-10-20 07:43 UTC, awxiaoxian2020 commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +React 以及许多其他 UI 库，将 UI 建模为树。将应用程序视为树对于理解组件之间的关系以及调试性能和状态管理等未来概念非常有用。
```suggestion
React 以及许多其他 UI 库，将 UI 建模为树。将应用程序视为树对于理解组件之间的关系以及调试性能和状态管理等未来将会遇到的一些概念非常有用。
```

2023-10-20 07:43 UTC, awxiaoxian2020 commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +下面是一个渲染鼓舞人心的引用语的 React 应用程序。
```suggestion
下面的 React 应用程序渲染了一些鼓舞人心的引语。
```

2023-10-20 07:43 UTC, awxiaoxian2020 commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +React 创建了一个由渲染的组件构成的 UI 树，被称为渲染树。
```suggestion
React 创建的 UI 树是由渲染过的组件构成的，被称为渲染树。
```

2023-10-20 07:43 UTC, awxiaoxian2020 commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +[TODO]: <> (添加 challenge)
```suggestion
[TODO]: <> (Add challenges)
```
这个地方还没有写，翻译没有什么意义。

2023-10-23 13:35 UTC, loveloki commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +也许会注意到在上面的渲染树中，没有提到每个组件渲染的 HTML 标签。这是因为渲染树仅由 React [组件](learn/your-first-component#components-ui-building-blocks) 组成。
```suggestion
也许你会注意到在上面的渲染树中，没有提到每个组件渲染的 HTML 标签。这是因为渲染树仅由 React [组件](learn/your-first-component#components-ui-building-blocks) 组成。
```

2023-10-23 13:35 UTC, loveloki commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +在条件渲染中，不同的渲染过程中，渲染树可能会渲染不同的组件。
```suggestion
在条件渲染的不同渲染过程中，渲染树可能会渲染不同的组件。
```

2023-10-23 13:35 UTC, loveloki commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +* 依赖树有助于调试大型捆绑包大小，缓慢的渲染速度，以及优化哪些代码应该捆绑的机会。
```suggestion
* 依赖树有助于调试大型捆绑包带来的渲染速度过慢的问题，以及发现哪些捆绑代码可以被优化。
```

2023-10-24 06:58 UTC, awxiaoxian2020 approved these changes

2023-10-24 07:06 UTC, merged