docs(cn): translate reference/react/use-server into Chinese
reactjs/zh-hans.react.dev pull request #1378
Opened 2023-11-08 02:15 UTC by Yucohny

翻译 reference/react/use-server。

2023-11-10 12:26 UTC, awxiaoxian2020 requested changes

2023-11-10 12:26 UTC, awxiaoxian2020 commented on src/content/reference/react/use-server.md
> +* 普通 [对象](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object)：使用 [对象初始化器](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Object_initi
85行漏译

2023-11-13 08:50 UTC, awxiaoxian2020 requested changes

2023-11-13 08:50 UTC, awxiaoxian2020 commented on src/content/reference/react/use-server.md
> +* [Server Actions](/reference/react/use-server) 中的函数
还有这里

2023-11-13 09:02 UTC, awxiaoxian2020 requested changes

2023-11-13 09:02 UTC, awxiaoxian2020 commented on src/content/reference/react/use-server.md
> +* [Server Actions](/reference/react/use-server) 中的函数
```suggestion
* Server Action 中的函数
```

2023-11-13 09:02 UTC, awxiaoxian2020 commented on src/content/reference/react/use-server.md
> +* 客户端或服务器组件元素（JSX）
* [Promise](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)

2023-11-13 09:02 UTC, awxiaoxian2020 commented on src/content/reference/react/use-server.md
> +* 客户端或服务器组件元素（JSX）
```suggestion
* [Promise](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)
```

2023-11-13 09:04 UTC, awxiaoxian2020 requested changes
Server Action 是否考虑改成单数

2023-11-13 09:09 UTC, Yucohny commented
> Server Action 是否考虑改成单数

保留复数吧，用单数总感觉很奇怪。

2023-11-14 14:48 UTC, Huxpro commented
> > Server Action 是否考虑改成单数
> 
> 保留复数吧，用单数总感觉很奇怪。

中文中出现英文数据一律用单数哈

2023-11-17 05:38 UTC, awxiaoxian2020 approved these changes

2023-11-17 05:40 UTC, merged