typo and translate
reactjs/zh-hans.react.dev pull request #1412
Opened 2024-01-04 03:39 UTC by marunrun

2024-01-04 03:43 UTC, Yucohny commented on src/content/reference/react/useId.md
> +如果页面上只有一个 React 应用程序，则无需传递 `identifierPrefix` 。
```suggestion
如果页面上只有一个 React 应用程序，则无需传递 `identifierPrefix`。
```

2024-01-04 03:44 UTC, Yucohny approved these changes

2024-01-08 05:55 UTC, awxiaoxian2020 requested changes

2024-01-08 05:55 UTC, awxiaoxian2020 commented on src/content/reference/react/useId.md
> +如果你 [在同一页面上渲染多个独立的 React 应用程序](#specifying-a-shared-prefix-for-all-generated-ids)，并且其中一些应用程序是服务端渲染，请确保你在客户端向 [`hydrateRoot`](/reference/react-dom/client/hydrateRoot) 调用传递的标识符前缀 `identifierPrefix` 与你向
```suggestion
如果你 [在同一页面上渲染多个独立的 React 应用程序](#specifying-a-shared-prefix-for-all-generated-ids)，并且其中一些应用程序是服务端渲染，请确保你在客户端向 [`hydrateRoot`](/reference/react-dom/client/hydrateRoot) 调用传递的标识符前缀 `identifierPrefix` 与你向 [服务器 API ](/reference/react-dom/server) （如 [`renderToPipeableStream`](/reference/react-dom/server/renderToPipeableStream) ）传递的标识符前缀 `identifierPrefix` 相同。
```

2024-01-08 05:55 UTC, awxiaoxian2020 approved these changes

2024-01-08 05:56 UTC, merged