docs(cn): translate reference/react-dom/preload into Chinese
reactjs/zh-hans.react.dev pull request #1432
Opened 2024-02-04 01:34 UTC by Yucohny

翻译 reference/react-dom/preload。

2024-02-05 01:05 UTC, awxiaoxian2020 requested changes

2024-02-05 01:11 UTC, Yucohny commented on src/content/reference/react-dom/preload.md
> +  *  `as`：必需的字符串，表示资源的类型，[可能的值](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/link#as) 包括 `audio`、`document`、`embed`、`fetch`、`font`、`image`、`object`、`script`、`style`、`track`、`video` 与 `wo
我觉得这个地方用逗号间隔没有什么问题。

2024-02-05 01:15 UTC, awxiaoxian2020 commented on src/content/reference/react-dom/preload.md
> +  *  `as`：必需的字符串，表示资源的类型，[可能的值](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/link#as) 包括 `audio`、`document`、`embed`、`fetch`、`font`、`image`、`object`、`script`、`style`、`track`、`video` 与 `wo
问题确实不大，主要考虑是原文是句号，中文也没有不使用句号的特殊原因。

2024-02-05 02:02 UTC, Yucohny commented on src/content/reference/react-dom/preload.md
> +  *  `as`：必需的字符串，表示资源的类型，[可能的值](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/link#as) 包括 `audio`、`document`、`embed`、`fetch`、`font`、`image`、`object`、`script`、`style`、`track`、`video` 与 `wo
这个地方我觉得用逗号前后更紧密一点。

2024-02-05 16:00 UTC, loveloki commented on src/content/reference/react-dom/preload.md
> +  *  `fetchPriority`：字符串，表示建议获取资源的相对优先级，可能的值为 `auto`（默认值）、`high` 与 `low`。
```suggestion
  *  `fetchPriority`：字符串，为获取资源建议的相对优先级，可能的值为 `auto`（默认值）、`high` 与 `low`。
```

和其他页面保持一致就行，先用了另一个页面的 comment。

2024-02-05 16:00 UTC, loveloki commented on src/content/reference/react-dom/preload.md
> +### 在事件处理程序在预加载 {/*preloading-in-an-event-handler*/}
```suggestion
### 在事件处理程序中预加载 {/*preloading-in-an-event-handler*/}
```

2024-02-05 16:00 UTC, loveloki commented on src/content/reference/react-dom/preload.md
> +在转换到需要外部资源的页面或状态之前，于事件处理程序中调用 `preload`。这会比在渲染新页面或状态时调用它更早地启动了该过程。
```suggestion
在转换到需要外部资源的页面或状态之前，于事件处理程序中调用 `preload`。这会比在渲染新页面或状态时调用它更早地启动该过程。
```

2024-02-06 10:44 UTC, loveloki commented on src/content/reference/react-dom/preload.md
> +* 在浏览器中，可以在任何情况下调用 `preload`：在渲染组件时，在 Effect 中，在事件处理程序中等等。
```suggestion
* 在浏览器中，可以在任何情况下调用 `preload`：例如渲染组件时、Effect 中以及事件处理程序中等等。
```

2024-02-07 01:46 UTC, loveloki approved these changes

2024-02-07 02:00 UTC, merged