docs(cn): translate the missing part in useInsertionEffect.md
reactjs/zh-hans.react.dev pull request #1482
Opened 2024-03-18 16:13 UTC by fsen-capricorn

翻译useInsertionEffect中遗漏翻译的内容

2024-03-18 22:33 UTC, awxiaoxian2020 requested changes
请将“您”改为“你”

2024-03-19 01:39 UTC, awxiaoxian2020 requested changes

2024-03-19 01:39 UTC, awxiaoxian2020 commented on src/content/reference/react/useInsertionEffect.md
> +* 与其他类型的 Effects 不同，它们会先为每个 Effect 触发 cleanup 函数，然后再触发 setup 函数。而 `useInsertionEffect` 会同时触发 cleanup 函数和 setup 函数。这会导致 cleanup 函数和 setup 函数的"交错"执行。
```suggestion
* 与其他类型的 Effects 不同，它们会先为每个 Effect 触发 cleanup 函数，然后再触发 setup 函数。而 `useInsertionEffect` 会同时触发 cleanup 函数和 setup 函数。这会导致 cleanup 函数和 setup 函数的“交错”执行。
```

2024-03-19 02:26 UTC, Yucohny approved these changes

2024-03-19 02:29 UTC, awxiaoxian2020 approved these changes

2024-03-19 02:29 UTC, merged