docs(cn): translate reference/rules/index.md into Chinese
reactjs/zh-hans.react.dev pull request #1501
Opened 2024-04-04 09:09 UTC by fsen-capricorn

翻译 reference/rules/index.md

2024-04-09 01:56 UTC, awxiaoxian2020 requested changes

2024-04-09 01:56 UTC, awxiaoxian2020 commented on src/content/reference/rules/index.md
> +* [组件必须是幂等的](/reference/rules/components-and-hooks-must-be-pure#components-and-hooks-must-be-idempotent) – React 组件被假定为总是针对它们一样的输入 – props, state, 和 context 返回相同的输出。
```suggestion
* [组件必须是幂等的](/reference/rules/components-and-hooks-must-be-pure#components-and-hooks-must-be-idempotent)——React 组件被假定为总是针对它们一样的输入——props, state, 和 context 返回相同的输出。
```
下同

2024-04-10 14:53 UTC, fsen-capricorn commented on src/content/reference/rules/index.md
> +* [组件必须是幂等的](/reference/rules/components-and-hooks-must-be-pure#components-and-hooks-must-be-idempotent) – React 组件被假定为总是针对它们一样的输入 – props, state, 和 context 返回相同的输出。
替换好了

2024-04-12 01:03 UTC, Yucohny commented
这篇文章我记得不是翻译过了吗？是不是之前合并的时候给还原了？

2024-04-14 01:04 UTC, awxiaoxian2020 commented
> 这篇文章我记得不是翻译过了吗？是不是之前合并的时候给还原了？

https://github.com/reactjs/zh-hans.react.dev/pull/1484

2024-04-14 01:05 UTC, awxiaoxian2020 commented
@fsen-capricorn Hook 建议保持原词，无需翻译

2024-04-20 13:48 UTC, fsen-capricorn commented
> @fsen-capricorn Hook 建议保持原词，无需翻译

已改

2024-04-20 14:02 UTC, awxiaoxian2020 commented
请参照 wiki 中的译文规范进行空格和单复数的调整。

2024-04-20 14:38 UTC, fsen-capricorn commented
> 请参照 wiki 中的译文规范进行空格和单复数的调整。

不好意思，已阅读并修复了一版本，帮忙看看还有没有遗漏的😊

2024-04-21 01:42 UTC, awxiaoxian2020 requested changes

2024-04-21 01:42 UTC, awxiaoxian2020 commented on src/content/reference/rules/index.md
> +* [组件必须是幂等的](/reference/rules/components-and-hooks-must-be-pure#components-and-hooks-must-be-idempotent)——React 组件被假定为总是针对它们一样的输入——props,state,和 context 返回相同的输出。
```suggestion
* [组件必须是幂等的](/reference/rules/components-and-hooks-must-be-pure#components-and-hooks-must-be-idempotent)——React 组件被假定为总是针对它们一样的输入——props、state 和 context 返回相同的输出。
```

2024-04-23 01:11 UTC, awxiaoxian2020 approved these changes
Thanks

2024-04-23 01:11 UTC, merged