docs(cn): translate blog/2024/04/25/react-19 into Chinese
reactjs/zh-hans.react.dev pull request #1543
Opened 2024-05-19 03:12 UTC by kiner-tang

2024-05-20 01:40 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
如果原文换行有问题，请先去原文提 PR~

2024-05-20 01:41 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
好的

2024-05-20 01:43 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
![image](https://github.com/reactjs/zh-hans.react.dev/assets/10286961/6e079c79-a960-4a12-86de-9702e222873d)
![image](https://github.com/reactjs/zh-hans.react.dev/assets/10286961/6207337e-0d7a-4142-a438-710166a6f716)
原文换行没问题。这边只是做了翻译而已

2024-05-20 01:50 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
Markdown 对于不分段换行渲染时，会当作空格处理。所以渲染没有问题。

译文需要和原文行行对应。

2024-05-20 01:58 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
哦，明白了，
<img width="720" alt="image" src="https://github.com/reactjs/zh-hans.react.dev/assets/10286961/13b7004c-9ff9-49c6-8e43-722c31385431">
我去英文文档那边改一下

2024-05-20 02:01 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
- https://github.com/reactjs/react.dev/pull/6883

2024-05-20 04:29 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
等这个合并，我们这边再跟进

2024-05-21 02:57 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +你可以使用 [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod/#no-implicit-ref-callback-return) 这个 codemod 来转换这种模式。
好像没有人帮忙 review 英文版本的 pr 呀

2024-05-21 23:32 UTC, kiner-tang commented
已经合过去了，@awxiaoxian2020

2024-05-22 05:02 UTC, awxiaoxian2020 commented
请解决冲突

2024-05-22 08:25 UTC, kiner-tang commented
> 请解决冲突

doen

2024-05-22 09:18 UTC, Ivocin reviewed
文章有点长，简单 review 了一下，供参考

2024-05-22 09:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
>  // Before Actions
注释建议翻译

2024-05-22 09:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +在我们的 [React 19 Beta 升级指南](/blog/2024/04/25/react-19-upgrade-guide) 中，我们分享了将您的应用升级到 React 19 Beta 的逐步指南。在这篇文章中，我们将概述 React 19 中的新功能，以及您如何采用它们。
建议统一用“你”代替“您”

2024-05-22 09:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
>  ## React Server Components {/*react-server-components*/}
建议翻译

2024-05-22 09:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
>  ### Server Components {/*server-components*/}
建议翻译

2024-05-22 09:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
>  ### Server Actions {/*server-actions*/}
建议翻译

2024-05-22 09:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +在 `react-dom` 中，我们也改进了 hydration 错误的错误报告。例如，现在不再在 DEV 中记录多个没有任何不匹配信息的错误：
hydration 错误，上文标题翻译为了水合错误，建议统一

2024-05-22 09:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +在 React 19 中，你可以将 `<Context>` 渲染为提供者，而不是 `<Context.Provider>`：
而不是 `<Context.Provider>` 建议翻译为 
无需再使用 `<Context.Provider>` 了

2024-05-22 12:45 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +有关破坏性更改的列表，请参阅 [升级指南](/blog/2024/04/25/react-19-upgrade-guide).
```suggestion
有关破坏性更改的列表，请参阅 [升级指南](/blog/2024/04/25/react-19-upgrade-guide)。
```

2024-05-22 12:49 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +`useActionState` 接受一个函数（"Action"），并返回一个被包装的用于调用的 Action。这是因为 Actions 是可以组合的。当调用被包装的 Action 时，`useActionState` 将返回 Action 的最后结果作为 `data`，以及 Action 的待处理状态作为 `pending`。
```suggestion
`useActionState` 接受一个函数（“Action”），并返回一个被包装的用于调用的 Action。这是因为 Actions 是可以组合的。当调用被包装的 Action 时，`useActionState` 将返回 Action 的最后结果作为 `data`，以及 Action 的待处理状态作为 `pending`。
```

2024-05-23 02:41 UTC, Ivocin requested changes
翻译的很流畅，重新通读了一下，请参考调整

2024-05-23 02:41 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +在 React 应用中，一个常见的用例是执行数据变更，然后响应更新状态。例如，当用户提交一个表单来更改他们的名字，你会发起一个 API 请求，然后处理响应。在过去，你需要手动处理待处理状态、错误、乐观更新和顺序请求。
手动处理待处理状态 ，两个处理有些别扭，建议 pending state 译为 待定状态
与 [在表单提交期间显示待定状态](https://zh-hans.react.dev/reference/react-dom/hooks/useFormStatus#display-a-pending-state-during-form-submission)  这处保持一致
本文有多处 pending state ，建议统一修改

2024-05-23 02:41 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +在 React 19 中，我们添加了在过渡中使用异步函数的支持，以自动处理待处理状态、错误、表单和乐观更新。
我们添加了 -> 我们正在添加

2024-05-23 02:41 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
>  ```
> // You can return any result of the action.
> // Here, we return only the error.

注释建议翻译

2024-05-23 02:41 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +在设计系统中，常常需要编写设计组件，这些组件需要访问它们所在的 `<form>` 的信息，而无需将属性传递到组件中。这可以通过 Context 来实现，但为了使常见情况更简单，我们添加了一个新的钩子 `useFormStatus`：
```suggestion
在设计系统中，常常需要编写设计一类能够访问其所在的 `<form>` 的信息而无需将属性传递到组件内的组件。这可以通过 Context 来实现，但为了使这类常见情况更简单，我们添加了一个新的钩子 `useFormStatus`：
```

2024-05-23 02:41 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
>  />
上文注释建议翻译

2024-05-23 02:41 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +这个测试版的发布是为了 React 19 的库做准备。应用开发者应该升级到 18.3.0，并等待 React 19 稳定版发布，因为我们正在维护这个库，并根据反馈进行更改。
```suggestion
这个测试版的发布是为了 React 19 正式版做准备。应用开发者应先升级到 18.3.0，并等待 React 19 稳定版发布，因为我们正在维护这个库，并根据反馈进行更改。
```

2024-05-23 02:41 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +服务器组件是一种新的选项，允许在打包前提前渲染组件，在与你的客户端应用程序或 SSR 服务器不同的环境中。这个独立的环境就是 React 服务器组件中的 "服务器"。服务器组件可以在你的 CI 服务器上在构建时运行一次，或者可以在每次请求时使用 web 服务器运行。
建议统一改为服务端组件，与标题保持一致
全文有非常多的服务器组件，注意统一修改

2024-05-23 04:18 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +服务器组件是一种新的选项，允许在打包前提前渲染组件，在与你的客户端应用程序或 SSR 服务器不同的环境中。这个独立的环境就是 React 服务器组件中的 "服务器"。服务器组件可以在你的 CI 服务器上在构建时运行一次，或者可以在每次请求时使用 web 服务器运行。
统一采用“服务器组件”

2024-05-23 13:04 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +服务器组件是一种新的选项，允许在打包前提前渲染组件，在与你的客户端应用程序或 SSR 服务器不同的环境中。这个独立的环境就是 React 服务器组件中的 "服务器"。服务器组件可以在你的 CI 服务器上在构建时运行一次，或者可以在每次请求时使用 web 服务器运行。
那我就改成：“服务器组件”？

2024-05-24 01:18 UTC, Ivocin requested changes

2024-05-24 01:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +  // 因为过早的返回，导致 useContext 无法使用
注释行数与原文保持一致
不要删除 305 行

2024-05-24 01:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +### 服务端操作 {/*server-actions*/}
```suggestion
### 服务器操作 {/*server-actions*/}
```

2024-05-24 01:18 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +这个测试版的发布是为了 React 19 的库做准备。应用开发者应该升级到 18.3.0，并等待 React 19 稳定版发布，因为我们正在维护这个库，并根据反馈进行更改。
```suggestion
这个测试版的发布是为了 React 19 正式版做准备。应用开发者应先升级到 18.3.0，并等待 React 19 稳定版发布，因为我们正在维护这个库，并根据反馈进行更改。
```

2024-05-24 01:31 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +例如，你可以在 `useState` 中处理待处理和错误状态：
```suggestion
例如，你可以在 `useState` 中处理待定和错误状态：
```

2024-05-24 01:34 UTC, Ivocin requested changes

2024-05-24 01:34 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +    // 新特性: 当元素从 DOM 中被移除时返回一个清理函数来重置 ref
行数与原文保持一致，不要删除行

2024-05-24 03:33 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +    // 新特性: 当元素从 DOM 中被移除时返回一个清理函数来重置 ref
其实上下两行本来就是一句话来的，翻译成中文的时候，如果不合并成一行会看起来很奇怪，读起来特别别扭

2024-05-24 03:35 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +    // 新特性: 当元素从 DOM 中被移除时返回一个清理函数来重置 ref
因为英文的行文次序将条件放在后面了，但按照中文的行文次序，应该用“当...的时候...”读起来更加通顺

2024-05-24 05:00 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +    // 新特性: 当元素从 DOM 中被移除时返回一个清理函数来重置 ref
> 其实上下两行本来就是一句话来的，翻译成中文的时候，如果不合并成一行会看起来很奇怪，读起来特别别扭

用空行补齐

2024-05-24 05:07 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +    // 新特性: 当元素从 DOM 中被移除时返回一个清理函数来重置 ref
对，其实目标就是译文和原文行数要对应上，review diff 的时候才方便校对
不是说一定要每行的中文和原英文的意思一一对应上去，可以按照中文的语义来断成两行，比如不修改你的译文：
// 新特性: 当元素从 DOM 中被移除时
// 返回一个清理函数来重置 ref

2024-05-24 05:09 UTC, Ivocin requested changes

2024-05-24 05:09 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +  // 因为过早的返回。
这里也一样，译文不用调整的，只需要断一下句：
 //  因为过早的返回
 //  导致 useContext 无法使用

2024-05-24 05:56 UTC, kiner-tang commented on src/content/blog/2024/04/25/react-19.md
> +  // 因为过早的返回。
好的

2024-05-24 06:15 UTC, Ivocin commented on src/content/blog/2024/04/25/react-19.md
> +在我们的 [React 19 RC Upgrade Guide](/blog/2024/04/25/react-19-upgrade-guide) 中, 我们分享了将应用程序升级到 React 19 的分步说明。在这篇文章中，我们将概述 React 19 的新特性，以及如何使用它们。
```suggestion
在我们的 [React 19 RC 升级指南](/blog/2024/04/25/react-19-upgrade-guide) 中, 我们分享了将应用程序升级到 React 19 的分步说明。在这篇文章中，我们将概述 React 19 的新特性，以及如何使用它们。
```

2024-05-24 06:15 UTC, Ivocin approved these changes

2024-05-24 08:31 UTC, awxiaoxian2020 commented on src/content/blog/2024/04/25/react-19.md
> +  // 因为过早的返回
```suggestion
  
  // 因为过早的返回
```

2024-05-24 08:42 UTC, awxiaoxian2020 approved these changes
Thanks!

2024-05-24 08:53 UTC, merged