docs(cn): improve learn/choosing-the-state-structure translation
reactjs/zh-hans.react.dev pull request #1561
Opened 2024-06-24 13:13 UTC by ZhaoTim

英文原文是： 
> Another case where you’ll group data into an object or an array is when you don’t know how many pieces of state you’ll need

现在中文版的翻译是：
> 另一种情况是，你将数据整合到一个对象或一个数组中时，你不知道需要多少个 state 片段。

---

我认为这个翻译已经不是单纯的某个单词有误，而是整个句子的因果关系存在错误。

原文作者想表达是 ： 你会这样做（group data into an object or an array）的场景是因为你不知道未来会存在多少个state。

所以我优化成了：**另一种你需要将数据整合到一个对象或一个数组的情况是，当你不知道未来需要多少个state片段。**

希望得到你的沟通~

2024-06-25 07:00 UTC, awxiaoxian2020 requested changes

2024-06-25 07:00 UTC, awxiaoxian2020 commented on src/content/learn/choosing-the-state-structure.md
> +另一种你需要将数据整合到一个对象或一个数组的情况是，当你不知道未来需要多少个state片段。例如，当你有一个用户可以添加自定义字段的表单时，这将会很有帮助。
```suggestion
另一种你需要将数据整合到一个对象或一个数组的情况是，你不知道未来需要多少个 state 片段。例如，有一个用户可以添加自定义字段的表单时，这将会很有帮助。
```

2024-06-25 08:28 UTC, Ivocin commented
赞，其实中文表达可以换一个语序可能更通顺：
另一种你需要将数据整合到一个对象或一个数组的情况是，你不知道未来需要多少个 state 片段 
-->
如果你不知道将来需要多少个 state 片段时，也可以将数据整合到一个对象或一个数组中。

2024-06-25 12:33 UTC, awxiaoxian2020 approved these changes

2024-06-25 12:33 UTC, merged

2024-06-25 12:34 UTC, awxiaoxian2020 commented
> 赞，其实中文表达可以换一个语序可能更通顺：
> 另一种你需要将数据整合到一个对象或一个数组的情况是，你不知道未来需要多少个 state 片段 
> -->
> 如果你不知道将来需要多少个 state 片段时，也可以将数据整合到一个对象或一个数组中。

没看到评论，我后面改一下，这样确实更好

2024-06-27 08:06 UTC, Ivocin commented
> @Ivocin
> 
> 不好意思我刚刚看到你的回复，确实你优化过后的句子通顺多了！
> 
> 但是不知为何，我读着有一种「割裂感」。因为上一段中，介绍了第一种需要将数据整合到一个对象或者一个数组的情况。
> 
> > 从技术上讲，你可以使用其中任何一种方法。但是，如果某两个 state 变量总是一起变化，则将它们统一成一个 state 变量可能更好。这样你就不会忘记让它们始终保持同步，就像下面这个例子中，移动光标会同时更新红点的两个坐标：
> 
> 那么在下一段中，我猜测 英文文档的作者更想表达的是，除了上一段中的使用场景，还有另一种使用场景。但是你优化过后的句子弱化了这一点，所以我读着就有一种「不连贯」的感觉。
> 
> 这仅仅是我的个人感受，我看到这个commit已经merge了，如果后续你们要改的话，我也是可以接受的~

你说的没错，所以可以这样，保留原译文的“另一种情况是” ：
另一种情况，当你不知道将来需要多少个 state 片段时，也可以将数据整合到一个对象或一个数组中。